= Clojure 1.10.1 release
Alex Miller
2019-06-06
:jbake-type: post

ifdef::env-github,env-browser[:outfilesuffix: .adoc]

Clojure 1.10.1 is a small release focusing on two issues: working around a Java performance regression and improving error reporting from clojure.main.

== Java performance regression

Recent builds of Java 8 (u202), 11 (11.0.2), 12, and 13 included some changes that drastically affect optimization performance of calls from static initializers to static fields. Clojure provides support for loading code on startup from a user.clj file and this occurred in the static initializer of the Clojure runtime (RT) class and was thus affected.

This issue may eventually be resolved in Java, but in Clojure we have modified runtime initialization to avoid loading user.clj in a static initializer, which mitigates the case where this caused a performance degradation.

== clojure.main error reporting

clojure.main is frequently used as a Clojure program launcher by external tools. Previously, uncaught exceptions would be automatically printed by the JVM, which would also print the stack trace.

This release will now catch exceptions and use the same error triage and printing functionality as the Clojure repl. The full stack trace, ex-info, and other information will be printed to a target specified by the configuration. See <<xref/../../../../../reference/repl_and_main#_error_printing,clojure.main docs>> for configuration details.

## Changelog

See the https://github.com/clojure/clojure/blob/master/changes.md#changes-to-clojure-in-version-1101[change log] for a complete list of all changes in Clojure 1.10.1.
