= README
Alex Miller
2015-10-19
:jbake-type: page
:toc: macro

This web site is an open-source repository of content about the Clojure programming language and its greater ecosystem, hosted at https://clojure.org.

== Contributing

If you wish to point out an issue in the site or propose a new page, you can do so by filing a GitHub issue at https://github.com/clojure/clojure-site/issues. 

If you wish to make a contribution (typo, modification, or new content), you must become a contributor and follow the https://github.com/clojure/clojure-site/blob/master/content/community/contributing_site.adoc[contribution process].

== Building the Site

The site is built using http://jbake.org/[JBake].

To https://jbake.org/docs/2.6.5/#installation[install] JBake 2.6.5:

. `curl -L -O https://dl.bintray.com/jbake/binary/jbake-2.6.5-bin.zip` (or download this file with your browser)
. `unzip -o jbake-2.6.5-bin.zip`
. Add jbake-2.6.5-bin/bin to your system PATH

To build the site:

Retrieve the content:

. `git clone https://github.com/clojure/clojure-site.git` (or your own fork)
. `cd clojure-site`

Retrieve and install the current theme assets (these don't change very often so you don't need to do this every time):

. `curl -O https://clojure.org/clojuretheme.zip` (or download this file with your browser to the clojure-site directory)
. `unzip -o clojuretheme.zip`

Generate the pages:

. `jbake -b` - this will create the static site in the output directory
. Run `jbake -s` to serve these pages at http://localhost:8820/index

## Terms of Use

Copyright © 2016-2020 Rich Hickey and contributors

All documentation contained in this repository is licensed by Rich Hickey under the http://www.eclipse.org/legal/epl-v10.html[Eclipse Public License v1.0] unless otherwise noted. To submit a pull request or other contribution, you must sign the http://clojure.org/community/contributing[Clojure Contributor Agreement].
