= Books 
Rich Hickey
2015-01-01
:jbake-type: page
:toc: macro

Please support these fine books about Clojure. (By order of first author surname). 

image::http://ws.assoc-amazon.com/widgets/q?_encoding=UTF8&amp;Format=_SL160_&amp;ASIN=1783986662&amp;MarketPlace=US&amp;ID=AsinImage&amp;WS=1&amp;tag=clojure-20&amp;ServiceVersion=20070822[Clojure Reactive Programming ]
link:http://www.amazon.com/Clojure-Reactive-Programming-Asynchronous-Applications/dp/1783986662[Clojure Reactive Programming ] - Leonardo Borges 

image::http://ws.assoc-amazon.com/widgets/q?_encoding=UTF8&Format=_SL160_&ASIN=1449394701&MarketPlace=US&ID=AsinImage&WS=1&tag=clojure-20&ServiceVersion=20070822[Programming Clojure]
link:http://www.amazon.com/Clojure-Programming-Chas-Emerick/dp/1449394701/ref=sr_1_4?ie=UTF8&qid=1448163622[Programming Clojure] - Chas Emerick, Brian Carper, Christophe Grand

image::http://ws.assoc-amazon.com/widgets/q?_encoding=UTF8&Format=_SL160_&ASIN=1617291412&MarketPlace=US&ID=AsinImage&WS=1&tag=clojure-20&ServiceVersion=20070822[The Joy of Clojure]
link:http://www.amazon.com/Joy-Clojure-Michael-Fogus/dp/1617291412[The Joy of Clojure] - Michael Fogus, Chris Houser

image::http://ws.assoc-amazon.com/widgets/q?_encoding=UTF8&Format=_SL160_&ASIN=1934356867&MarketPlace=US&ID=AsinImage&WS=1&tag=clojure-20&ServiceVersion=20070822[Programming Clojure]
link:http://www.amazon.com/Programming-Clojure-Stuart-Halloway/dp/1934356867[Programming Clojure] - Stuart Halloway, Aaron Bedra 

image::http://ws.assoc-amazon.com/widgets/q?_encoding=UTF8&Format=_SL160_&ASIN=1593275919&MarketPlace=US&ID=AsinImage&WS=1&tag=clojure-20&ServiceVersion=20070822[Clojure for the Brave and True]
link:http://www.amazon.com/Clojure-Brave-True-Ultimate-Programmer/dp/1593275919/ref=sr_1_1?ie=UTF8&qid=1448163622[Clojure for the Brave and True] - Daniel Higginbotham

image::http://ws.assoc-amazon.com/widgets/q?_encoding=UTF8&amp;Format=_SL160_&amp;ASIN=0321927737&amp;MarketPlace=US&amp;ID=AsinImage&amp;WS=1&amp;tag=clojure-20&amp;ServiceVersion=20070822[Clojure Recipes]
link:http://www.amazon.com/Clojure-Recipes-Developers-Library-Julian/dp/0321927737[Clojure Recipes] - Julian Gamble

image::http://ws.assoc-amazon.com/widgets/q?_encoding=UTF8&amp;Format=_SL160_&amp;ASIN=1941222226&amp;MarketPlace=US&amp;ID=AsinImage&amp;WS=1&amp;tag=clojure-20&amp;ServiceVersion=20070822[Mastering Clojure Macros]
link:http://www.amazon.com/Mastering-Clojure-Macros-Cleaner-Smarter/dp/1941222226[Mastering Clojure Macros] - Colin Jones 

image::http://ws.assoc-amazon.com/widgets/q?_encoding=UTF8&amp;Format=_SL160_&amp;ASIN=1784390291&amp;MarketPlace=US&amp;ID=AsinImage&amp;WS=1&amp;tag=clojure-20&amp;ServiceVersion=20070822[Clojure High Performance Programming]
link:http://www.amazon.com/Clojure-Data-Analysis-Cookbook--Second/dp/1784390291[Clojure High Performance Programming] - Shantanu Kumar 

image::http://ws.assoc-amazon.com/widgets/q?_encoding=UTF8&amp;Format=_SL160_&amp;ASIN=1491909048&amp;MarketPlace=US&amp;ID=AsinImage&amp;WS=1&amp;tag=clojure-20&amp;ServiceVersion=20070822[Living Clojure]
link:http://www.amazon.com/Living-Clojure-Carin-Meier/dp/1491909048[Living Clojure] - Carin Meier 

image::http://ws.assoc-amazon.com/widgets/q?_encoding=UTF8&amp;Format=_SL160_&amp;ASIN=1935182595&amp;MarketPlace=US&amp;ID=AsinImage&amp;WS=1&amp;tag=clojure-20&amp;ServiceVersion=20070822[Clojure In Action]
link:http://www.amazon.com/Clojure-Action-Amit-Rathore/dp/1617291528/ref=sr_1_10?ie=UTF8&qid=1448163622[Clojure In Action] - Amit Rathore

image::http://ws.assoc-amazon.com/widgets/q?_encoding=UTF8&amp;Format=_SL160_&amp;ASIN=1784390291&amp;MarketPlace=US&amp;ID=AsinImage&amp;WS=1&amp;tag=clojure-20&amp;ServiceVersion=20070822[Clojure Data Analysis Cookbook]
link:http://www.amazon.com/Clojure-Data-Analysis-Cookbook--Second/dp/1784390291[Clojure Data Analysis Cookbook] - Eric Rochester 

image::http://ws.assoc-amazon.com/widgets/q?_encoding=UTF8&amp;Format=_SL160_&amp;ASIN=1680500821&amp;MarketPlace=US&amp;ID=AsinImage&amp;WS=1&amp;tag=clojure-20&amp;ServiceVersion=20070822[Web Development with Clojure]
link:http://www.amazon.com/Web-Development-Clojure-Build-Bulletproof/dp/1680500821[Web Development with Clojure] - Dmitri Sotnikov 

image::http://ws.assoc-amazon.com/widgets/q?_encoding=UTF8&amp;Format=_SL160_&amp;ASIN=1449366171&amp;MarketPlace=US&amp;ID=AsinImage&amp;WS=1&amp;tag=clojure-20&amp;ServiceVersion=20070822[Clojure Cookbook]
link:http://www.amazon.com/Clojure-Cookbook-Recipes-Functional-Programming/dp/1449366171[Clojure Cookbook] - Luke VanderHart and Ryan Neufeld 

image::http://ws.assoc-amazon.com/widgets/q?_encoding=UTF8&amp;Format=_SL160_&amp;ASIN=1680500740&amp;MarketPlace=US&amp;ID=AsinImage&amp;WS=1&amp;tag=clojure-20&amp;ServiceVersion=20070822[Clojure Applied]
link:http://www.amazon.com/Clojure-Applied-Practitioner-Ben-Vandgrift/dp/1680500740[Clojure Applied] - Ben Vandgrift, Alex Miller

image::http://ws.assoc-amazon.com/widgets/q?_encoding=UTF8&amp;Format=_SL160_&amp;ASIN=1783284358&amp;MarketPlace=US&amp;ID=AsinImage&amp;WS=1&amp;tag=clojure-20&amp;ServiceVersion=20070822[Clojure for Machine Learning]
link:http://www.amazon.com/Clojure-Machine-Learning-Akhil-Wali/dp/1783284358[Clojure for Machine Learning] - Akhil Wali 
