= Contributing to Clojure
Rich Hickey
2016-01-15
:type: community
:toc: macro
:icons: font

ifdef::env-github,env-browser[:outfilesuffix: .adoc]

Following the lead of other open source projects, the Clojure project requires contributors to jointly assign their copyright on contributed code. The https://secure.echosign.com/public/hostedForm?formid=95YMDL576B336E[Contributor Agreement] (CA) gives Rich Hickey and the contributor joint copyright interests in the code: the contributor retains copyrights while also granting those rights to Rich Hickey as the open source project sponsor.

The CA is derived from the Oracle Contributor Agreement (OCA), used for OpenJDK, Netbeans and OpenSolaris projects and others. There is a good http://www.oracle.com/technetwork/oca-faq-405384.pdf[OCA FAQ] answering many questions.

The CA does not change the rights or responsibilities of the Clojure community under the http://opensource.org/licenses/eclipse-1.0.php[Eclipse Public License (EPL)]. By executing the CA, contributors protect the Clojure code base, enable alternative licensing models, and protect the flexibility to adapt the project to the changing demands of the community. In order for the CA to be effective, the Clojure project must obtain an assignment for all contributions. Please review the CA for a complete understanding of its terms and conditions. By contributing source code or other material to Clojure, you represent that you have a CA with Rich Hickey for such contributions. In order to track contributors, you understand that your full name and username may be posted on a web page listing authorized contributors that is accessible via a public URL.

== Instructions for submitting the agreement

* Fill out and submit the https://secure.echosign.com/public/hostedForm?formid=95YMDL576B336E[Contributor Agreement] (an online e-form)

== Making a contribution

Before you invest time working on a change, discuss what you're trying to do with others on the http://groups.google.com/group/clojure-dev[Clojure Dev Google group]. They're likely to be able to offer comments and suggestions that will result in a higher-quality change and a smoother submission process. Announcing that you're working on a particular item can also help to avoid wasted effort in case someone else is already working on it. Once you've submitted the CA, you can http://dev.clojure.org/jira/browse/CLJ[submit patches via JIRA]. Frequent and trusted contributors of more substantial libraries may be granted committer membership in the Clojure contrib projects.

Please see the http://dev.clojure.org/display/community/Contributing[Contributing] wiki for a collection of resources on tickets, builds, patches, source, and more. If you'd like to submit a patch, please follow these guidelines on the http://dev.clojure.org/display/community/JIRA+workflow[preferred process for submitting].

[[contributors]]
== Contributors

See the full <<contributors#,list of contributors>> that have signed the Clojure Contributor Agreement.

[[patches]]
== Contributed patches to Clojure:

* Aaron Bedra
* Aaron Cohen
* Achim Passen
* Alan Dipert
* Alan Malloy
* Alexander Yakushev
* Alex Miller
* Alex Osborne
* Alex Ott
* Alex Redington
* Alexander Taggart
* Alexander Yakushev
* Alf Kristian Stoyle
* Allen Rohner
* Ambrose Bonnaire-Sergeant
* Andrei Kleschinski
* Andrew Rosa
* Andy Fingerhut
* Andy Sheldon
* Anthony Grimes
* Aspasia Beneti
* Baishampayan Ghose
* Ben Smith-Mannschott
* Benjamin Teuber
* Blake West
* Bozhidar Batsov
* Brandon Bloom
* Brenton Ashworth
* Brian Hurt
* Brian Taylor
* Bruce Adams
* Chas Emerick
* Chris Gray
* Chris Houser
* Chris Perkins
* Christoffer Sawicki
* Christophe Grand
* Christopher Redinger
* Clinton R. Nixon
* Colin Jones
* Cosmin Stejerean
* Daniel Compton
* Daniel Solano Gómez
* David Liebke
* David McNeil
* David Miller
* David Powell
* David Rupp
* David Santiago
* Devender Gollapally
* Devin Walters
* Dimitry Gashinsky
* Drew Raines
* Ed Bowler
* Eric Schoonover
* Erik Assum
* Federico Brubacher
* Frantisek Sodomka
* Gabriel Horner
* Gary Fredericks
* George Jahad
* Ghadi Shayban
* Gordon Syme
* Herwig Hochleitner
* Howard Lewis Ship
* Hubert Iwaniuk
* Hugo Duncan
* Immo Heikkinen
* James Reeves
* Jarkko Oranen
* Jason Wolfe
* Jean Niklas L'orange
* Jeremy Heiler
* Joe Gallo
* John Szakmeister
* Jonas Enlund
* Jozef Wagner
* Juha Arpiainen
* Justin Balthrop
* Justin Kramer
* Karsten Schmidt
* Kevin Downey
* Konrad Hinsen
* Kurt Harriger
* Laurent Petit
* Lauri Pesonen
* Luke VanderHart
* Mark Simpson
* Matt Revelle
* Max Penet
* Meikel Brandmeyer
* Micah Martin
* Michael Blume
* Michael Fogus
* Michał Marczyk
* Michel Alexandre Salim
* Mike Anderson
* Mike Hinchey
* Nahuel Greco
* Nicola Mometto
* Nicolas Buduroi
* Nikita Prokopov
* Nola Stowe
* Paul M Bauer
* Paul Stadig
* Pepijn de Vos
* Phil Hagelberg
* Philip Aston
* Philip Potter
* Ragnar Dahlén
* Ralf Schmitt
* Rasmus Svensson
* Rich Hickey
* Richard Newman
* Robert Lachlan
* Russ Olsen
* Scott Lowe
* Sean Devlin
* Shogo Ohta
* Stefan Kamphausen
* Stephen C. Gilardi
* Steve Miner
* Steven Yi
* Stuart Halloway
* Stuart Sierra
* Tassilo Horn
* Tim Dysinger
* Tim McCormack
* Timothy Baldridge
* Timothy Pratley
* Toby Crawley
* Tom Faulhaber
* Tomasz Nurkiewicz
* Tsutomu Yano
* Vipul Amler
* Yanxiang Lou
* Zach Tellman

_**Many thanks for your contributions to Clojure!**_
