= Contributing
Alex Miller
2019-05-01
:type: community
:toc: macro
:icons: font

ifdef::env-github,env-browser[:outfilesuffix: .adoc]

== Ways to Contribute

There are many ways to make a meaningful contribution to the Clojure community:

* Advocate for the use of Clojure in your organization
* Use Clojure and share your experience via talks, blogs, etc
* Start or join a local meetup
* Help new Clojure users in Slack or other forums
* Create or provide patches to open source libraries
* Create or improve Clojure tools
* Write guides or reference documentation for libraries
* Write intros or getting started guides for tools
* Create Clojure podcasts, screencasts, or videos
* Give a talk at a conference
* Write an article or book
* Start a Clojure podcast
* Start a Clojure conference or join the organization team for an existing one
* Test alpha or beta releases of Clojure on your code base and provide feedback

=== Editing this Site

If you are writing a guide, making an event, or creating a resource, please consider contributing to this web site, clojure.org. All of the content is https://github.com/clojure/clojure-site[stored in GitHub] and pull requests and issues are accepted. For more information on how to contribute, see the page on <<contributing_site#,contributing to the site>>. Every page has a link to the corresponding source file in the bottom right corner. If you have an idea for a new guide or updated documentation, please https://github.com/clojure/clojure-site/issues[file an issue] for discussion.

== Reporting Problems and Requesting Enhancements

The Clojure team provides a <<ask#,question forum>> where users can ask questions, submit potential problems, and request enhancements to Clojure, ClojureScript, or Clojure contrib libraries. For all of these cases, please ask a question on the <<ask#,forum>>. Mark the question with tag `problem` for potential problems and `request` for enhancements. The community and core team will assess the issue and determine whether to file an issue in the jira tracker. If an issue is filed, the link will be added to the question and it will be tagged with `jira`.

The development teams for these languages and libs will use the question votes to prioritize their work in jira towards the next release.

== Development

Clojure was created by Rich Hickey and is developed by a core team of developers at https://cognitect.com[Cognitect], which supports this work. The Clojure development team values a measured and thoughtful approach to language evolution with a strong emphasis on maintaining backward compatibility. See <<xref/../../dev/dev#,Development>> for more information on Clojure development.

If you would like to provide a patch on a specific ticket in the jira tracker, please follow the <<xref/../../dev/dev#,process>> to become a contributor.
