= Clojure Downloads
Rich Hickey
2015-01-01
:jbake-type: page
:toc: macro
:icons: font

ifdef::env-github,env-browser[:outfilesuffix: .adoc]

== Stable Release: 1.10.0 (Dec 17, 2018)

* See: <<xref/../../guides/getting_started#,Getting Started>>
* https://repo1.maven.org/maven2/org/clojure/clojure/1.10.0/[Clojure 1.10.0]
* https://github.com/clojure/clojure/blob/master/changes.md[Changelog]
* Requirements: Java 8 or higher (recommended: Java 8 or Java 11)

== Development Release: 1.10.1-beta2

* https://repo1.maven.org/maven2/org/clojure/clojure/1.10.1-beta2/[Clojure 1.10.1-beta2]
* https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22org.clojure%22%20AND%20a%3A%22clojure%22%20AND%20v%3A1.10.1*[Clojure 1.10.1 pre-release builds]
* <<devchangelog#,Dev changelog>>
* Requirements: Java 8 or higher (recommended: Java 8 or Java 11)

== <<downloads_older#,Older Releases>>

== Clojure Source

Clojure source code is hosted at https://github.com/clojure/clojure[github.com/clojure/clojure]. Builds of the very latest version of Clojure's master branch are available at https://oss.sonatype.org/content/repositories/snapshots/org/clojure/clojure/1.11.0-master-SNAPSHOT/[oss.sonatype.org].

== Get Clojure

=== Via deps.edn

Specify the version of Clojure that you want in your deps.edn:

[source,clojure]
----
{:deps
 {org.clojure/clojure {:mvn/version "1.10.0"}}}
----

=== Via Leiningen

Modify the dependencies and repositories sections of your https://leiningen.org/[Leiningen] project.clj file, specifying the version of Clojure that you want:
[source,clojure]
----
; under dependencies, select the release of clojure that you want
:dependencies [[org.clojure/clojure "1.10.0"]]
----

== Using Clojure and contrib SNAPSHOT releases

Most tools do not automatically include the sonatype snapshot repositories. To use SNAPSHOT releases, you must add this to your configuration:

=== In deps.edn

Add an additional repository in deps.edn:

[source,clojure]
----
{:mvn/repos
 {"sonatype-oss-public" {:url "https://oss.sonatype.org/content/groups/public/"}}}
----

=== In Leiningen

Add a snapshot repository in Leiningen in project.clj:

[source,clojure]
----
:repositories {"sonatype-oss-public" "https://oss.sonatype.org/content/groups/public/"}
----

=== In Maven

In pom.xml:

[source,xml]
----
<repositories>
  <repository>
    <id>sonatype-oss-public</id>
    <url>https://oss.sonatype.org/content/groups/public/</url>
    <releases>
      <enabled>true</enabled>
    </releases>
    <snapshots>
      <enabled>true</enabled>
    </snapshots>
  </repository>
</repositories>
----
