= Training
Timothy Pratley
2018-03-06
:type: community
:toc: macro
:icons: font


== For teams

Adding Clojure to your company's capabilities?
Give your employees a head start!
Training services are available for small to large groups.
These courses are typically 1-3 day events with 5-30 people,
in a hotel meeting room. Lunch and snacks included.
Content is tailored to the group.
Prices range from 5 to 15k USD, depending on group size.
Here is list of companies and individuals that offer Clojure training courses.

[options="header"]
|===
| Company | Location | Courses | Link | contact
| Cognitect | North America | All levels | https://cognitect.com/services.html | info@cognitect.com +1 919.283.2748
| BraveAndTrue | North America | All levels | https://www.braveclojure.com/training | daniel@braveclojure.com
| Starweaver | Global | Clojure in a Nutshell | https://www.starweaver.com | USA: +1-646-883-1460 // UK: +44 20 3289 3277 // helpdesk@starweaver.com
| Peter Taoussanis | Europe | Enterprise Clojure | https://www.taoensso.com | ptaoussanis@taoensso.com
| Adam Bard | North America | Clojure Training | http://clojuretraining.ca | learnclojure@adambard.com
|===


== For individuals

Looking for a curated ciriculum to jump start your learning?
Several courses are offered.

=== Online courses

[options="header"]
|===
| Link | Short description
| https://lambdaisland.com | A series of video tutorial about web development using ClojureScript and Clojure
| https://purelyfunctional.tv | Our mission is to help people thrive with Functional Programming.
| https://www.udemy.com/learning-clojure | Will teach you how to write Clojure code and structure Clojure products.
|===

=== ClojureBridge

ClojureBridge aims to increase diversity within the Clojure community by offering free,
beginner-friendly Clojure programming workshops for underrepresented groups in tech.
ClojureBridge holds free training events for women and minorities.
Typically these are 1 day events hosted by one or more sponsors.
http://www.clojurebridge.org


=== Conferences

Clojure training events are held just prior to Clojure/Conj conferences.
This is a great opportunity for individuals to participate in a group training session.
Check out the Clojure/Conj website for details.


== Resources for trainers

* https://github.com/cognitect/clojure-lab
* https://github.com/braveclojure/training
* https://github.com/timothypratley/enterprise-clojure-training


== Maintenance

If you would like to be added or removed from this list,
please contact __alex.miller@cognitect.com__
or submit a pull request.
