= ClojureBridge Boston
ClojureBridge
2016-10-14
:jbake-type: event
:jbake-edition: 2016
:jbake-link: http://www.clojurebridge.org/events/2016-10-14-boston
:jbake-location: Cambridge, MA
:jbake-start: 2016-10-14
:jbake-end: 2016-10-15

ClojureBridge Workshop is aimed at increasing women's participation in the Clojure community. A free 1-day workshop will be held in Cambridge, MA on Saturday October 15 2016 with an optional install fest on Friday late afternoon October 14 2016. The workshop is intended both for those new to programming, as well as those with some programming experience, who would like to explore programming using Clojure, a modern functional programming language.

The workshop will introduce you to fundamental programming concepts and approaches. Participants can choose between two tracks, based on their programming experience. Participants can install the required software for the workshop by themselves. For those who would like help or prefer to to install software as a group, we will meet Friday late afternoon to install all of the software. Saturday will be spent learning and practicing Clojure programming. You will be working in small groups of 2 to 4 attendees each. Each participant needs to bring a laptop computer with a fairly recent operating system (Mac, Linux or Windows). If you have questions about your hardware or you don’t have a laptop, don’t hesitate to send an email to the organizers before the event.

== Who can attend?

The workshop is open to all women, trans*, and gender nonconforming people. Men are welcome if they are an invited guest of a student who qualifies by the above definition. Attendees inviting a guest should select quantity 2 when signing up for tickets, and fill out their guest's information in the 2nd ticket.
