= Home
Rich Hickey
2015-01-01
:jbake-type: page
:toc: macro

ifdef::env-github,env-browser[:outfilesuffix: .adoc]

== Clojure

Clojure is a dynamic programming language that targets the Java Virtual Machine (http://github.com/clojure/clojure-clr[and the CLR], and http://github.com/clojure/clojurescript[JavaScript]). It is designed to be a general-purpose language, combining the approachability and interactive development of a scripting language with an efficient and robust infrastructure for multithreaded programming. Clojure is a compiled language - it compiles directly to JVM bytecode, yet remains completely dynamic. Every feature supported by Clojure is supported at runtime. Clojure provides easy access to the Java frameworks, with optional type hints and type inference, to ensure that calls to Java can avoid reflection.

Clojure is a dialect of Lisp, and shares with Lisp the code-as-data philosophy and a powerful macro system. Clojure is predominantly a functional programming language, and features a rich set of immutable, persistent data structures. When mutable state is needed, Clojure offers a software transactional memory system and reactive Agent system that ensure clean, correct, multithreaded designs.

I hope you find Clojure's combination of facilities elegant, powerful, practical and fun to use.

The primary forum for discussing Clojure is the http://groups.google.com/group/clojure[Google Group] - please join us!

https://twitter.com/richhickey[Rich Hickey] +
CTO http://cognitect.com/[Cognitect], providers of http://cognitect.com/support-document#platform-support[enterprise support] for Clojure

=== Use Clojure 


* <<about/rationale#,Rationale>>
* <<about/features#,Features>>
* <<community/downloads#,Download>>
* <<guides/getting_started#,Getting Started>>
* <<reference/documentation#,Documentation>>
* <<about/clojurescript#,ClojureScript>>
* <<about/clojureclr#,ClojureCLR>>

=== Join the Community 


* http://groups.google.com/group/clojure[Clojure Google Group]
* #clojure on IRC
* http://clojurians.net/[Clojurians Slack Chat]
* http://dev.clojure.org/display/doc/Home[Community Wiki]
* http://clojure-conj.org/[Clojure/conj], http://clojurewest.org[Clojure/West], and http://euroclojure.com/[EuroClojure] conferences
* http://dev.clojure.org/display/community/Clojure+User+Groups[Clojure User Groups]
* http://dev.clojure.org/display/community/Google+Summer+of+Code[Google Summer of Code]

*Clojure is stewarded and supported by Cognitect*

http://cognitect.com/support-document#platform-support[Cognitect provides support for Clojure] including enterprise support, training, and development assistance.