= Applying past software architecture and
2024-01-16
:jbake-type: event
:jbake-edition: 
:jbake-link: https://www.meetup.com/func-prog-sweden/events/297868767/
:jbake-location: online
:jbake-start: 2024-01-16
:jbake-end: 2024-01-16

== Applying past software architecture and design

Welcome to the first Func Prog Sweden MeetUp 2024 &ndash; Online +
This MeetUp will be streamed live online on the Func Prog Sweden YouTube channel: https://www.youtube.com/c/FuncProgSweden +
The program starts at 18. +
 +
Intro by Magnus Sedlacek +
Functional Design: Applying past software architecture and design to our Clojure programs by Janet Carr +
 +
Functional Design: Applying past software architecture and design +
Functional Design covers software design in functional programming with Clojure. Starting with functional programming basics, I'll demonstrate how to build some of the common functional programming abstractions like reducers, and how to think of functional programming abstractions by borrowing concepts from past software design principles. +
Janet Carr +
Independent Clojure consultant +
https://janetacarr.com/ +
https://twitter.com/janetacarr +
Video sponsor &ndash; Ada Beat +
https://adabeat.com +
Merch +
If you want to spread functional programming and support the channel, buy something from the shop: +
https://funcprogsweden.myspreadshop.net/ +
#funcprogsweden +
 +
Zulip: https://clojurians.zulipchat.com/#narrow/stream/262224-events/near/412318401 +

