= Brimm: graph backend with a
2024-03-12
:jbake-type: event
:jbake-edition: 
:jbake-link: https://www.meetup.com/London-Clojurians/events/297612163/
:jbake-location: online
:jbake-start: 2024-03-12
:jbake-end: 2024-03-12

== Brimm: graph backend with a Notion-inspired UI...

Brimm: graph backend with a Notion-inspired UI (by Filip Juruković) +
 +
THIS IS AN ONLINE EVENT +
[Connection details will be shared 1h before the start time] +
The London Clojurians are happy to present: +
Title: Brimm: graph backend with a Notion-inspired UI +
Speaker: Filip Juruković +
Time: 2024-03-12 @ 18:30 (London time) +
Local time: click here for local time +
Filip Juruković (https://github.com/zeitstein) will be presenting: +
&quot;Brimm: graph backend with a Notion-inspired UI&quot; +
In this talk, we'll explore Brimm: a new open source full stack project for knowledge management. We'll showcase the default UI and discuss how you can use Brimm as a tool for thought or a graph CMS. +
Filip is a web developer who fell in love with Clojure because of the parentheses. He's been writing Clojure for several years and has thought about Brimm for more. He is interested in UX, knowledge management and a more open Web. +
If you missed this event, you can watch the recording on our YouTube channel: +
https://www.youtube.com/@LondonClojurians +
(The recording will be uploaded a couple of days after the event.) +
Please, consider supporting the London Clojurians with a small donation: +
https://opencollective.com/london-clojurians/ +
Your contributions will enable the sustainability of the London Clojurians community and support our varied set of online and in-person events: +
 +
ClojureBridge London: supports under-represented groups discover Clojure +
re:Clojure: our free to attend annual community conference +
monthly meetup events with speakers from all over the world +
subscription and admin costs such as domain name &amp; StreamYard subscription +
 +
Thank you to our sponsors: +
 +
https://juxt.pro/ +
https://flexiana.com/ +
And many individual sponsors +
 +
Zulip: https://clojurians.zulipchat.com/#narrow/stream/262224-events/near/404434914 +

