= Bringing Real-Time AI to Phone Calls
2024-03-19
:jbake-type: event
:jbake-edition: 
:jbake-link: https://www.meetup.com/london-clojurians/events/298480748/
:jbake-location: online
:jbake-start: 2024-03-19
:jbake-end: 2024-03-19

== Bringing Real-Time AI to Phone Calls using cor...

Bringing Real-Time AI to Phone Calls using core.async (by Ovi Stoica) +
 +
THIS IS AN ONLINE EVENT +
[Connection details will be shared 1h before the start time] +
The London Clojurians are happy to present: +
Title: Bringing Real-Time AI to Phone Calls using core.async +
Speaker: Ovi Stoica +
Time: 2024-03-19 @ 18:30 (London time) +
Local time: click here for local time +
Ovi Stoica (https://www.ovistoica.com/) will be presenting: +
&quot;Bringing Real-Time AI to Phone Calls using core.async&quot; +
How to bring AI to real-time telephony using Twilio, OpenAI &amp; clojure core.async. The talk will include details about assembling the pipeline, handling audio, and using u/log to find bottlenecks in the pipeline. +
Ovi works for 3E, a company building renewable software in the renewable energy space. He has been working with Clojure for the last 3 years mostly building APIs and Web interfaces. He is passionate about AI, functional programming and bringing clojure to the startup space +
If you missed this event, you can watch the recording on our YouTube channel: +
https://www.youtube.com/@LondonClojurians +
(The recording will be uploaded a couple of days after the event.) +
Please, consider supporting the London Clojurians with a small donation: +
https://opencollective.com/london-clojurians/ +
Your contributions will enable the sustainability of the London Clojurians community and support our varied set of online and in-person events: +
 +
ClojureBridge London: supports under-represented groups discover Clojure +
re:Clojure: our free to attend annual community conference +
monthly meetup events with speakers from all over the world +
subscription and admin costs such as domain name &amp; StreamYard subscription +
 +
Thank you to our sponsors: +
 +
https://juxt.pro/ +
https://flexiana.com/ +
And many individual sponsors +
 +
Zulip: https://clojurians.zulipchat.com/#narrow/stream/262224-events/near/412521148 +

