= Data-recur meeting 5: Datajure
2024-06-29
:jbake-type: event
:jbake-edition: 
:jbake-link: https://clojureverse.org/t/data-recur-meeting-5-datajure-a-dsl-extension-to-existing-data-processing-libraries/10747
:jbake-location: online
:jbake-start: 2024-06-29
:jbake-end: 2024-06-29

== Data-recur meeting 5: Datajure - a DSL extensi...

Data-recur meeting 5: Datajure - a DSL extension to existing data processing libraries +
 +
The data-recur group is a space for collaborations around the emerging Clojure stack for data processing and data analysis. +
This June, it is coming back. +
It will be presented by Matthias Buehlmaier and Yang Ming-Tian from the Business School. +
This meeting will be dedicated to the Datajure, a Domain Specific Language extension for existing data processing libraries such as tech.ml.dataset, tablecloth, clojask and geni. +
Joining +
Please use the Going button at the top of this post to mark your participation. +
You can also use the Add to Calendar button to add the event to your calendar. +
Length +
The official part will be 90 minutes long. +
Sometimes some of us like to stay longer and chat. +
Platform +
 +
Video meeting: Launch Meeting - Zoom +
Text chat: We will use the #data-recur Zulip stream. +
 +
Recording +
Most of the meeting will be recorded and shared publicly. +
Some parts will be unrecorded. +
 +
Zulip: https://clojurians.zulipchat.com/#narrow/stream/262224-events/near/439889919 +

