= Desktop GUI Made Easy
2024-01-16
:jbake-type: event
:jbake-edition: 
:jbake-link: https://www.meetup.com/london-clojurians/events/297092266/
:jbake-location: online
:jbake-start: 2024-01-16
:jbake-end: 2024-01-16

== Desktop GUI Made Easy (by Nikita Prokopov)

THIS IS AN ONLINE EVENT +
[Connection details will be shared 1h before the start time] +
The London Clojurians are happy to present: +
Title: Desktop GUI Made Easy +
Speaker: Nikita Prokopov +
Time: 2024-01-16 @ 18:30 (London time) +
Local time: click here for local time +
Nikita Prokopov (https://tonsky.me/) will be presenting: +
&quot;Desktop GUI Made Easy&quot; +
Introduction into Humble UI, new JVM Clojure library for desktop GUI application. Why is it needed, how is it implemented, how deep is the rabbit hole, who could it be useful to, what can you build in it? +
Nikita has been programming in Clojure, Java, Python, Erlang for 18 years, been interested in UI/UX design for about the same amount of time, and created a few notable projects, including DataScript, Rum, Fira Code and now Humble UI. +
If you missed this event, you can watch the recording on our YouTube channel: +
https://www.youtube.com/@LondonClojurians +
(The recording will be uploaded a couple of days after the event.) +
Please, consider supporting the London Clojurians with a small donation: +
https://opencollective.com/london-clojurians/ +
Your contributions will enable the sustainability of the London Clojurians community and support our varied set of online and in-person events: +
 +
ClojureBridge London: supports under-represented groups discover Clojure +
re:Clojure: our free to attend annual community conference +
monthly meetup events with speakers from all over the world +
subscription and admin costs such as domain name &amp; StreamYard subscription +
 +
Thank you to our sponsors: +
 +
https://juxt.pro/ +
https://flexiana.com/ +
https://gaiwan.co/ +
And many individual sponsors +
 +
Zulip: https://clojurians.zulipchat.com/#narrow/stream/262224-events/near/404435087 +

