= HYBRID: Immutable Databases to Set Your
2024-04-10
:jbake-type: event
:jbake-edition: 
:jbake-link: https://www.meetup.com/madison-clojure-meetup/events/299793692
:jbake-location: online
:jbake-start: 2024-04-10
:jbake-end: 2024-04-11

== HYBRID: Immutable Databases to Set Your Distri...

HYBRID: Immutable Databases to Set Your Distributed System Free +
 +
Writing software is just great until you need to get two different machines to agree on some state. Then you have to start solving some difficult problems. In Clojure we can see how immutable data makes building concurrent programs manageable -- what if we could apply those same lessons to our distributed systems? We'll talk about what an immutable database is, how it works in principle and in practice, and why you'll want to use one to make your life easier. +
The talk will also be streamed live and a VOD will be posted later: https://youtube.com/live/zx4HGVx9NR8 +
Agenda: +
 +
6:30pm arrive, pizza served +
7:00pm talk +
7:45pm all questions +
8:00pm end stream, offline questions +
8:30pm end meetup, people who want to hang out can choose from nearby bars and restaurants +
 +
Zulip: https://clojurians.zulipchat.com/#narrow/stream/262224-events/near/432397097 +

