= Is there a place for LLM orchestration
2024-04-09
:jbake-type: event
:jbake-edition: 
:jbake-link: https://www.meetup.com/London-Clojurians/events/299650081/
:jbake-location: online
:jbake-start: 2024-04-09
:jbake-end: 2024-04-09

== Is there a place for LLM orchestration tools? ...

Is there a place for LLM orchestration tools? (by Žygimantas Medelis) +
 +
THIS IS AN ONLINE EVENT +
[Connection details will be shared 1h before the start time] +
The London Clojurians are happy to present: +
Title: Is there a place for LLM orchestration tools? +
Speaker: Žygimantas Medelis +
Time: 2024-04-09 @ 18:30 (London time) +
Local time: click here for local time +
Žygimantas Medelis (https://x.com/zzgmm) will be presenting: +
&quot;Is there a place for LLM orchestration tools?&quot; +
Every second week LLM space is hit by a major announcement of new models and improved AI capabilities. Given this breakneck progress, do we need a layer of LLM orchestration tools? I argue that the answer is yes, and I'll use Bosquet &ndash; an LLM tooling library &ndash; to illustrate my point. I will show that going beyond simple LLM apps you will need support for complex promoting and workflows, model swapping, memory management, and similar functionality offered by LLM tools like Bosquet. +
Žygis has been working in Clojure, Natural Language Processing, and adjacent fields for about 15 years, and is always interested in ways to extract meaning from all the messy data we are producing. Very excited about LLMs - a technology that might finally allows us to do just that. +
If you missed this event, you can watch the recording on our YouTube channel: +
https://www.youtube.com/@LondonClojurians +
(The recording will be uploaded a couple of days after the event.) +
Please, consider supporting the London Clojurians with a small donation: +
https://opencollective.com/london-clojurians/ +
Your contributions will enable the sustainability of the London Clojurians community and support our varied set of online and in-person events: +
 +
ClojureBridge London: supports under-represented groups discover Clojure +
re:Clojure: our free to attend annual community conference +
monthly meetup events with speakers from all over the world +
subscription and admin costs such as domain name &amp; StreamYard subscription +
 +
Thank you to our sponsors: +
 +
https://juxt.pro/ +
https://flexiana.com/ +
And many individual sponsors +
 +
Zulip: https://clojurians.zulipchat.com/#narrow/stream/262224-events/near/426007215 +

