= Real-world-data meeting 1
2024-03-22
:jbake-type: event
:jbake-edition: 
:jbake-link: https://clojureverse.org/t/real-world-data-meeting-1/10613
:jbake-location: online
:jbake-start: 2024-03-22
:jbake-end: 2024-03-22

== Real-world-data meeting 1

The Scicloj real-world-data group is a new space for Clojurians working on data and science projects. +
It is a safe space for sharing successes, troubles, problems, hopes, and doubts. Data analytics, machine learning, AI, data engineering, scientific computing, and data visualization are all welcome. +
The group will meet regularly every couple of weeks. This will be the first meeting. +
Session agenda +
(this section will evolve gradually) +
Participating +
If you wish to use Clojure for a data or science project and prefer not to be alone in that journey, this group is for you. +
We will also assume that you either know some Clojure or have a serious intention to learn it. +
To join, please reach out to us by contacting Daniel Slutsky at the Clojurians Zulip chat, or ar the various Scicloj ways of contact. We will think together about whether this group fits your path. +
Recording +
The session will be partially recorded. Possibly, some parts of the recording will be shared publicly. +
Chat +
The group will use the Clojurians Zulip chat. Specifically, the #real-world-data stream. +
More information +
Please check the group page for additional information. +
 +
Zulip: https://clojurians.zulipchat.com/#narrow/stream/262224-events/near/425187632 +

