= Reifying execution, the interactive
2024-01-09
:jbake-type: event
:jbake-edition: 
:jbake-link: https://www.meetup.com/London-Clojurians/events/297594133/
:jbake-location: online
:jbake-start: 2024-01-09
:jbake-end: 2024-01-09

== Reifying execution, the interactive programmin...

Reifying execution, the interactive programming missing piece (by Juan Monetta) +
 +
THIS IS AN ONLINE EVENT +
[Connection details will be shared 1h before the start time] +
The London Clojurians are happy to present: +
Title: Reifying execution, the interactive programming missing piece +
Speaker: Juan Monetta +
Time: 2024-01-09 @ 18:30 (London time) +
Local time: click here for local time +
Juan Monetta (https://github.com/jpmonettas/) will be presenting: +
&quot;Reifying execution, the interactive programming missing piece&quot; +
This is a talk about recording Clojure programs executions, and how this recordings can be leveraged, specially in the context of interactive programming. From making sense of complex systems to debugging, from test coverage, to approximate types extraction, we will explore some instrumentation techniques, and demo a bunch of tools built for recording and visualizing programs executions. +
Juan has been working as a programmer since late 90s, and working professionally as a Clojure developer since 2011 over many domains. He has a passion for dev tooling and anything that makes writing software more fun. +
If you missed this event, you can watch the recording on our YouTube channel: +
https://www.youtube.com/@LondonClojurians +
(The recording will be uploaded a couple of days after the event.) +
Please, consider supporting the London Clojurians with a small donation: +
https://opencollective.com/london-clojurians/ +
Your contributions will enable the sustainability of the London Clojurians community and support our varied set of online and in-person events: +
 +
ClojureBridge London: supports under-represented groups discover Clojure +
re:Clojure: our free to attend annual community conference +
monthly meetup events with speakers from all over the world +
subscription and admin costs such as domain name &amp; StreamYard subscription +
 +
Thank you to our sponsors: +
 +
https://juxt.pro/ +
https://flexiana.com/ +
https://gaiwan.co/ +
And many individual sponsors +
 +
Zulip: https://clojurians.zulipchat.com/#narrow/stream/262224-events/near/404434830 +

