= Sitefox framework
2024-02-27
:jbake-type: event
:jbake-edition: 
:jbake-link: https://www.meetup.com/london-clojurians/events/297830419/
:jbake-location: online
:jbake-start: 2024-02-27
:jbake-end: 2024-02-27

== Sitefox framework: ClojureScript on the backen...

Sitefox framework: ClojureScript on the backend (by Chris McCormick) +
 +
THIS IS AN ONLINE EVENT +
[Connection details will be shared 1h before the start time] +
The London Clojurians are happy to present: +
Title: Sitefox framework: ClojureScript on the backend +
Speaker: Chris McCormick +
Time: 2024-02-27 @ 18:30 (London time) +
Local time: click here for local time +
Chris McCormick (https://mccormick.cx) will be presenting: +
&quot;Sitefox framework: ClojureScript on the backend&quot; +
You'll learn a fast way to build web backends (and frontends) in 100% ClojureScript. Leveraging the Node.js ecosystem Sitefox aims to solve the same problems for ClojureScript as Django does for Python, and Ruby on Rails does for Ruby. Since 2021 I've been using it to build web apps for thousands of users with indie-scale resources, and I'd like to show you how you can too. +
Chris is an independent programmer who has been building software for decades for clients, side projects, and open source. He started using ClojureScript in 2015 and hasn't looked back. These days he is building full-stack web and SaaS apps on 100% cljs. +
If you missed this event, you can watch the recording on our YouTube channel: +
https://www.youtube.com/@LondonClojurians +
(The recording will be uploaded a couple of days after the event.) +
Please, consider supporting the London Clojurians with a small donation: +
https://opencollective.com/london-clojurians/ +
Your contributions will enable the sustainability of the London Clojurians community and support our varied set of online and in-person events: +
 +
ClojureBridge London: supports under-represented groups discover Clojure +
re:Clojure: our free to attend annual community conference +
monthly meetup events with speakers from all over the world +
subscription and admin costs such as domain name &amp; StreamYard subscription +
 +
Thank you to our sponsors: +
 +
https://juxt.pro/ +
https://flexiana.com/ +
And many individual sponsors +
 +
Zulip: https://clojurians.zulipchat.com/#narrow/stream/262224-events/near/407938736 +

