= The Design of Biff (by Jacob O'Bryant)
2024-03-05
:jbake-type: event
:jbake-edition: 
:jbake-link: https://www.meetup.com/london-clojurians/events/297926307/
:jbake-location: online
:jbake-start: 2024-03-05
:jbake-end: 2024-03-05

== The Design of Biff (by Jacob O'Bryant)

THIS IS AN ONLINE EVENT +
[Connection details will be shared 1h before the start time] +
The London Clojurians are happy to present: +
Title: The Design of Biff +
Speaker: Jacob O'Bryant +
Time: 2024-03-05 @ 18:30 (London time) +
Local time: click here for local time +
Jacob O'Bryant (https://tfos.co) will be presenting: +
&quot;The Design of Biff&quot; +
We'll take a behind-the-scenes tour of Biff, everyone's favorite 4-letter Clojure web framework. Learn about the design tradeoffs and implementation details that help Biff to put solo developers first. +
Jacob has been a full-time Clojurist since 2019, when he started living the dream as an entrepreneur. In 2023, after getting sick of living the dream, he joined Tyba, a startup in the renewable energy industry (they use Clojure btw). Jacob is also a musician, father of two, and connoisseur of fine dad jokes. +
If you missed this event, you can watch the recording on our YouTube channel: +
https://www.youtube.com/@LondonClojurians +
(The recording will be uploaded a couple of days after the event.) +
Please, consider supporting the London Clojurians with a small donation: +
https://opencollective.com/london-clojurians/ +
Your contributions will enable the sustainability of the London Clojurians community and support our varied set of online and in-person events: +
 +
ClojureBridge London: supports under-represented groups discover Clojure +
re:Clojure: our free to attend annual community conference +
monthly meetup events with speakers from all over the world +
subscription and admin costs such as domain name &amp; StreamYard subscription +
 +
Thank you to our sponsors: +
 +
https://juxt.pro/ +
https://flexiana.com/ +
And many individual sponsors +
 +
Zulip: https://clojurians.zulipchat.com/#narrow/stream/262224-events/near/407938760 +

