= Visual-tools meeting 24
2024-04-26
:jbake-type: event
:jbake-edition: 
:jbake-link: https://clojureverse.org/t/visual-tools-meeting-24-badspreadsheet-and-htmx/10679
:jbake-location: online
:jbake-start: 2024-04-26
:jbake-end: 2024-04-26

== Visual-tools meeting 24 - badspreadsheet and HTMX

The visual tools group will have its 24th meeting on April 26th. +
Agenda +
 +
Adam James will discuss badspreadsheet - A Clojure Spreadsheet for building design tools. +
As time permits, we will also use this opportunity to discuss HTMX (which is used by badspreadsheets), following some recent community interest. +
 +
Preparing +
 +
Please read the README, the attached videos, and the explanations. +
Please read the discussion at the Clojurians Slack.  Your comments and questions there will help a lot in preparing the meeting. +
 +
Joining +
Please write to @daslu or comment below if you wish to participate. You can also use the Add to Calendar to add the event to your calendar. +
Length +
The official part will be 90 minutes long. +
Sometimes, some of us like to stay longer and chat. +
Video Call +
Zoom link: Launch Meeting - Zoom +
Recording +
Possibly, we will share a recording of parts of the meeting. This has not been decided yet. +
image720&times;441 104 KB +
 +
Zulip: https://clojurians.zulipchat.com/#narrow/stream/262224-events/near/432727353 +

