= Source Libs and Builds
Fogus
2021-07-08
:jbake-type: post

ifdef::env-github,env-browser[:outfilesuffix: .adoc]

Several years ago, Clojure introduced https://clojure.org/reference/deps_and_cli#_deps_edn[deps.edn] (a data definition for dependencies), https://github.com/clojure/tools.deps.alpha/[tools.deps] (a library for computing classpaths), and the 
https://clojure.org/reference/deps_and_cli[Clojure CLI] to run programs. The Clojure community has widely adopted these, but some functionality was missing when it came to building artifacts to share with others. We are excited today to provide some new things in this area:

* https://github.com/clojure/tools.build/[tools.build] - a library for building artifacts
* CLI updates to make working with source repos as libs easier
* CLI updates for installing, introspecting, and using custom tools

Builds are processes and are best represented as programs. The tools.build library provides building blocks to write build programs - this is a modular and compositional approach to artifact building, making the best use of Clojure itself as the language. 

We also take advantage of Clojure's dynamic nature to use source repositories directly as libraries, avoiding the overhead of building, deploying, and consuming artifacts. While most Clojure libraries can be consumed directly as source, sometimes they require a preparation step (like compiling Java in mixed source projects). We've added support for this as well.

Finally, we've enhanced support for making, installing, and running custom tools that don't use the project classpath. Tools embrace all of the ideas above and require only a git repository for others to install and run.

== Builds are Programs

The new https://github.com/clojure/tools.build[tools.build] library is a set of helper functions for writing build programs. To add a build for your deps.edn project, you will:

* Write a Clojure program that uses tools.build to build your project
* Provide function entry points in your program that take a map for whatever targets make sense (things like `clean` or `jar`)
* Add an alias to your deps.edn that invokes your build program and includes tools.build as a dependency
* Invoke the build as at tool using -T. -T is similar to -X but does not include the project classpath and does include the root of the project as one of the `:path`.

For more details and full examples, see the following:

* https://clojure.github.io/tools.build[tools.build API]
* https://clojure.org/guides/tools_build#source-library-jar-build[tools.build guide]

Often, you may want to call multiple functions in your build program. The Clojure CLI has been extended to support the invocation of multiple functions in a row, and also to take a set of additional parameters as a trailing map (similar to the https://clojure.org/news/2021/03/18/apis-serving-people-and-programs[functionality] added in Clojure 1.11 alphas). You can use this functionality to parameterize your build as needed - see the guide for an example.

== Source Repos as Libs

Due to Clojure’s dynamic nature, we can directly use source repositories as libraries without the overhead of making, distributing, and consuming artifacts. This release provides some new updates for git libraries:

* 

 allows us to rethink the way that libraries and applications are created to work directly with source code as our dependencies than requiring deployed artifacts. While the Clojure CLI has long supported git-based deps, it has been somewhat cumbersome to define a git-based dependency: there was no library name convention, the library name often repeated much of the url, there was no support for developer-named versions via tags, etc. While the previous format is still supported, the new format defines a convention for git libraries to infer the url, and the ability to specify meaningful versions via git tags. The short sha prefix is still included to verify the tag has not moved since definition:

```clojure
{:deps {GIT-LIB {:git/tag "TAG" :git/sha "SHA"}
```

If GIT-LIB uses the naming convention, no `:git/url` is required. For example:

```clojure
{:deps {io.github.clojure/tools.deps.graph {:git/tag "v1.0.63" :git/sha "0b569d6"}}}
```

Here, the reversed url of a repository's GitHub pages is used to infer the git url `"https://github.com/clojure/tools.deps.graph.git"`. Similar conventions exist for GitLab, Bitbucket, etc. Rather than supply the full 40 character git sha, it is sufficient here to use a meaningful git tag name and a short sha that is used to verify the tag location. More information on specifying Git source dependencies is found in the https://clojure.org/reference/deps_and_cli#using-git-libraries[CLI and deps guide].

Occasionally, source dependencies will require preparation (e.g. compilation, text replacement, etc.) before they’re suitable for inclusion on the classpath. A common type of “unprepped” is a Clojure library with some Java source requiring compilation. A source-based lib can declare how it should be prepped in its deps.edn:

```clojure
{:deps/prep-lib {:alias :build
                 :fn compile
                 :ensure "target/classes"}}
```

The Clojure CLI library will check for the presence of the `target/classes` directory and if it’s not found, program execution will not proceed. To tell the CLI to prepare this (and any other libraries), you can run the command:

```shell
clj -X:deps prep
```

This command will find the unprepped lib (and any others), and run the `compile` function using the `:build` alias, presumably filling the `target/classes` directory with necessary classes to put on the classpath (`"target/classes"` should be in the project `:paths`). More information on supporting unprepped dependencies is available in the https://clojure.org/reference/deps_and_cli#preparing-source-dependency-libs[Clojure CLI reference]. In the next section we'll talk about the new tools.build library which can be used to do that compilation when needed.

== Tools

You can also run the CLI command `clj -X:deps:build help/doc` if tools.build is a dependency in your deps.edn file under the `build` alias.


In addition to the support for builds, the Clojure CLI was enhanced with the ability to explore, install, invoke, and introspect tools based on a set of conventions for tool creators. Installing a new tool such as Sean Corfield's https://github.com/seancorfield/clj-new[clj-new] library is a simple as running the following command:

```bash
clj -Ttools install io.github.seancorfield/clj-new '{:git/tag "v1.1.309"}' :as new
```

The use of a Git library name `io.github.seancorfield/clj-new` and a coordinate tag `v1.1.309` allows the CLI to find, build, and install the tool as `new`, which is the name that is used for invocation, a la `clj -Tnew <function> <args>`. In this one case, a `:sha` is not required (but it will be determined and rememembered to check for a match in the future).

The CLI also provides a way to explore the available versions of tools with the `clj -X:deps find-versions` command that will list the tags available for that tool. There's more to the tools story including listing installed tools, uninstalling tools, and even exploring the available functions and their details for an installed tool using the https://clojure.org/reference/deps_and_cli#other-programs[help/doc and help/dir functions]. One additional feature added to the CLI is the ability to pass https://clojure.org/reference/deps_and_cli##trailing-map-argument[a trailing map] that represents new or augmenting key value pairs as the arguments to invoke functions.

More information on the new https://clojure.org/reference/deps_and_cli#tool_install[tools support in the CLI] is available in the reference docs.

== Installation

A prerelease version of the CLI is now available: VERSION.

On Mac or Linux, you can install the prerelease https://github.com/clojure/homebrew-tools#version-archive-tool-releases[using brew]. On Linux or Windows you can use the installer per the instructions in https://clojure.org/guides/getting_started[Getting Started] to install the specific version above.

== What's Changed

All items below are additive updates, there should be no changes required for existing deps.edn projects or CLI usage.

* https://github.com/clojure/tools.build[tools.build] - a new library for builds
** https://clojure.github.io/tools.build[API]
** https://clojure.org/guides/tools_build[Guide]
* deps.edn:
*** If a git library name follows repo convention names, the `:git/url` can now be inferred (`:git/url` can still be specificed explicitly and takes precedence)
*** `:git/tag` and short `:git/sha` can now be specified instead of the full sha. Both must point to the same commit.
*** `:sha` has been renamed to `:git/sha` but the original is still supported for backwards compatibility
*** A new `:deps/prep-lib` top-level key is used to publish how a lib can be prepared
*** A new `: 
* https://clojure.org/reference/deps_and_cli[Clojure CLI]
* https://github.com/clojure/tools.deps.alpha[tools.deps.alpha]
** New API functions available via the built-in `:deps` alias
** New library API: `create-basis` (also available in tools.build - use that one if writing a build program)
* https://github.com/clojure/tools.tools[tools.tools] - a tool library for managing tools
** https://clojure.github.io/tools.build[API]
** tools.tools is auto-installed by the Clojure CLI as a tool named `tools`

Clojure now has a built-in story for source deps, builds, and tools including:

- Source deps support - better git deps (https://clojure.org/reference/deps_and_cli#_git[reference]), support for source libs requiring prep (https://clojure.org/reference/deps_and_cli#prep[reference])
- tools.build - a new library for writing build programs (https://clojure.github.io/tools.build[API], , https://github.com/clojure/tools.build[source])
- -X support for running multiple functions at the CLI (https://clojure.org/reference/deps_and_cli#_executing_a_function[reference]) and passing trailing maps as arguments (https://clojure.org/reference/deps_and_cli##trailing-map-argument[reference])
- Tool support - tool installation and use (https://clojure.org/reference/deps_and_cli#tool_install[reference]), better introspection (https://clojure.org/reference/deps_and_cli#other-programs[reference])



You may also want to check out https://www.youtube.com/watch?v=BTAx-gFz6Ks[Alex Miller's talk] about this release at clojureD.

Issues and bugs can be reported on https://ask.clojure.org or in Clojurians Slack in #tools-deps.
