= Clojure/conj 2024 Registration
Alex Miller
2024-05-30
:jbake-type: post

ifdef::env-github,env-browser[:outfilesuffix: .adoc]

https://2024.clojure-conj.org[Clojure/conj] is the oldest gathering of the Clojure community - join us for the next edition on Oct 23-25, 2024! We will be returning to the George Washington Masonic National Memorial in Alexandria, VA -- we were last there in 2013.

Conference overview:

* Oct 23 - 1 pm start, self-organizing unsessions
* Oct 24 - dual track all-day sessions
* Oct 25 - community day, single-track, free streaming

https://ti.to/nubank/clojureconj-2024[Registration is open now!] A limited number of early bird tickets are available for $450. When those are gone, regular registration will begin for $550. Groups of 4 or more can register for $500/ticket. No ticket needed for streaming - we will publish information for access closer to the conference.

The https://2024.clojure-conj.org/#/prospectus[Sponsorship Prospectus] is available now - if you're looking to hire or connect to Clojure developers, this is for you! Thanks for supporting the conference and the Clojure community.

The Call for Papers will open soon, stay tuned!

Questions? Contact us at clojure-conj@nubank.com.br.