= Atomic Architecture
2023-10-04
:jbake-type: event
:jbake-edition: 
:jbake-link: https://us06web.zoom.us/webinar/register/WN_DgHl4OG2Sdq5VbgJ_IyeFw
:jbake-location: online
:jbake-start: 2023-10-04
:jbake-end: 2023-10-04

== Atomic Architecture

Atomic Architecture — An Architectural Vision for Better Information Systems +
 +
As part of our drive to design better data systems for our customers, we’ve identified 7 architectural principles that yield exceptional results. +
 +
In this webinar, JUXT CTO & co-founder — Malcolm Sparks — will explain the principles behind Atomic Architecture, an architectural blueprint for building reliable information systems. +
 +
Malcolm will argue that current trends in software architecture create unnecessary complexity, delivering poor outcomes for users. +
 +
Atomic Architecture incorporates key ideas and principles from Functional Programming, Domain Driven Design, Event Driven Architecture, Data Mesh and more — to let data take back its central place at the heart of a distributed information system. +
 +
A system that is built with the principles of Atomic Architecture has a number of benefits, across the entire data set: +
* A single source of truth +
* Full auditability with historical versioning: who did what? what happened when?  +
* Secure object-level access control +
 +
Key takeaways from this session: +
1. In practical terms, learn how to design a system that's compliant with Atomic Architecture +
2. Discover available tools and technologies +
3. See how to integrate Atomic Architecture into existing software infrastructure +
 +
 +
Zulip: https://clojurians.zulipchat.com/#narrow/stream/262224-events/near/392335860 +

