= Betting your company on Lisp
2023-06-27
:jbake-type: event
:jbake-edition: 
:jbake-link: https://www.meetup.com/london-clojurians/events/292730420/
:jbake-location: 
:jbake-start: 2023-06-27
:jbake-end: 2023-06-27

== Betting your company on Lisp: 5 years with Clo...

Betting your company on Lisp: 5 years with Clojure in Prod (by Adam Tornhill) +
 +
**THIS IS AN ONLINE EVENT** +
[Connection details will be shared 1h before the start time] +
The London Clojurians are happy to present: +
Title: **Betting your company on Lisp: 5 years with Clojure in production** +
Speaker: **Adam Tornhill** +
Time: **2023-06-27 @ 18:30 (London time)** +
Local time: https://time.is/1830_27_June_2023_in_London/ (click here for local time) +
Adam Tornhill (https://twitter.com/AdamTornhill) will be presenting: +
&quot;Betting your company on Lisp: 5 years with Clojure in production&quot; +
Functional Programming is sold as a silver bullet, yet many +
organizations lack real-world experience with the paradigm at +
scale. How well does functional programming work in practice? What +
happens when you bet your company on a functional programming language like Clojure? In this talk, Adam shares his experience from building the CodeScene tool and how the FP hype transferred into real +
productivity gains and cheaper maintenance. +
Adam Tornhill is a programmer who combines degrees in engineering and +
psychology. He&rsquo;s the founder of CodeScene, the leading Software +
Engineering Intelligence tool. Adam is also the author of multiple +
technical books, including the best-selling Your Code as a Crime +
Scene. Adam&rsquo;s other interests include modern history, music, retro +
computing, and martial arts. +
If you missed this event, you can watch the recording on our YouTube channel: +
https://www.youtube.com/@LondonClojurians +
(The recording will be uploaded a couple of days after the event.) +
Please, consider supporting the London Clojurians with a small donation: +
https://opencollective.com/london-clojurians/ +
Your contributions will enable the sustainability of the London +
Clojurians community and support our varied set of online and +
in-person events: +
- ClojureBridge London: supports under-represented groups discover Clojure +
- re:Clojure: our **free** to attend annual community conference +
- monthly meetup events with speakers from all over the world +
- subscription and admin costs such as domain name &amp; Zoom plan for +
larger online meetups +
Thank you to our sponsors: +
- https://juxt.pro/ +
- https://flexiana.com/ +
- https://gaiwan.co/ +
- https://freshcodeit.com/ +
- https://nette.io/ +
- https://nilenso.com/ +
- And many individual sponsors +
 +
Zulip: https://clojurians.zulipchat.com/#narrow/stream/262224-events/near/348201020 +

