= Blambda! The sound of Babashka and
2023-02-23
:jbake-type: event
:jbake-edition: 
:jbake-link: https://www.meetup.com/sthlm-clj/events/291204199/
:jbake-location: online
:jbake-start: 2023-02-23
:jbake-end: 2023-02-23

== Blambda! The sound of Babashka and Lambda coll...

Blambda! The sound of Babashka and Lambda colliding. +
 +
 +
The presentations will be streamed via https://www.youtube.com/watch?v=NfgYon96dsE +
 +
Join us for pizza and drinks (non-alcoholic and alcoholic) and two talks for the price of none! +
Please note: Spaces are quite limited + we will be buying food and drinks. Please, please, make sure to only RSVP yes if you are sure you are coming. If your plans change, update your response as well! +
Give me Interactive Programming or give me Death - Peter Str&ouml;mberg +
Peter strolls down memory lane piecing together his answer to the question &ldquo;what makes work fun?&rdquo; He visits himself with his first computer, a Commodore VIC 20, and recalls his years programming PostScript printers. When, much later in life, he meets the Clojure REPL it feels like love at first sight! But is it actually first sight, or is it a reunion with his teenage sweetheart? +
Blambda! The sound of Babashka and Lambda colliding - Josh Glover +
&ldquo;Clojure on AWS Lambda, how hard could it be?&rdquo; The answer to these famous last words turns out to be, &ldquo;not so hard, actually.&rdquo; So perhaps the better question is this: &ldquo;Clojure on AWS Lambda without slow deployments, long coldstarts, gross tools like Docker and NPM, and a feedback loop that makes you want to give up and go back to C; how hard could it be?&rdquo; Now that sounds like a fun question for Josh to answer in this talk! +
The venue: +
Thanks to Agical for hosting us! +
Agical helps businesses keep the fun in software development. Amongst us we count programmers, user experience designers, and leadership experts. Sometimes all of it in the same consultants. +
The food and drink: +
Thanks to Pitch for providing sustenance! +
Pitch is the collaborative presentation platform for modern teams. Founded in 2018 by the team behind Wunderlist, thousands of teams use Pitch to create and deliver beautiful presentations together. +
 +
Zulip: https://clojurians.zulipchat.com/#narrow/stream/262224-events/near/328949818 +

