= Clojure-Asia meetup
2023-02-25
:jbake-type: event
:jbake-edition: 
:jbake-link: https://forms.gle/LgUWoU6U9ueD4Tue8
:jbake-location: online
:jbake-start: 2023-02-25
:jbake-end: 2023-02-25

== Clojure-Asia meetup

Hello my fellow Clojurians! : We will be having another Clojure-Asia Online Meetup for the month of February! :D +
 +
We currently do not have any talk planned but we can have a good catch up session! :) +
 +
Sessions are typically such that the talk will be followed by QnA/discussion. Hope to see you there! :D +
 +
Meeting Details: +
Date: 25th February 2023 (Saturday) +
Time: 1330-1500 SGT (0530-0700 UTC) +
Location: Jitsi (Easy to setup open source video conferencing) (will email the link in time) +
 +
Contact Info: +
Email: clojure.asia@gmail.com +
Slack/Telegram: @zackteo +
 +
Please fill up the form here: https://forms.gle/LgUWoU6U9ueD4Tue8 +
 +
Also: +
Do join us on the #clojure-asia channel in the Clojurian Slack: https://clojurians.slack.com/archives/C02N2TTDVT5 +
 +
Here's the google calendar link for planned Clojure-Asia Meetups in 2023 (every 3rd Saturday of the month): https://calendar.google.com/calendar/u/0?cid=OWRtcjQ5Z29ybmNydjNna3FoZWoxdWRhczRAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ +
 +
Zulip: https://clojurians.zulipchat.com/#narrow/stream/262224-events/near/329674423 +

