= Clojure-Asia May 2023;  Goose - Akstat
2023-05-27
:jbake-type: event
:jbake-edition: 
:jbake-link: https://clojureverse.org/t/next-level-background-processing-goose-akshat-clojure-asia-05-23-online-meetup/10015/
:jbake-location: online
:jbake-start: 2023-05-27
:jbake-end: 2023-05-27

== Clojure-Asia May 2023;  Goose - Akstat

Next-level Background Processing (Goose) - Akshat +
 +
#clojure-asia May 2023 Meetup +
 +
Date: 27th May 2023 (Saturday) +
Time: 1330-1500 SGT (0530-0700 UTC) +
 +
Akshat will be giving a talk titled: Next-level Background Processing +
 +
Abstract: +
 +
Conventional background processing libraries have failed to keep up with the demands of distributed systems in 2023. This talk will explore the key features that modern web developers require from an asynchronous system: Reliability, Scalability, Pluggability, and Extensibility. +
 +
Furthermore, we'll talk about the journey of building Goose, a versatile background processing library for Clojure designed with next-level features like pluggable message brokers. Goose serves as specimen for open-source libraries, as it exemplifies community-collaboration, thorough documentation, and built-in reliability. +
 +
Please fill up the signup form :) +
https://forms.gle/1Wpa3xcXvsQMD1C6A +
 +
Zachary (zackteo) +
 +
 +
Zulip: https://clojurians.zulipchat.com/#narrow/stream/262224-events/near/359694126 +

