= Clojure/Conj 2023
2023-04-27
:jbake-type: event
:jbake-edition: 
:jbake-link: https://2023.clojure-conj.org/
:jbake-location: 
:jbake-start: 2023-04-27
:jbake-end: 2023-04-28

== Clojure/Conj 2023

....
Clojure/conj 2023 welcomes you back to Durham, after its discontinuation following the COVID-19 pandemic. This 11th edition will be a two-day program, with an in-person audience of over 400 people and streaming access. Founded in 2010, the conference is a great place to meet worldwide Clojure developers and enthusiasts, and learn about what is happening in the language, the community, and in companies using Clojure.

WHAT TO EXPECT:

Two days of cutting-edge Clojure, ClojureScript and functional programming talks
Over 400 Clojure developers from around the world
Conference Swag and sponsor tables
Networking for information, sales and employment
All-day beverages and snacks
Livestreaming and edited conference video publishing

Zulip: https://clojurians.zulipchat.com/#narrow/stream/262224-events/near/316934527
....
