= Clojure Goes Brrr
2023-05-30
:jbake-type: event
:jbake-edition: 
:jbake-link: https://www.meetup.com/London-Clojurians/events/293273349/
:jbake-location: 
:jbake-start: 2023-05-30
:jbake-end: 2023-05-30

== Clojure Goes Brrr: a quest for performanc...

Clojure Goes Brrr:&nbsp;a quest for performance (by Oleksandr Yakushev) +
 +
**THIS IS AN ONLINE EVENT** +
[Connection details will be shared 1h before the start time] +
The London Clojurians are happy to present: +
Title: **Clojure Goes Brrr: a quest for performance** +
Speaker: **Oleksandr Yakushev** +
Time: **2023-05-30 @ 18:30 (London time)** +
Local time: https://time.is/1830_30_May_2023_in_London/ (click here for local time) +
Oleksandr Yakushev (https://twitter.com/unlog1c) will be presenting: +
&quot;Clojure Goes Brrr: a quest for performance&quot; +
Oleksandr will do a live demo of using the tools from +
Clojure Goes Fast umbrella to tackle a life-like programming task. He +
will show how these tools interoperate and complement each other, and +
how to integrate them into your regular development workflow. +
Oleksandr has been involved in the Clojure community since 2012. He +
has spent seven years at Grammarly using Clojure full-time for +
NLP-related performance-critical tasks. For the last year, Oleksandr +
has been serving in Armed Forces of Ukraine. +
If you missed this event, you can watch the recording on our YouTube channel: +
https://www.youtube.com/@LondonClojurians +
(The recording will be uploaded a couple of days after the event.) +
Please, consider supporting the London Clojurians with a small donation: +
https://opencollective.com/london-clojurians/ +
Your contributions will enable the sustainability of the London +
Clojurians community and support our varied set of online and +
in-person events: +
- ClojureBridge London: supports under-represented groups discover Clojure +
- re:Clojure: our **free** to attend annual community conference +
- monthly meetup events with speakers from all over the world +
- subscription and admin costs such as domain name &amp; Zoom plan for +
larger online meetups +
Thank you to our sponsors: +
- https://juxt.pro/ +
- https://flexiana.com/ +
- https://gaiwan.co/ +
- https://freshcodeit.com/ +
- https://nette.io/ +
- https://nilenso.com/ +
- And many individual sponsors +
 +
Zulip: https://clojurians.zulipchat.com/#narrow/stream/262224-events/near/358743327 +

