= Cooking up a workflow for data
2023-12-12
:jbake-type: event
:jbake-edition: 
:jbake-link: https://www.meetup.com/London-Clojurians/events/297576396/
:jbake-location: online
:jbake-start: 2023-12-12
:jbake-end: 2023-12-12

== Cooking up a workflow for data (by Slutsky, Pr...

Cooking up a workflow for data (by Slutsky, Prately &amp; McLean) +
 +
THIS IS AN ONLINE EVENT +
[Connection details will be shared 1h before the start time] +
The London Clojurians are happy to present: +
Title: Cooking up a workflow for data +
Speaker: Slutsky, Prately &amp; McLean +
Time: 2023-12-12 @ 18:30 (London time) +
Local time: click here for local time +
Slutsky, Prately &amp; McLean (https://github.com/daslu) will be presenting: +
&quot;Cooking up a workflow for data&quot; +
What does a typical data analysis workflow look like? .. and what is needed to make such workflows simple &amp; easy for any person with a data question? In the talk, we will demonstrate some of the relevant workflows, libraries, and tools through a real-world data problem. +
Daniel Slutsky (https://github.com/daslu) is a mathematician and a community organiser at Scicloj. He has been using Clojure in various data-science and backend teams at startups since 2013. These days he is focusing on building the Clay/Claykind tooling for literate programming in collaboration with Timothy and Kira. +
Timothy Prately (https://twitter.com/timothypratley): +
Timothy grew up exploring jungles, fighting kangaroos, surfing, and programming computers. After a career of leveraging computational graphs for companies he is now building Hummi.app, a diagramming app that puts the power of graphs in the hands of individuals. +
Kira McLean (https://github.com/kiramclean): +
Kira is an independent software engineer from the east coast of Canada. She&rsquo;s spent her career building web-facing services but has recently taken an interest in data science. After falling in love with Clojure she&rsquo;s keen to explore the best ways to use the language in these different domains. In her spare time you may catch Kira playing violin, teaching yoga, or hiking with her family. +
If you missed this event, you can watch the recording on our YouTube channel: +
https://www.youtube.com/@LondonClojurians +
(The recording will be uploaded a couple of days after the event.) +
Please, consider supporting the London Clojurians with a small donation: +
https://opencollective.com/london-clojurians/ +
Your contributions will enable the sustainability of the London Clojurians community and support our varied set of online and in-person events: +
 +
ClojureBridge London: supports under-represented groups discover Clojure +
re:Clojure: our free to attend annual community conference +
monthly meetup events with speakers from all over the world +
subscription and admin costs such as domain name &amp; StreamYard subscription +
 +
Thank you to our sponsors: +
 +
https://juxt.pro/ +
https://flexiana.com/ +
https://gaiwan.co/ +
And many individual sponsors +
 +
Zulip: https://clojurians.zulipchat.com/#narrow/stream/262224-events/near/404434718 +

