= Electric Clojure
2023-07-25
:jbake-type: event
:jbake-edition: 
:jbake-link: https://www.meetup.com/london-clojurians/events/294436947/
:jbake-location: online
:jbake-start: 2023-07-25
:jbake-end: 2023-07-25

== Electric Clojure &mdash; compiler managed data...

Electric Clojure &mdash; compiler managed datasync for rich web apps +
 +
THIS IS AN ONLINE EVENT +
[Connection details will be shared 1h before the start time] +
The London Clojurians are happy to present: +
Title: Electric Clojure &mdash; compiler managed datasync for rich web apps +
Speaker: Dustin Getz +
Time: 2023-07-25 @ 18:30 (London time) +
Local time: https://time.is/1830_25_July_2023_in_London/ (click here for local time) +
Dustin Getz (https://twitter.com/dustingetz) will be presenting: +
&quot;Electric Clojure &mdash; compiler managed datasync for rich web apps&quot; +
Electric Clojure is a reactive DSL for full-stack web development, with compiler-managed frontend/backend network sync. Electric's mission is to bring the next-generation of rich application interfaces within reach, by abstracting over client/server network plumbing in web applications by building it directly into the language/runtime, like how the JVM does with managed memory. +
Dustin will be presenting an overview of Electric, including everything you need to know to get started. He will also walk through the tutorial and explain all the tricky bits. Please watch the 10 minute lightning talk before this presentation and feel free to DM him questions ahead of time on slack @ Dustin Getz. +
This will be an interactive talk, please turn your cameras on and interrupt with questions! +
https://github.com/hyperfiddle/electric +
https://electric.hyperfiddle.net/ +
https://hyperfiddle.notion.site/UIs-are-streaming-DAGs-e181461681a8452bb9c7a9f10f507991 +
Dustin is the founder @ Hyperfiddle, where he has been working on this problem for a long time. +
If you missed this event, you can watch the recording on our YouTube channel: +
https://www.youtube.com/@LondonClojurians +
(The recording will be uploaded a couple of days after the event.) +
Please, consider supporting the London Clojurians with a small donation: +
https://opencollective.com/london-clojurians/ +
Your contributions will enable the sustainability of the London +
Clojurians community and support our varied set of online and +
in-person events: +
- ClojureBridge London: supports under-represented groups discover Clojure +
- re:Clojure: our free to attend annual community conference +
- monthly meetup events with speakers from all over the world +
- subscription and admin costs such as domain name &amp; Zoom plan for +
larger online meetups +
Thank you to our sponsors: +
- https://juxt.pro/ +
- https://flexiana.com/ +
- https://gaiwan.co/ +
- https://freshcodeit.com/ +
- https://nette.io/ +
- https://nilenso.com/ +
- And many individual sponsors +
 +
Zulip: https://clojurians.zulipchat.com/#narrow/stream/262224-events/near/374597466 +

