= HOP on and jump-start the development
2023-03-21
:jbake-type: event
:jbake-edition: 
:jbake-link: https://www.meetup.com/London-Clojurians/events/291838750/
:jbake-location: 
:jbake-start: 2023-03-21
:jbake-end: 2023-03-21

== HOP on and jump-start the development of your ...

HOP on and jump-start the development of your Clojure web apps (by Lucas Sousa) +
 +
**THIS IS AN ONLINE EVENT** +
[Connection details will be shared 1h before the start time] +
The London Clojurians are happy to present: +
Title: HOP on and jump-start the development and deployment of your Clojure web applications +
Speaker: Lucas Sousa +
Time: 2023-03-21 @ 18:30 (London time) +
Local time: https://time.is/1830_21_Mar_2023_in_London/ (click here for local time) +
Lucas Sousa (https://github.com/lucassousaf) will be presenting: +
&quot;HOP on and jump-start the development and deployment of your Clojure web applications&quot; +
In this talk you will see HOP&rsquo;s capabilities to build a production +
system to manage the entire stack (databases, code, deployment) in +
your local environments, and test and deploy into production +
environments effortlessly. +
Lucas works for a small cooperative company called Magnet based in +
Spain since 2018. He has been working as a full-stack Clojure(Script) +
developer for 5 years now, mostly building web applications for final +
clients. +
If you missed this event, you can watch the recording on our YouTube channel: +
https://www.youtube.com/c/LondonClojurians +
(The recording will be uploaded a couple of days after the event.) +
Please, consider supporting the London Clojurians with a small donation: +
https://opencollective.com/london-clojurians/ +
Your contributions will enable the sustainability of the London +
Clojurians community and support our varied set of online and +
in-person events: +
 +
ClojureBridge London: supports under-represented groups discover Clojure +
re:Clojure: our **free** to attend annual community conference +
- monthly meetup events with speakers from all over the world +
- subscription and admin costs such as domain name &amp; Zoom plan for +
larger online meetups +
 +
Thank you to our sponsors: +
- https://juxt.pro/ +
- https://flexiana.com/ +
- https://gaiwan.co/ +
- https://freshcodeit.com/ +
- https://nette.io/ +
- https://nilenso.com/ +
- And many individual sponsors +
 +
Zulip: https://clojurians.zulipchat.com/#narrow/stream/262224-events/near/336470778 +

