= Joyful Mobile Development with
2023-09-12
:jbake-type: event
:jbake-edition: 
:jbake-link: https://www.meetup.com/london-clojurians/events/295606069/
:jbake-location: online
:jbake-start: 2023-09-12
:jbake-end: 2023-09-12

== Joyful Mobile Development with ClojureDart (by...

Joyful Mobile Development with ClojureDart (by Baptiste &amp; Christophe) +
 +
THIS IS AN ONLINE EVENT +
[Connection details will be shared 1h before the start time] +
The London Clojurians are happy to present: +
Title: Joyful Mobile Development with ClojureDart +
Speaker: Baptiste Dupuch &amp; Christophe Grand +
Time: 12 Sept 2023 @ 18:30 (London time) +
Local time: https://time.is/1830_12_September_2023_in_London/ (click here for local time) +
Baptiste Dupuch &amp; Christophe Grand (@ClojureDart) will be presenting: +
&quot;Joyful Mobile Development with ClojureDart&quot; +
Java promised WORA: Write Once Run Anywhere. +
Clojure dialects deliver SORA: Skill Once Reach Anywhere. +
ClojureDart is a recent creatively-named dialect targeting Dart and its cross platform gui Flutter to bring native binaries to mobiles and desktops. +
We&rsquo;ll demo how the Clojure and Flutter combo makes app development enjoyable by leveraging strengths of our favorite language and of the Flutter ecosystem (portability, performance, libraries, tooling and community). +
Baptiste and Christophe have been contracting in Clojure together for 3 years and independently for 15 years. During the pandemic they started working on ClojureDart to make development of native GUI apps blissful. +
If you missed this event, you can watch the recording on our YouTube channel: https://www.youtube.com/@LondonClojurians +
(The recording will be uploaded a couple of days after the event.) +
Please, consider supporting the London Clojurians with a small donation: +
https://opencollective.com/london-clojurians/ +
Your contributions will enable the sustainability of the London +
Clojurians community and support our varied set of online and +
in-person events: +
 +
 +
ClojureBridge London: supports under-represented groups discover Clojure +
 +
 +
re:Clojure: our free to attend annual community conference +
 +
 +
- monthly meetup events with speakers from all over the world +
- subscription and admin costs such as domain name &amp; Zoom plan for +
larger online meetups +
Thank you to our sponsors: +
- https://juxt.pro/ +
- https://flexiana.com/ +
- https://gaiwan.co/ +
- https://freshcodeit.com/ +
- https://nette.io/ +
- https://nilenso.com/ +
- And many individual sponsors +
 +
Zulip: https://clojurians.zulipchat.com/#narrow/stream/262224-events/near/386801665 +

