= Lisp for Lattice Technology
2023-08-01
:jbake-type: event
:jbake-edition: 
:jbake-link: https://www.meetup.com/london-clojurians/events/294596750/
:jbake-location: online
:jbake-start: 2023-08-01
:jbake-end: 2023-08-01

== Lisp for Lattice Technology (by Mike Anderson)

THIS IS AN ONLINE EVENT +
[Connection details will be shared 1h before the start time] +
The London Clojurians are happy to present: +
Title: Lisp for Lattice Technology +
Speaker: Mike Anderson +
Time: 2023-08-01 @ 18:30 (London time) +
Local time: https://time.is/1830_01_Aug_2023_in_London/ (click here for local time) +
Mike Anderson ( https://www.linkedin.com/in/mike-cvx/ ) will be presenting: +
&quot;Lisp for Lattice Technology&quot; +
Convex (https://convex.world/) is a new decentralised network based on lattice technology - a promising alternative to blockchain based solutions. Best of all it runs a new dialect of Lisp, heaving influenced by Clojure and +
Racket. The session will include an introduction to both lattice technology and programming smart contracts with Convex Lisp. +
Mike leads the Convex Foundation, developing decentralised technology +
for programmable economic systems. A passionate open-source +
contributor, he has been enjoyed working with Clojure for over ten +
years, including developing the core.matrix numerical library. +
If you missed this event, you can watch the recording on our YouTube channel: +
https://www.youtube.com/@LondonClojurians +
(The recording will be uploaded a couple of days after the event.) +
Please, consider supporting the London Clojurians with a small donation: +
https://opencollective.com/london-clojurians/ +
Your contributions will enable the sustainability of the London +
Clojurians community and support our varied set of online and +
in-person events: +
- ClojureBridge London: supports under-represented groups discover Clojure +
- re:Clojure: our **free** to attend annual community conference +
- monthly meetup events with speakers from all over the world +
- subscription and admin costs such as domain name &amp; Zoom plan for +
larger online meetups +
Thank you to our sponsors: +
- https://juxt.pro/ +
- https://flexiana.com/ +
- https://gaiwan.co/ +
- https://freshcodeit.com/ +
- https://nette.io/ +
- https://nilenso.com/ +
- And many individual sponsors +
 +
Zulip: https://clojurians.zulipchat.com/#narrow/stream/262224-events/near/374597038 +

