= Lisp curse vs Lisp envy
2023-01-10
:jbake-type: event
:jbake-edition: 
:jbake-link: https://www.meetup.com/london-clojurians/events/289944517/
:jbake-location: 
:jbake-start: 2023-01-10
:jbake-end: 2023-01-10

== Lisp curse vs Lisp envy (by Mauricio Szabo)

....
**THIS IS AN ONLINE EVENT**
[Connection details will be shared 1h before the start time]
The London Clojurians are happy to present:
Title: Lisp curse vs Lisp envy
Speaker: Mauricio Szabo
Time: 2023-01-10 @ 18:30 (London time)
Local time: https://time.is/1830_10_Jan_2023_in_London/ (click here for local time)
Mauricio Szabo (https://github.com/mauricioszabo/) will be presenting:
&quot;Lisp curse vs Lisp envy&quot;
We sometimes say &quot;this doesn't exist in Clojure because of the Lisp
Curse&quot;, or blame it for some other lack of &quot;mature libraries&quot;. In this
talk, we will revisit the idea of what the &quot;curse&quot; is, and what
other &quot;curses&quot; we have on other communities, to conclude if what we
have is a &quot;bug&quot; or a &quot;feature&quot;.
Mauricio is a Clojure and ClojureScript developer, author of Chlorine,
Clover, Spock some other libraries; He calls himself a &quot;test-freak&quot;,
he like motorcycles and windsurf, and a lot of other random things
too.
If you missed this event, you can watch the recording on our YouTube channel: https://www.youtube.com/c/LondonClojurians
(The recording will be uploaded a couple of days after the event.)
Please, consider supporting the London Clojurians with a small donation:
https://opencollective.com/london-clojurians/
Your contributions will enable the sustainability of the London
Clojurians community and support our varied set of online and
in-person events:

ClojureBridge London: supports under-represented groups discover Clojure
re:Clojure: our free to attend annual community conference
- monthly meetup events with speakers from all over the world
- subscription and admin costs such as domain name &amp; Zoom plan for
larger online meetups

Thank you to our sponsors:
- https://www.juxt.pro/
- https://flexiana.com/
- https://gaiwan.co/
- And many individual sponsors

Zulip: https://clojurians.zulipchat.com/#narrow/stream/262224-events/near/312008988
....
