= Matrix Exposed!
2023-10-03
:jbake-type: event
:jbake-edition: 
:jbake-link: https://www.meetup.com/London-Clojurians/events/296103679/
:jbake-location: online
:jbake-start: 2023-10-03
:jbake-end: 2023-10-03

== Matrix Exposed! (or, You Don't Know Reactive) ...

Matrix Exposed! (or, You Don't Know Reactive) (by Kenny Tilton) +
 +
THIS IS AN ONLINE EVENT +
[Connection details will be shared 1h before the start time] +
The London Clojurians are happy to present: +
Title: Matrix Exposed! (or, You Don't Know Reactive) +
Speaker: Kenny Tilton +
Time: 2023-10-03 @ 18:30 (London time) +
Local time: click here for local time +
Kenny Tilton (https://github.com/kennytilton) will be presenting: +
&quot;Matrix Exposed! (or, You Don't Know Reactive)&quot; +
No one takes state management seriously. ReactJS punted. Flutter punted. Kenny Tilton will lead a deep dive into his Matrix state manager; make the case for state being the first problem solved by any UI framework; and explain how to evaluate state engines when our chosen UI punts. +
Kenny is currently developing a new Flutter/Matrix reactive front-end library atop ClojureDart. He came to Clojure from Common Lisp ten years ago, and has used it professionally for ETL and e-commerce, as well his own O/S UI frameworks. He has used re-frame professionally, Reagent in anger, and Hoplon/Javelin, one of his favorites, for fun. Before shuffling off this mortal coil, he wants us to know the power we are missing with even today's excellent reactive solutions. +
If you missed this event, you can watch the recording on our YouTube channel: +
https://www.youtube.com/@LondonClojurians +
(The recording will be uploaded a couple of days after the event.) +
Please, consider supporting the London Clojurians with a small donation: +
https://opencollective.com/london-clojurians/ +
Your contributions will enable the sustainability of the London Clojurians community and support our varied set of online and in-person events: +
 +
ClojureBridge London: supports under-represented groups discover Clojure +
re:Clojure: our free to attend annual community conference +
monthly meetup events with speakers from all over the world +
subscription and admin costs such as domain name &amp; Zoom plan for larger online meetups +
 +
Thank you to our sponsors: +
 +
https://juxt.pro/ +
https://flexiana.com/ +
https://gaiwan.co/ +
And many individual sponsors +
 +
Zulip: https://clojurians.zulipchat.com/#narrow/stream/262224-events/near/391695079 +

