= Model-driven systems with zen-lang
2023-02-21
:jbake-type: event
:jbake-edition: 
:jbake-link: https://www.meetup.com/london-clojurians/events/290555251/
:jbake-location: online
:jbake-start: 2023-02-21
:jbake-end: 2023-02-21

== Model-driven systems with zen-lang (by Nikolai...

Model-driven systems with zen-lang (by Nikolai Ryzhikov) +
 +
THIS IS AN ONLINE EVENT +
[Connection details will be shared 1h before the start time] +
The London Clojurians are happy to present: +
Title: Model-driven systems with zen-lang +
Speaker: Nikolai Ryzhikov +
Time: 2023-02-21 @ 18:30 (London time) +
Local time: https://time.is/1830_21_Feb_2023_in_London/ (click here for local time) +
Nikolai Ryzhikov (https://twitter.com/niquola) will be presenting: +
&quot;Model-driven systems with zen-lang&quot; +
We all use a lot of fantastic data-based DSLs in Clojure. What if we +
describe the whole system as a composable meta-data with zen-lang +
(https://github.com/zen-lang/zen) +
CTO &amp; Engineer in Health Samurai. Crafting FHIR platform for future +
healthcare in Clojure &amp; PostgreSQL for the last decade. +
If you missed this event, you can watch the recording on our YouTube channel: +
https://www.youtube.com/c/LondonClojurians +
(The recording will be uploaded a couple of days after the event.) +
Please, consider supporting the London Clojurians with a small donation: +
https://opencollective.com/london-clojurians/ +
Your contributions will enable the sustainability of the London +
Clojurians community and support our varied set of online and +
in-person events: +
 +
ClojureBridge London: supports under-represented groups discover Clojure +
reClojure: our free to attend annual community conference +
- monthly meetup events with speakers from all over the world +
- subscription and admin costs such as domain name &amp; Zoom plan for +
larger online meetups +
 +
Thank you to our sponsors: +
- https://juxt.pro/ +
- https://flexiana.com/ +
- https://gaiwan.co/ +
- https://freshcodeit.com/ +
- https://nette.io/ +
- https://nilenso.com/ +
- And many individual sponsors +
 +
Zulip: https://clojurians.zulipchat.com/#narrow/stream/262224-events/near/328969911 +

