= Open Source Licenses for Developers
2023-01-24
:jbake-type: event
:jbake-edition: 
:jbake-link: https://www.meetup.com/london-clojurians/events/289965685/
:jbake-location: 
:jbake-start: 2023-01-24
:jbake-end: 2023-01-24

== Open Source Licenses for Developers (by Martin...

Open Source Licenses for Developers (by Martin Clausen) +
 +
**THIS IS AN ONLINE EVENT** +
[Connection details will be shared 1h before the start time] +
The London Clojurians are happy to present: +
Title: Open Source Licenses for Developers +
Speaker: Martin Clausen +
Time: 2023-01-24 @ 18:30 (London time) +
Local time: https://time.is/1830_24_Jan_2023_in_London/ (click here for local time) +
Martin Clausen (https://github.com/maacl) will be presenting: +
&quot;Open Source Licenses for Developers&quot; +
What are the different types of Open Source license, and how do I pick +
one for my project. The are questions that may dev struggle with. I +
will try to address these, provide an overview of the Open Source +
license landscape, and dive into the EPL v1 which dominates the +
Clojure community. +
Martin is a recovering General Counsel who now spends his time +
developing a practical Computable Contract platform using Clojure. In +
the past Martin has work for world leading companies within ocean +
transportation and renewables. Martin can teach you how to make a +
proper Sauce B&eacute;arnaise. +
If you missed this event, you can watch the recording on our YouTube channel: https://www.youtube.com/c/LondonClojurians +
(The recording will be uploaded a couple of days after the event.) +
Please, consider supporting the London Clojurians with a small donation: +
https://opencollective.com/london-clojurians/ +
Your contributions will enable the sustainability of the London +
Clojurians community and support our varied set of online and +
in-person events: +
 +
ClojureBridge London: supports under-represented groups discover Clojure +
re:Clojure: our free to attend annual community conference +
monthly meetup events with speakers from all over the world +
subscription and admin costs such as domain name &amp; Zoom plan for +
larger online meetups +
 +
Thank you to our sponsors: +
- https://www.juxt.pro/ +
- https://flexiana.com/ +
- https://gaiwan.co/ +
- And many individual sponsors +
 +
Zulip: https://clojurians.zulipchat.com/#narrow/stream/262224-events/near/316927484 +

