= Portfolio: A &quot;visual REPL&quot;
2023-04-18
:jbake-type: event
:jbake-edition: 
:jbake-link: https://www.meetup.com/London-Clojurians/events/292784243/
:jbake-location: 
:jbake-start: 2023-04-18
:jbake-end: 2023-04-18

== Portfolio: A &quot;visual REPL&quot; for UI Co...

Portfolio: A &quot;visual REPL&quot; for UI Component development +
 +
**THIS IS AN ONLINE EVENT** +
[Connection details will be shared 1h before the start time] +
The London Clojurians are happy to present: +
Title: **Portfolio: A &quot;visual REPL&quot; for UI Component development** +
Speaker: **Christian Johansen** +
Time: **2023-04-18 @ 18:30 (London time)** +
Local time: https://time.is/1830_18_April_2023_in_London/ (click here for local time) +
Christian Johansen (https://github.com/cjohansen) will be presenting: +
&quot;Portfolio: A &quot;visual REPL&quot; for UI Component development&quot; +
Christian will present Portfolio, a library inspired by devcards +
and Storybook.JS for working with UI components. He will show you +
what the tool can do and how to use it. He'll also show examples +
from his own work, including custom extensions for i18n, theming and more. +
Christian works for the Norwegian consultancy Kodemaker. +
He's worked backends and frontends for web and mobile apps +
since the early 2000s and picked up Clojure in 2013.He's been +
fortunate enough to do Clojure and ClojureScript full-time since 2017. +
If you missed this event, you can watch the recording on our YouTube channel: +
https://www.youtube.com/@LondonClojurians +
(The recording will be uploaded a couple of days after the event.) +
Please, consider supporting the London Clojurians with a small donation: +
https://opencollective.com/london-clojurians/ +
Your contributions will enable the sustainability of the London +
Clojurians community and support our varied set of online and +
in-person events: +
- ClojureBridge London: supports under-represented groups discover Clojure +
- re:Clojure: our **free** to attend annual community conference +
- monthly meetup events with speakers from all over the world +
- subscription and admin costs such as domain name &amp; Zoom plan for +
larger online meetups +
Thank you to our sponsors: +
- https://juxt.pro/ +
- https://flexiana.com/ +
- https://gaiwan.co/ +
- https://freshcodeit.com/ +
- https://nette.io/ +
- https://nilenso.com/ +
- And many individual sponsors +
 +
Zulip: https://clojurians.zulipchat.com/#narrow/stream/262224-events/near/348200876 +

