= Portal Internals (by Chris Badahdah)
2023-10-24
:jbake-type: event
:jbake-edition: 
:jbake-link: https://www.meetup.com/london-clojurians/events/295880430/
:jbake-location: online
:jbake-start: 2023-10-24
:jbake-end: 2023-10-24

== Portal Internals (by Chris Badahdah)

THIS IS AN ONLINE EVENT +
[Connection details will be shared 1h before the start time] +
The London Clojurians are happy to present: +
Title: Portal Internals +
Speaker: Chris Badahdah +
Time: 2023-10-24 @ 18:30 (London time) +
Local time: click here for local time +
Chris Badahdah (https://djblue.github.io/) will be presenting: +
&quot;Portal Internals&quot; +
Portal is a Clojure data visualization and exploration tool aimed at enhancing interactive development. In this talk we will explore aspects of Portal's internals and how they enable various types of workflows for different users. After this talk, you should be better equipped to leverage Portal in your specific workflow. +
Chris started learning Clojure in 2016 after he realized lisp was the ultimate programming language. In early 2020, he started working in Clojure professionally and hasn&rsquo;t looked back. He&rsquo;s been working with data driven systems, during which Portal has been of great use! +
If you missed this event, you can watch the recording on our YouTube channel: +
https://www.youtube.com/@LondonClojurians +
(The recording will be uploaded a couple of days after the event.) +
Please, consider supporting the London Clojurians with a small donation: +
https://opencollective.com/london-clojurians/ +
Your contributions will enable the sustainability of the London Clojurians community and support our varied set of online and in-person events: +
 +
 +
ClojureBridge London: supports under-represented groups discover Clojure +
 +
 +
re:Clojure: our free to attend annual community conference +
 +
 +
monthly meetup events with speakers from all over the world +
 +
 +
subscription and admin costs such as domain name &amp; Zoom plan for larger online meetups +
 +
 +
Thank you to our sponsors: +
 +
 +
https://juxt.pro/ +
 +
 +
https://flexiana.com/ +
 +
 +
https://gaiwan.co/ +
 +
 +
And many individual sponsors +
 +
Zulip: https://clojurians.zulipchat.com/#narrow/stream/262224-events/near/391693746 +

