= Scicloj LLM meetup 1: Introduction
2023-05-26
:jbake-type: event
:jbake-edition: 
:jbake-link: https://clojureverse.org/t/scicloj-llm-meetup-1-introduction-login-for-details/10025
:jbake-location: 
:jbake-start: 2023-05-26
:jbake-end: 2023-05-26

== Scicloj LLM meetup 1: Introduction (login for ...

Scicloj LLM meetup 1: Introduction (login for details) +
 +
This coming Friday, we will have the first meetup in a new series exploring Large Language Models in Clojure. +
 +
Agenda +
In this meetup, Martynas M. will give an interview on the topic, introducing a few of the basic ideas behind LLMs and demonstrating some of the practices of prompt engineering. +
 +
Joining +
Please use the Going button at the top of this post to mark your participation. +
You can also use the Add to Calendar to add the event to your calendar. +
 +
Length +
The official part will be 90 minutes long. +
Sometimes some of us like to stay longer and chat. +
 +
Video Call +
Updated Zoom link: Launch Meeting - Zoom +
 +
Recording +
The meeting will be recorded and shared publicly. +
Some parts will be unrecorded. +
 +
Future meetings +
 +
At a following meetup that will be announced soon, Žygimantas Medelis will present Bosquet &ndash; a Clojure LLMOps platform for Large Language Model based applications. +
We are also planning a talk by Dimid Duchovny that will explore a little more of the architecture and ideas behind transformer-based models. +
 +
 +
Zulip: https://clojurians.zulipchat.com/#narrow/stream/262224-events/near/360360880 +

