= Scicloj LLM meetup 5
2023-09-24
:jbake-type: event
:jbake-edition: 
:jbake-link: https://clojureverse.org/t/scicloj-llm-meetup-5-library-overviews-and-selected-discussions/10313
:jbake-location: online
:jbake-start: 2023-09-24
:jbake-end: 2023-09-24

== Scicloj LLM meetup 5: Library overviews and se...

Scicloj LLM meetup 5: Library overviews and selected discussions +
 +
The Clojure ecosystem around LLMs has been growing, with a few new libraries and other projects. Quite a lot of that activity is discussed at the #clojurellm channel on the Clojurians Slack. You can also see most of the relevant libraries listed on the Scicloj website. +
While LLMs are not the current main focus of the Scicloj group, it has been organizing a meetups series to assist some of those explorations. It was done in collaboration with the wise friends at the #clojurellm channel, who&rsquo;ve kindly agreed to give talks and contribute to the discussions. +
This event aims to explore a few of the current development directions in this field. +
 +
Joining +
Please Reply below and mention that you plan to attend. You can also inform me by a private message. +
You can use the Add to Calendar button to add the event to your calendar. +
 +
Contributing to the agenda +
Please let us know if you wish to present a project or propose a discussion topic. +
You can propose it either in a comment replying to this post or by mentioning @daslu on the #clojurellm Slack channel. Private messages are also welcome. +
Further planning of the session will take place on Slack. +
 +
Agenda (gradually updating) +
 +
short project overviews by some of the library makers +
selected discussions of topics proposed in advance +
additional discussion +
 +
 +
Assumed background +
This session will not teach the basics of LLMs. We may assume some familiarity with the common notions, mainly regarding using LLMs and composing them with other software components. +
You are encouraged to watch the recordings of previous meetups for some background. +
Some familiarity with Clojure will be assumed, and maybe also some Python. +
 +
Length +
The official part will be 90 minutes long. +
Sometimes, some of us like to stay longer and chat. +
 +
Video Call +
Zoom link: Launch Meeting - Zoom +
 +
Recording +
Some parts of this meeting will be recorded and shared publicly. +
Some parts will not be recorded, to allow the conversation to flow freely. +
 +
Zulip: https://clojurians.zulipchat.com/#narrow/stream/262224-events/near/390540499 +

