= Scicloj LLM meetup 3: Bosquet
2023-06-17
:jbake-type: event
:jbake-edition: 
:jbake-link: https://clojureverse.org/t/scicloj-llm-meetup-3-bosquet-login-for-details/10058
:jbake-location: online
:jbake-start: 2023-06-17
:jbake-end: 2023-06-17

== Scicloj LLM meetup 3: Bosquet (login for details)

This 3rd meetup in the LLM meetup series will focus on the Bosquet LLMOps tool. +
 +
Agenda +
Žygimantas Medelis will present Bosquet, dive in a bit into its internals (e.g., the use of Slemer and Pathom), and discuss future directions. +
 +
Assumed background +
Some familiarity with LLMs will be assumed (e.g., the content of the previous meetings in this series). +
 +
Joining +
Please use the Going button at the top of this post to mark your participation. +
You can also use the Add to Calendar to add the event to your calendar. +
 +
Time +
Saturday June 17th 2pm UTC +
 +
Length +
The official part will be 90 minutes long. +
Sometimes, some of us like to stay longer and chat. +
 +
Video Call +
Zoom link: Launch Meeting - Zoom +
 +
Recording +
The meeting will be recorded and shared publicly. +
Some parts will be unrecorded. +
 +
Zulip: https://clojurians.zulipchat.com/#narrow/stream/262224-events/near/361277921 +

