= Scicloj LLM meetup 2
2023-06-16
:jbake-type: event
:jbake-edition: 
:jbake-link: https://clojureverse.org/t/scicloj-llm-meetup-2-prompt-engineering-login-for-details/10057
:jbake-location: 
:jbake-start: 2023-06-16
:jbake-end: 2023-06-16

== Scicloj LLM meetup 2: Prompt engineering (logi...

Scicloj LLM meetup 2: Prompt engineering (login for details) +
 +
This 2nd meetup in the LLM meetup series will focus on prompt engineering. +
One of the main goals here will be to clarify some notions and practices before the 3rd meetup (that will focus on Bosquet). +
 +
Agenda +
@irfanns and @daslu will explain and demonstrate some practices from Clojure. +
 +
Joining +
Please use the Going button at the top of this post to mark your participation. +
You can also use the Add to Calendar to add the event to your calendar. +
 +
Time +
Friday June 16th 2pm UTC +
 +
Length +
The official part will be 90 minutes long. +
Sometimes, some of us like to stay longer and chat. +
 +
Video Call +
Zoom link: Launch Meeting - Zoom +
 +
Recording +
The meeting will be recorded and shared publicly. +
Some parts will be unrecorded. +
 +
Zulip: https://clojurians.zulipchat.com/#narrow/stream/262224-events/near/361277826 +

