= Scicloj LLM meetup 6
2023-11-17
:jbake-type: event
:jbake-edition: 
:jbake-link: https://clojureverse.org/t/scicloj-llm-meetup-6-implementing-research-papers-with-bosquet/10404
:jbake-location: online
:jbake-start: 2023-11-17
:jbake-end: 2023-11-17

== Scicloj LLM meetup 6: Implementing research pa...

Scicloj LLM meetup 6: Implementing research papers with Bosquet +
 +
On the next meetup of the Scicloj LLM series, we will keep exploring the LLMOps platform Bosquet. +
In this meeting, the author Žygimantas Medelis will demonstrate how Bosquet can be used to implement a couple of workflows presented in recent research. You may see examples of such implementations in Bosquet&rsquo;s documentation. +
 +
Joining +
Please Reply below and mention that you plan to attend. You can also inform me by a private message. +
You can use the Add to Calendar button to add the event to your calendar. +
 +
Assumed background +
This session will not teach the basics of LLMs. For background, you are encouraged to watch the recordings of previous sessions on this series, especially Meetups 1,2, and the short part about Bosquet in Meetup 5. You may also enjoy Meetup 3, where an earlier version of Bosquet was presented. +
We will also assume some knowledge of Clojure. +
 +
Length +
The official part will be 90 minutes long. +
Sometimes, some of us like to stay longer and chat. +
 +
Video Call +
Zoom link: Launch Meeting - Zoom +
 +
Recording +
Some parts of this meeting will be recorded and shared publicly. +
Some parts will not be recorded, to allow the conversation to flow freely. +
 +
Zulip: https://clojurians.zulipchat.com/#narrow/stream/262224-events/near/400427049 +

