= Second Func Prog Sweden 2023 - Online
2023-03-21
:jbake-type: event
:jbake-edition: 
:jbake-link: https://www.meetup.com/func-prog-sweden/events/291001737/
:jbake-location: online
:jbake-start: 2023-03-21
:jbake-end: 2023-03-21

== Second Func Prog Sweden 2023 - Online

Second Func Prog Sweden 2023 &ndash; Online +
 +
Welcome to the second Func Prog Sweden MeetUp 2022 &ndash; Online +
This MeetUp will be streamed live online on the Func Prog Sweden YouTube channel: https://www.youtube.com/c/FuncProgSweden +
The program starts at 18. +
 +
Intro by Magnus Sedlacek +
Gotta catch 'em all: Let's do it with Tablecloth! by Mey Beisaron +
TBA +
 +
Gotta catch 'em all: Let's do it with Tablecloth! +
Have you ever wondered which Pok&eacute;mon shares your height and weight features? I'm guessing never. +
In this talk I&rsquo;m going to show you how you can find the Pokemon that shares your features and see if you could win all Pokemon battles if you were this Pokemon. +
Although I&rsquo;m sure that finding your matching Pokemon is an interesting thing to learn, what we will truly focus on is the magical Clojure library that I used to get this magic happen - Tablecloth! +
Tablecloth is a Clojure library that we can use for performing queries on columnar datasets. +
We will go through the main features this library offers, see code examples of using Tablecloth and compare these code examples with the same queries done in other ways in Clojure. +
We will think together - which way is preferred for use in different use cases. +
Join me on the journey of learning about Tablecloth and finding your matching Pokemon. +
Even if you&rsquo;ve never thought about your matching Pokemon, aren't you just a little bit curious? +
Mey Beisaron +
Mey is a Software Engineer, a Public speaker and a Mentor. +
When she is not spending her weekends coding games or speaking at tech conferences, she experiments with algorithms or playing Super Mario Bros on the Nintendo Switch. +
As she recently joined the Infrastructure forces at Forter, Clojure is not her main development language anymore, but it will forever be her favorite one. +
Mey is a sworn Star Wars fan. May the force be with you. +
Twitter: https://twitter.com/ladymeyy +
LinkedIn: https://www.linkedin.com/in/ladymey/ +
Video sponsor &ndash; Ada Beat +
https://adabeat.com +
Merch +
If you want to spread functional programming and support the channel, buy something from the shop: +
https://funcprogsweden.myspreadshop.net/ +
#funcprogsweden +
 +
Zulip: https://clojurians.zulipchat.com/#narrow/stream/262224-events/near/340324544 +

