= Simpler User Interfaces with Membrane
2023-02-07
:jbake-type: event
:jbake-edition: 
:jbake-link: https://www.meetup.com/London-Clojurians/events/290017912/
:jbake-location: 
:jbake-start: 2023-02-07
:jbake-end: 2023-02-07

== Simpler User Interfaces with Membrane (by Adri...

Simpler User Interfaces with Membrane (by Adrian Smith)

THIS IS AN ONLINE EVENT
[Connection details will be shared 1h before the start time]
The London Clojurians are happy to present:
Title: Simpler User Interfaces with Membrane
Speaker: Adrian Smith
Time: 2023-02-07 @ 18:30 (London time)
Local time: https://time.is/1830_07_Feb_2023_in_London/ (click here for local time)
Adrian Smith (https://github.com/phronmophobic) will be presenting:
&quot;Simpler User Interfaces with Membrane&quot;
User Interfaces are brittle, highly coupled, and inflexible. This talk
will diagnose some of the root problems that plague user interfaces
and show how a different approach can make UI programs dramatically
simpler using Membrane (https://github.com/phronmophobic/membrane).
Adrian is a software engineer and creator of membrane, a UI library
that runs anywhere. He got started programming by making tic-tac-toe
for his TI-83 calculator. Since then, he's built web, mobile, and
desktop apps using python, javascript, ruby, php, objective-c, and c++
before finally finding clojure. He believes that programming should be
for everyone and that you shouldn't need a CS degree to make a simple
web, desktop, or mobile app. The right tools for making programming
accessible don't exist... yet, but he's working to change that.
If you missed this event, you can watch the recording on our YouTube channel:
https://www.youtube.com/c/LondonClojurians
(The recording will be uploaded a couple of days after the event.)
Please, consider supporting the London Clojurians with a small donation:
https://opencollective.com/london-clojurians/
Your contributions will enable the sustainability of the London
Clojurians community and support our varied set of online and
in-person events:

ClojureBridge London: supports under-represented groups discover Clojure
reClojure: our free-to- attend annual community conference
- monthly meetup events with speakers from all over the world
- subscription and admin costs such as domain name &amp; Zoom plan for
larger online meetups

Thank you to our sponsors:
- https://www.juxt.pro/
- https://flexiana.com/
- https://gaiwan.co/
- And many individual sponsors

Zulip: https://clojurians.zulipchat.com/#narrow/stream/262224-events/near/316927721
