= Software Development Leverage
2023-05-02
:jbake-type: event
:jbake-edition: 
:jbake-link: https://www.meetup.com/london-clojurians/events/291838848/
:jbake-location: 
:jbake-start: 2023-05-02
:jbake-end: 2023-05-02

== Software Development Leverage (by Tony Kay)

**THIS IS AN ONLINE EVENT** +
[Connection details will be shared 1h before the start time] +
The London Clojurians are happy to present: +
Title: **Software Development Leverage** +
Speaker: **Tony Kay** +
Time: **2023-05-02 @ 18:30 (London time)** +
Local time: https://time.is/1830_02_May_2023_in_London/ (click here for local time) +
Tony Kay (github.com/awkay) will be presenting: +
&quot;Software Development Leverage&quot; +
This talk is about Tony's experiments and experiences around the issue +
of efficient and sustainable software development that have led to +
open source libraries such as Fulcro, Fulcro RAD, Guardrails, and +
more. It briefly explores what led to his choice of Clojure and the +
design decisions in his open-source work, and how those things have +
evolved through success and failure. +
Tony has been a professional software developer for more than 3 +
decades, with interests that have ranged from operating system +
internals to language processing, and he has mainly worked with (or +
co-owned) companies in the early phases of development. In the past +
decade he has had an increased interest in how software development +
succeeds or fails as a human endeavor. He spends a lot of his spare +
time hiking in forested and alpine areas of the Pacific Northwest in +
the United States, and has interests in perennial food systems, soil +
science, and regenerative agriculture. +
If you missed this event, you can watch the recording on our YouTube channel: +
https://www.youtube.com/c/LondonClojurians +
(The recording will be uploaded a couple of days after the event.) +
Please, consider supporting the London Clojurians with a small donation: +
https://opencollective.com/london-clojurians/ +
Your contributions will enable the sustainability of the London +
Clojurians community and support our varied set of online and +
in-person events: +
 +
ClojureBridge London: supports under-represented groups discover Clojure +
re:Clojure: our **free** to attend annual community conference +
- monthly meetup events with speakers from all over the world +
- subscription and admin costs such as domain name &amp; Zoom plan for +
larger online meetups +
 +
Thank you to our sponsors: +
- https://juxt.pro/ +
- https://flexiana.com/ +
- https://gaiwan.co/ +
- https://freshcodeit.com/ +
- https://nette.io/ +
- https://nilenso.com/ +
- And many individual sponsors +
 +
Zulip: https://clojurians.zulipchat.com/#narrow/stream/262224-events/near/336471134 +

