= Talking to Martians (by Oliver Hine)
2023-08-29
:jbake-type: event
:jbake-edition: 
:jbake-link: https://www.meetup.com/london-clojurians/events/294724965/
:jbake-location: online
:jbake-start: 2023-08-29
:jbake-end: 2023-08-29

== Talking to Martians (by Oliver Hine)

THIS IS AN ONLINE EVENT +
[Connection details will be shared 1h before the start time] +
The London Clojurians are happy to present: +
Title: Talking to Martians +
Speaker: Oliver Hine +
Time: 2023-08-29 @ 18:30 (London time) +
Local time: https://time.is/1830_29_August_2023_in_London/ (click here for local time) +
Oliver Hine (https://github.com/oliyh) will be presenting: +
&quot;Talking to Martians&quot; +
How describing remote interfaces using schemas allows abstraction from HTTP and leads to greater good. +
Oliver enjoys writing software and wants others to enjoy it too. A decade of Clojure dev across the stack. +
If you missed this event, you can watch the recording on our YouTube channel: +
https://www.youtube.com/@LondonClojurians +
(The recording will be uploaded a couple of days after the event.) +
Please, consider supporting the London Clojurians with a small donation: +
https://opencollective.com/london-clojurians/ +
Your contributions will enable the sustainability of the London +
Clojurians community and support our varied set of online and +
in-person events: +
- ClojureBridge London: supports under-represented groups discover Clojure +
- re:Clojure: our free to attend annual community conference +
- monthly meetup events with speakers from all over the world +
- subscription and admin costs such as domain name &amp; Zoom plan for +
larger online meetups +
Thank you to our sponsors: +
- https://juxt.pro/ +
- https://flexiana.com/ +
- https://gaiwan.co/ +
- https://freshcodeit.com/ +
- https://nette.io/ +
- https://nilenso.com/ +
- And many individual sponsors +
 +
Zulip: https://clojurians.zulipchat.com/#narrow/stream/262224-events/near/374596975 +

