= The jank programming language
2023-06-13
:jbake-type: event
:jbake-edition: 
:jbake-link: https://www.meetup.com/london-clojurians/events/293062043/
:jbake-location: 
:jbake-start: 2023-06-13
:jbake-end: 2023-06-13

== The jank programming language (by Jeaye Wilker...

The jank programming language (by Jeaye Wilkerson) +
 +
**THIS IS AN ONLINE EVENT** +
[Connection details will be shared 1h before the start time] +
The London Clojurians are happy to present: +
Title: **The jank programming language** +
Speaker: **Jeaye Wilkerson** +
Time: **2023-06-13 @ 18:30 (London time)** +
Local time: https://time.is/1830_13_June_2023_in_London/ (click here for local time) +
Jeaye Wilkerson (https://github.com/jeaye) will be presenting: +
&quot;The jank programming language&quot; +
jank (https://jank-lang.org/) is a Clojure dialect on LLVM with C++ interop. In this talk, Jeaye will cover jank's use cases, some challenges around building a native Clojure dialect, and some insights about Clojure itself found only by spelunking deep into the Clojure compiler. +
Jeaye has a background in C++ systems programming, focusing on games +
and game engines. After several years of that, he co-founded an +
e-sports tournament startup written in full-stack Clojure for another +
5 years. These days, he&rsquo;s at Electronic Arts (EA) building tooling +
used to make some of the world&rsquo;s top games. +
If you missed this event, you can watch the recording on our YouTube channel: +
https://www.youtube.com/@LondonClojurians +
(The recording will be uploaded a couple of days after the event.) +
Please, consider supporting the London Clojurians with a small donation: +
https://opencollective.com/london-clojurians/ +
Your contributions will enable the sustainability of the London +
Clojurians community and support our varied set of online and +
in-person events: +
- ClojureBridge London: supports under-represented groups discover Clojure +
- re:Clojure: our **free** to attend annual community conference +
- monthly meetup events with speakers from all over the world +
- subscription and admin costs such as domain name &amp; Zoom plan for +
larger online meetups +
Thank you to our sponsors: +
- https://juxt.pro/ +
- https://flexiana.com/ +
- https://gaiwan.co/ +
- https://freshcodeit.com/ +
- https://nette.io/ +
- https://nilenso.com/ +
- And many individual sponsors +
 +
Zulip: https://clojurians.zulipchat.com/#narrow/stream/262224-events/near/358743768 +

