= TMD 7.0 - Higher Performance Functional
2023-10-10
:jbake-type: event
:jbake-edition: 
:jbake-link: https://www.meetup.com/london-clojurians/events/295843187/
:jbake-location: online
:jbake-start: 2023-10-10
:jbake-end: 2023-10-10

== TMD 7.0 - Higher Performance Functional Data S...

TMD 7.0 - Higher Performance Functional Data Science (by Chris Nuernberger) +
 +
THIS IS AN ONLINE EVENT +
[Connection details will be shared 1h before the start time] +
The London Clojurians are happy to present: +
Title: TMD 7.0 - Higher Performance Functional Data Science +
Speaker: Chris Nuernberger +
Time: 2023-10-10 @ 18:30 (London time) +
Local time: click here for local time +
Chris Nuernberger (https://github.com/cnuernber) will be presenting: +
&quot;TMD 7.0 - Higher Performance Functional Data Science&quot; +
This talk is about the research and work done to move TMD, our data processing system, from version 6.0 to 7.0. It will then cover the upcoming technologies we are most interested and the vision for the future of functional data science in Clojure. +
Chris has been programming in Clojure since 2009 and worked in Clojure since 2015. He is the primary author of the Clojure data analysis library tech.ml.dataset and libpython-clj. He is most interested in high performance computing and functional data analytics. +
If you missed this event, you can watch the recording on our YouTube channel: +
https://www.youtube.com/@LondonClojurians +
(The recording will be uploaded a couple of days after the event.) +
Please, consider supporting the London Clojurians with a small donation: +
https://opencollective.com/london-clojurians/ +
Your contributions will enable the sustainability of the London Clojurians community and support our varied set of online and in-person events: +
 +
ClojureBridge London: supports under-represented groups discover Clojure +
re:Clojure: our free to attend annual community conference +
monthly meetup events with speakers from all over the world +
subscription and admin costs such as domain name &amp; Zoom plan for larger online meetups +
 +
Thank you to our sponsors: +
 +
https://juxt.pro/ +
https://flexiana.com/ +
https://gaiwan.co/ +
And many individual sponsors +
 +
Zulip: https://clojurians.zulipchat.com/#narrow/stream/262224-events/near/391693689 +

