= Visual-tools meeting 17
2023-04-01
:jbake-type: event
:jbake-edition: 
:jbake-link: https://clojureverse.org/t/visual-tools-meeting-17-coming-back-various-updates/9879
:jbake-location: 
:jbake-start: 2023-04-01
:jbake-end: 2023-04-01

== Visual-tools meeting 17 - coming back, various...

Visual-tools meeting 17 - coming back, various updates +
 +
Please note that some clocks are shifting these days, and the Clojureverse view might be misleading. +
The time is 18:00 in UTC time zone. You can click Add to Calendar to add the event to your calendar. +
After a break of a few months, the visual tools group will have its 17h meeting on April 1st. +
In this meeting, a few of our friends will share updates of their current projects. Please see the gradually updating agenda below, and please reach out to add your topics to the Agenda. +
A few of the topics will be updates of ongoing projects, but we will encourage participants to make their presentations self-contained. +
 +
Agenda +
 +
 +
@daslu: +
 +
 +
Kindly updates: support for Clerk &amp; Quarto, exploring Portal +
 +
Clay updates: bridging between interactive backend computation to static documents +
 +
 +
&hellip; you? +
 +
 +
Joining +
Please use the Going button at the top of this post to mark your participation. +
You can also use the Add to Calendar to add the event to your calendar. +
 +
Length +
The official part will be 90 minutes long. +
Sometimes some of us like to stay longer and chat. +
 +
Video Call +
Zoom link: Launch Meeting - Zoom +
 +
Recording +
The meeting will be recorded and shared publicly. +
Some parts will be unrecorded. +
 +
Zulip: https://clojurians.zulipchat.com/#narrow/stream/262224-events/near/342664721 +

