= Visual-tools meeting 20
2023-12-01
:jbake-type: event
:jbake-edition: 
:jbake-link: https://clojureverse.org/t/visual-tools-meeting-20-various-updates/10454
:jbake-location: online
:jbake-start: 2023-12-01
:jbake-end: 2023-12-01

== Visual-tools meeting 20 - various updates

The visual tools group will have its 20th meeting on Dec 1st. +
In this meeting, a few of our friends will share updates on their current projects in the fields of tooling, literate programming, data visualization, and UI design. Please see the gradually updating agenda below, and please reach out to add your topics to the Agenda. +
 +
Agenda +
(gradually updating) +
 +
 +
@joshcho will present MetaREPL, an embedded LLM REPL. +
Phoenix will present a tool built with Electric, PixiJS and tech.ml.dataset for time-series analysis inspired by TradingView. +
&hellip; you? +
 +
 +
Joining +
Please use the Going button at the top of this post to mark your participation. +
You can also use the Add to Calendar to add the event to your calendar. +
 +
Length +
The official part will be 90 minutes long. +
Sometimes, some of us like to stay longer and chat. +
 +
Video Call +
Updated Zoom link: Launch Meeting - Zoom +
 +
Recording +
The meeting will be recorded and shared publicly. +
Some parts will be unrecorded. +
 +
Zulip: https://clojurians.zulipchat.com/#narrow/stream/262224-events/near/404246049 +

