= Visual-tools meeting 19 - Electric
2023-07-07
:jbake-type: event
:jbake-edition: 
:jbake-link: https://clojureverse.org/t/visual-tools-meeting-19-electric-login-for-details/10029
:jbake-location: online
:jbake-start: 2023-07-07
:jbake-end: 2023-07-07

== Visual-tools meeting 19 - Electric (login for ...

Visual-tools meeting 19 - Electric (login for details) +
 +
While the coming meeting 18 of the visual-tools group is this Saturday, in this post we are announcing meeting 19 &ndash; a special meeting where @dustingetz will present Electric. +
Preparing for the session, you may join the thread at the Clojurians Slack. +
 +
Joining +
Please use the Going button at the top of this post to mark your participation. +
You can also use the Add to Calendar to add the event to your calendar. +
 +
Agenda +
 +
presentation by @dustingetz +
 +
discussion +
 +
 +
Time +
Friday July 7th 4pm UTC +
 +
Length +
The official part will be 90 minutes long. +
Sometimes some of us like to stay longer and chat. +
 +
Video Call +
Updated Zoom link: Launch Meeting - Zoom +
 +
Recording +
The meeting will be recorded and shared publicly. +
Some parts will be unrecorded. +
 +
Zulip: https://clojurians.zulipchat.com/#narrow/stream/262224-events/near/360372177 +

