= Visual-tools meeting 18
2023-05-27
:jbake-type: event
:jbake-edition: 
:jbake-link: https://clojureverse.org/t/visual-tools-meeting-18-various-updates/9981
:jbake-location: online
:jbake-start: 2023-05-27
:jbake-end: 2023-05-27

== Visual-tools meeting 18 - various updates

The visual tools group will have its 18th meeting on May 26th. +
In this meeting, a few of our friends will share updates on their current projects. Please see the gradually updating agenda below, and please reach out to add your topics to the Agenda. +
A few of the topics will be updates on ongoing projects, but we will encourage participants to make their presentations self-contained. +
 +
Agenda +
(gradually updating) +
 +
 +
@daslu - updates about using Kindly - Clay - Quarto in documentation +
&hellip; you? +
 +
 +
Joining +
Please use the Going button at the top of this post to mark your participation. +
You can also use the Add to Calendar to add the event to your calendar. +
 +
Length +
The official part will be 90 minutes long. +
Sometimes some of us like to stay longer and chat. +
 +
Video Call +
Updated Zoom link: Launch Meeting - Zoom +
 +
Recording +
The meeting will be recorded and shared publicly. +
Some parts will be unrecorded. +
 +
Zulip: https://clojurians.zulipchat.com/#narrow/stream/262224-events/near/355028979 +

