= Why you need Fulcro, the framework to
2023-07-11
:jbake-type: event
:jbake-edition: 
:jbake-link: https://www.meetup.com/London-Clojurians/events/293543779/
:jbake-location: 
:jbake-start: 2023-07-11
:jbake-end: 2023-07-11

== Why you need Fulcro, the framework to build ap...

Why you need Fulcro, the framework to build apps better, faster (by Jakub Hol&yacute;) +
 +
THIS IS AN ONLINE EVENT +
[Connection details will be shared 1h before the start time] +
The London Clojurians are happy to present: +
Title: Why you need Fulcro, the web framework to build apps better, faster +
Speaker: Jakub Hol&yacute; +
Time: 2023-07-11 @ 18:30 (London time) +
Local time: https://time.is/1830_11_July_2023_in_London/ (click here for local time) +
Jakub Hol&yacute; (https://holyjak.cz/) will be presenting: +
&quot;Why you need Fulcro, the web framework to build apps better, faster&quot; +
Fulcro (https://github.com/fulcrologic/fulcro) is my web framework of +
choice whenever I need to create any non-trivial web application +
thanks to its productivity. Its overarching design goal is sustainable +
development speed as time goes and code grows and it really shows +
up. It is developer friendly, with minimal boilerplate, and features +
you need for any serious application. And it is surprisingly +
flexible. Fulcro is based on a few simple ideas that combine +
powerfully to produce a multitude of capabilities, including its Rapid +
Application Development &quot;add-on&quot;. Some people find Fulcro complicated +
and scary - but it doesn't need to be. Stop choosing &quot;simpler&quot; web +
frameworks - and ending up implementing half of Fulcro with much more +
effort and verbosity and much less value. I will present the +
minimalist way of learning Fulcro with its three corner stones and +
explain Fulcro's building blocks. After this talk, you will understand +
the design and value of Fulcro, be motivated to learn it, and equipped +
to do so quickly. +
Jakub has been developing enterprise software since 2005, fell in love +
with Clojure in 2012, and with Fulcro in 2020. He cares deeply about +
productivity (and thus Clojure, DevOps, and Fulcro) and quality and +
enjoys sharing his discoveries and thoughts on his blog. Aside of his +
daily job, he also mentors and pair-programs with Fulcro beginners. He +
comes from the Czech Republic and lives currently in Norway. +
If you missed this event, you can watch the recording on our YouTube channel: +
https://www.youtube.com/@LondonClojurians +
(The recording will be uploaded a couple of days after the event.) +
Please, consider supporting the London Clojurians with a small donation: +
https://opencollective.com/london-clojurians/ +
Your contributions will enable the sustainability of the London +
Clojurians community and support our varied set of online and +
in-person events: +
- ClojureBridge London: supports under-represented groups discover Clojure +
- re:Clojure: our **free** to attend annual community conference +
- monthly meetup events with speakers from all over the world +
- subscription and admin costs such as domain name &amp; Zoom plan for +
larger online meetups +
Thank you to our sponsors: +
- https://juxt.pro/ +
- https://flexiana.com/ +
- https://gaiwan.co/ +
- https://freshcodeit.com/ +
- https://nette.io/ +
- https://nilenso.com/ +
- And many individual sponsors +
 +
Zulip: https://clojurians.zulipchat.com/#narrow/stream/262224-events/near/358742727 +

