= Writing Maintainable Clojure
2023-11-28
:jbake-type: event
:jbake-edition: 
:jbake-link: https://www.meetup.com/london-clojurians/events/295880507/
:jbake-location: online
:jbake-start: 2023-11-28
:jbake-end: 2023-11-28

== Writing Maintainable Clojure Applications (by ...

Writing Maintainable Clojure Applications (by Dmitri Sotnikov) +
 +
THIS IS AN ONLINE EVENT +
[Connection details will be shared 1h before the start time] +
The London Clojurians are happy to present: +
Title: Writing Maintainable Clojure Applications +
Speaker: Dmitri Sotnikov +
Time: 2023-11-28 @ 18:30 (London time) +
Local time: click here for local time +
Dmitri Sotnikov (https://github.com/yogthos/) will be presenting: +
&quot;Writing Maintainable Clojure Applications&quot; +
This talk will discuss a strategy for structuring large Clojure applications to facilitate maintainability. +
Dmitri has over a decade of experience doing web development using Clojure and has been an active member of the open source community. Dmitri is the author of Luminus and Kit microframeworks as well as a number of popular libraries. +
If you missed this event, you can watch the recording on our YouTube channel: +
https://www.youtube.com/@LondonClojurians +
(The recording will be uploaded a couple of days after the event.) +
Please, consider supporting the London Clojurians with a small donation: +
https://opencollective.com/london-clojurians/ +
Your contributions will enable the sustainability of the London Clojurians community and support our varied set of online and in-person events: +
 +
 +
ClojureBridge London: supports under-represented groups discover Clojure +
 +
 +
re:Clojure: our free to attend annual community conference +
 +
 +
monthly meetup events with speakers from all over the world +
 +
 +
subscription and admin costs such as domain name &amp; Zoom plan for larger online meetups +
 +
 +
Thank you to our sponsors: +
 +
 +
https://juxt.pro/ +
 +
 +
https://flexiana.com/ +
 +
 +
https://gaiwan.co/ +
 +
 +
And many individual sponsors +
 +
Zulip: https://clojurians.zulipchat.com/#narrow/stream/262224-events/near/391693908 +

