= IN/Clojure
IN/Clojure
2020-02-15
:jbake-type: event
:jbake-edition: 2020
:jbake-link: http://inclojure.org/
:jbake-location: Pune, India
:jbake-start: 2020-02-14
:jbake-end: 2020-02-15

IN/Clojure 2020 is the 4th edition of India's annual Clojure and Clojurescript conference, and Asia's first. We were also Asia's only such conference, but no more; yay ClojuRU!

IN/Clojure strives to facilitate the free exchange of ideas between new and experienced Clojure programmers alike. Learning and networking opportunities abound across:

* A single-track day of conference talks with 150-odd attendees and our awesome sponsors.
* A day of hands-on workshops having 80-100 participants across a track for newcomers and another for more experienced Clojurists.
* Oh, and the after-party(ies) and impromptu get-togethers that invariably happen.

Over the years, IN/Clojure has helped kick-start a series of Clojure workshops and meet-ups across the country. It has helped companies hiring Clojurists reach out to a wonderful community. And it has helped attendees make a strong case for Clojure/Clojurescript adoption in their companies.

We hope to make IN/Clojure 2020 bigger this year and continue our efforts to help foster the growing Clojure community in Asia/India.

And we hope to see you there!

* Propose a talk: https://hasgeek.com/inclojure/2020/proposals#call-for-proposal
* Follow us for the latest-greatest: https://twitter.com/in_clojure
