= :clojureD
clojureD
2022-02-07
:jbake-type: event
:jbake-edition: 2022
:jbake-link: http://www.clojured.de/
:jbake-location: Berlin, Germany
:jbake-start: 2022-06-11
:jbake-end: 2022-06-11

The developer conference :clojureD premiered in 2015 and quickly evolved to the biggest annual Clojure conference in Germany. 
Software developers from all over the world meet in Berlin to share new, amazing and mind-blowing ideas and techniques. 

After two years without meeting the community in real, this year's special summer beach camp will focus on having a really good time together.
Besides of exciting talks there will be space, time and activities to have thrilling exchanges, chats and fun.

And if that's not enough,:clojureD is also framed by a pre-conference welcome meet up before and a get-together at the beach right after the conference.

Call for proposals is open until 4 March 2022.
CfP is for full talks (30 minutes long, including Q & A). 
For lightning talks (5 minutes) you can register straight at the conference. We’ll have a limited number of spots and it’ll be first come first served.

Tickets will go on sale in February.

We are excited to see you all back in Berlin for another great an inspiring :clojureD conference!
