= ClojureBridge London
London Clojurians
2022-09-16
:jbake-type: event
:jbake-edition: 2022
:jbake-link: https://www.meetup.com/london-clojurians/events/286832822/
:jbake-location: London, United Kingdom
:jbake-start: 2022-09-16
:jbake-end: 2022-09-17

Saturday workshop learning Clojure with the help of a coach (attend on Friday evening for an introduction and setup)
Please bring a laptop to participate in the workshop.

ClojureBridge is a fun, free and friendly workshop for trans/cis women and non-binary people. The workshop is suitable for people just starting to code, or people on their first language who are also Clojure curious.

## Event overview

Friday evening we have members of the community sharing their development experiences and show what you can do with Clojure. We also help you install Clojure development tools (optional).

https://clojurebridgelondon.github.io/workshop/development-tools/install-guides/

;;Note: If you cannot make Friday please let us know and we will stream the presentations to you via YouTube or similar service.

Saturday we coach you through a day of small practical exercises, building responsive websites or creating simple games. We aim for 1-2-1 coaching so we can support you each step of the way.

## Why learn Clojure?

Clojure is a small language with a simple design that can be used to build apps for the web, mobile apps, and even desktop apps. Clojure is a great choice for those new to programming, or existing developers who want to learn about functional programming and use it in the software industry.

Clojure has a huge amount of libraries available to help you build a wide
range of apps really quickly. You can use all the libraries from its host
platforms, JavaScript/Node.js, Java or Microsoft .Net, too.

For more information, please take a look at the ClojureBridge London website:

http://clojurebridgelondon.github.io/

## Requirements

Each participant requires their own laptop with either MacOSX, Linux or
Windows operating system. We help you set up your laptop for Clojure during the Friday evening.

## Typical workshop schedule

* Friday evening - Intro & Install
* 18.30 - Doors open & social
* 19.00 - Introductions, talks & demo
* 19.45 - Install Clojure tools or try the workshop out with a coach
* 20.30 - Finish

Saturday - Workshop
* 10.00 - Doors open, breakfast
* 11.00 - Coding starts
* 12.50 - Group show & tell
* 13.00 - Lunch & talks
* 14.00 - Continue coding
* 16.30 - Retrospective - your feedback

We will encourage you to have regular breaks during the workshop, to give your brain a chance to absorb all this new information.

## Sponsors

Thank you to our sponsor SignalAI for providing the venue and all the food and refreshments for the event. We will aim to have 50% vegetarian food and around 10% of that will be vegan. We can always increase this based on you feedback.

## Who is involved

The event is free of charge and run by unpaid volunteers from the Clojure community. While the workshop is primarily for trans/cis women & non-binary attendees, our coaches and organisers are members of the local Clojure community of any gender or none. Everyone agrees to abide by the ClojureBridge Code of Conduct.

http://bridgefoundry.org/code-of-conduct/

If anyone is interested in volunteering as a coach, take a look at the learning paths (https://clojurebridgelondon.github.io/#learning-paths). If you understand the the basic syntax of Clojure and know some of the most common functions, then you can coach. Coach training is provided around one/two weeks before the event