= London Clojurians - August
London Clojurians - August
2022-08-02
:jbake-type: event
:jbake-edition: 2022
:jbake-link: https://www.meetup.com/london-clojurians/events/286468872/
:jbake-location: Online
:jbake-start: 2022-08-02
:jbake-end: 2022-08-02

The London Clojurians are happy to present:

== Transform Microsoft Office Solutions into Cloud-savvy Linked Data Microservices With Clojure on .NET

Bob Calco (https://www.linkedin.com/in/bob-calco/) will be presenting:
"Transform Microsoft Office Solutions into Cloud-savvy Linked Data Microservices With Clojure on .NET"

ClojureCLR hasn't yet gotten a lot of attention from mainstream .NET
developers, and from the point of view of mainstream JVM-focused
Clojurians, there haven't been many compelling reasons to work on the
CLR--until now. Now it emerges from the shadows of a mostly unified
.NET 6 with a purpose: to modernize Microsoft Office/365 solutions for
a new world of data interoperability.
Join Bob Calco as he describes the upcoming Professional Edition of
Acceλerate for Microsoft 365, which adds ClojureCLR to power the
database component of this innovative add-in and demonstrates how you
can help Office solution developers and enterprise customers transform
their desktop data silos into Cloud-savvy linked data microservices!
Clojure was never intended to run only on the JVM and you can be part
of teaching the .NET world why it deserves to be one of .NET's
most-used languages in an increasingly distributed solution landscape
for which most popular languages are ill-prepared.

Bob is a seasoned enterprise architect and a proven software innovator
with over 20+ years of experience designing, building and leading
teams to deliver large-scale, enterprise solutions in the healthcare,
financial services and retail sectors. For the past 5 years, Bob’s
work has focused on data sharing and interoperability both within and
between large, distributed enterprise systems. Bob was the primary
visionary and architect for the VistA.js Platform within the VA, a
Class 1 enterprise microservices framework that enabled data
federation and reconciliation across the VA’s 154 medical centers.
Currently, he is leading the Apex Team to address current industry
challenges associated with Provider Data Management/Provider
Directories.
Bob is a certified expert in multiple programming languages, having
worked productively in over a dozen programming environments and
platforms as diverse as C++, Delphi, Ada, Java, .NET (C#, VB),
JavaScript, LISP, Clojure, Scala, Smalltalk, Ruby and others.

