= #ai-assisted-coding Clojure Meetup
2025-06-21
:jbake-type: event
:jbake-edition: 
:jbake-link: https://clojureverse.org/t/ai-assisted-coding-clojure-meetup/11465
:jbake-location: online
:jbake-start: 2025-06-21
:jbake-end: 2025-06-21

== #ai-assisted-coding Clojure Meetup

Recently, the #ai-assisted-coding channel at the Clojurians Slack has been very active with ideas, updates, and advice. +
To support that, @John_Newman and @bhauman are organising a meetup this Saturday to share ideas between everybody. +
More details +
For the full connection details, see the Slack thread. +
Original announcement +
@John_Newman said (at Slack): +
 +
Hey everybody - Bruce and I were chatting and we want to have an imprompt u (lol) meetup to share ideas between everyone. No specific agenda - just helping each other fuse up on the best ai assisted coding methods lately, and look for more opportunities for us all to collaborate on common solutions for getting this stuff done in Clojure. I&rsquo;ll show my stuff off. Folks can show what they&rsquo;ve been hacking on. +
 +
 +
Zulip: https://clojurians.zulipchat.com/#narrow/stream/262224-events/near/525066794 +

