= Building a 3D Multiplayer Shooter in
2025-04-29
:jbake-type: event
:jbake-edition: 
:jbake-link: https://www.meetup.com/london-clojurians/events/307082137/
:jbake-location: online
:jbake-start: 2025-04-29
:jbake-end: 2025-04-29

== Building a 3D Multiplayer Shooter in Clojure (...

Building a 3D Multiplayer Shooter in Clojure (by Ertugrul Cetin) +
 +
THIS IS AN ONLINE EVENT +
[Connection details will be shared 1h before the start time] +
The London Clojurians are happy to present: +
Title: Building a 3D Multiplayer Shooter in Clojure: The Making of Wizard Masters +
Speaker: Ertugrul Cetin +
Time: 2025-04-29 @ 18:30 (London time) +
Local time: click here for local time +
Ertugrul Cetin (https://github.com/ertugrulcetin) will be presenting: +
&quot;Building a 3D Multiplayer Shooter in Clojure: The Making of Wizard Masters&quot; +
In this talk, the speaker will walk through how Wizard Masters, a 3D multiplayer browser game, was built using Clojure and Babylon.js. Attendees will get a peek into the architecture, tooling, and lessons learned from blending fullstack Clojure with real-time 3D game development. +
The speaker has been working with Clojure for nearly a decade, mostly in fullstack SaaS development. For the past 4 years, he&rsquo;s been exploring game development as a hobby, building Wizard Masters, a browser-based 3D multiplayer shooter. +
If you missed this event, you can watch the recording on our YouTube channel: +
https://www.youtube.com/@LondonClojurians +
(The recording will be uploaded a couple of days after the event.) +
Please, consider supporting the London Clojurians with a small donation: +
https://opencollective.com/london-clojurians/ +
Your contributions will enable the sustainability of the London Clojurians community and support our varied set of online and in-person events: +
 +
ClojureBridge London: supports under-represented groups discover Clojure +
re:Clojure: our annual community conference +
monthly meetup events with speakers from all over the world +
subscription and admin costs such as domain name &amp; StreamYard subscription +
 +
Thank you to our sponsors: +
 +
https://juxt.pro/ +
https://flexiana.com/ +
And many individual sponsors +
 +
Zulip: https://clojurians.zulipchat.com/#narrow/stream/262224-events/near/509921572 +

