= Clein: Bringing a bit of leiningen to
2025-01-21
:jbake-type: event
:jbake-edition: 
:jbake-link: https://www.meetup.com/london-clojurians/events/305279887/
:jbake-location: online
:jbake-start: 2025-01-21
:jbake-end: 2025-01-21

== Clein: Bringing a bit of leiningen to deps.edn...

Clein: Bringing a bit of leiningen to deps.edn (by Noah Bogart) +
 +
THIS IS AN ONLINE EVENT +
[Connection details will be shared 1h before the start time] +
The London Clojurians are happy to present: +
Title: Clein: Bringing a bit of leiningen to deps.edn +
Speaker: Noah Bogart +
Time: 2025-01-21 @ 18:30 (London time) +
Local time: click here for local time +
Noah Bogart (https://github.com/NoahTheDuke) will be presenting: +
&quot;Clein: Bringing a bit of leiningen to deps.edn&quot; +
Clein attempts to handle the basic use cases of build.clj, covering the boilerplate with minimal configuration and sensible defaults. This talk will go over why and how Clein was built, and future plans. +
Noah has been a hobby programmer since 2002, a professional programmer since 2016, and a Clojure fanatic since 2018. He loves to take data in, change it, and push it out. +
If you missed this event, you can watch the recording on our YouTube channel: +
https://www.youtube.com/@LondonClojurians +
(The recording will be uploaded a couple of days after the event.) +
Please, consider supporting the London Clojurians with a small donation: +
https://opencollective.com/london-clojurians/ +
Your contributions will enable the sustainability of the London Clojurians community and support our varied set of online and in-person events: +
 +
ClojureBridge London: supports under-represented groups discover Clojure +
re:Clojure: our free to attend annual community conference +
monthly meetup events with speakers from all over the world +
subscription and admin costs such as domain name &amp; StreamYard subscription +
 +
Thank you to our sponsors: +
 +
https://juxt.pro/ +
https://flexiana.com/ +
And many individual sponsors +
 +
Zulip: https://clojurians.zulipchat.com/#narrow/stream/262224-events/near/491802512 +

