= Clojure DSP meeting 2025-11-02
2025-11-02
:jbake-type: event
:jbake-edition: 
:jbake-link: https://clojureverse.org/t/clojure-dsp-meeting-2025-11-02/14767
:jbake-location: online
:jbake-start: 2025-11-02
:jbake-end: 2025-11-02

== Clojure DSP meeting 2025-11-02

Once in a while, a few of the Scicloj freinds will meet to learn about signal processing, following the Think DSP book by Allen B. Downey, and implementing things in Clojure. Our notes will be published at Clojure Civitas. +
This will be the first meeting. We will discuss a bit of our plans, setup for sharing notes, etc., and look into the first chapter. +
Joining +
Please let us know if you are planning to join by dropping a message at #dsp &gt; meeting 2025-11-02 on the Clojurians Zulip Chat (require login). +
Then, we will add you to the calendar event. +
Background +
Clojure knowledge will be assumed. We will adapt the style and pace given the backgrounds of participants who let us know beforehand. +
Chat +
We will use the #dsp channel at the Zulip chat. +
Length +
The official session will run for 120 minutes. Informal discussions may continue afterwards for those interested. +
Recording +
We will possibly share a recording internally in the Zulip chat. +
 +
Zulip: https://clojurians.zulipchat.com/#narrow/stream/262224-events/near/553228529 +

