= Clojure real-world-data meeting 26
2025-03-09
:jbake-type: event
:jbake-edition: 
:jbake-link: https://clojureverse.org/t/clojure-real-world-data-meeting-26-prep-meeting-for-conference-cfp/11228
:jbake-location: online
:jbake-start: 2025-03-09
:jbake-end: 2025-03-09

== Clojure real-world-data meeting 26 - prep meet...

Clojure real-world-data meeting 26 - prep meeting for conference cfp +
 +
This will be the 26th meeting of the real-world-data group &ndash; one of a few conference prep sessions facilitated by @Melody. +
The meeting will be dedicated to discussing talk proposals for upcoming  SciNoj Light  conference. +
Updates about the agenda will be shared in the Zulip chat. +
 +
If you wish to join the group, please reach out beforehand.  +
If you wish to present anything, please reach out soon. +
 +
(Scicloj contact details) +
Zoom link  +
 +
   +
       +
 +
      Zoom Video +
   +
 +
   +
     +
 +
Join our Cloud HD Video Meeting +
 +
  Zoom is the leader in modern enterprise video communications, with an easy, reliable cloud platform for video and audio conferencing, chat, and webinars across mobile, desktop, and room systems. Zoom Rooms is the original software-based conference... +
 +
 +
   +
 +
   +
     +
     +
   +
 +
   +
 +
 +
About SciNoj Light +
In recent months, the Clojure toolkit for data and science has been maturing. Thus, in 2025, Scicloj can finally shift more resources into making it accessible and well-known. SciNoj Light is one of the first steps in that direction. It is an online conference where Clojurians will share their short-term data analysis. The conference will be on May 16-17, and proposals should be submitted by March 15th. +
parens1920&times;1440 98.2 KB +
 +
Zulip: https://clojurians.zulipchat.com/#narrow/stream/262224-events/near/502397705 +

