= Clojure GIS meeting 2025-11-20
2025-11-20
:jbake-type: event
:jbake-edition: 
:jbake-link: https://clojureverse.org/t/clojure-gis-meeting-2025-11-20/14777
:jbake-location: online
:jbake-start: 2025-11-20
:jbake-end: 2025-11-20

== Clojure GIS meeting 2025-11-20

Once in a while, a few of the Scicloj freinds will meet to discuss, explore, and document the use of Clojure for GIS. +
A few of our friends are quite experienced in geospatial analysis, remote sensing, urban sensing, and more. Gladly, we found a time where we could meet and initiate some collaborations. +
Joining +
Please let us know if you are planning to join by dropping a message at the #gis &gt; meeting 2025-11-20 topic thread on the Clojurians Zulip Chat (require login). +
A Zoom link will be shared at that thread before the meeting. +
For your convenience, you can also click Add to Calendar to add this event to your calendar. +
Background +
Clojure knowledge will be assumed. We will adapt the style and pace given the backgrounds of participants who let us know beforehand. +
Chat +
We will use the #gis channel at the Zulip chat. +
Length +
The official session will run for 120 minutes. Informal discussions may continue afterwards for those interested. +
Recording +
We will possibly share a recording internally in the Zulip chat. +
 +
 +
Zulip: https://clojurians.zulipchat.com/#narrow/stream/262224-events/near/556895972 +

