= Clojure real-world-data meeting 25
2025-02-21
:jbake-type: event
:jbake-edition: 
:jbake-link: https://clojureverse.org/t/clojure-real-world-data-meeting-25-prep-meeting-for-conference-cfp/11201
:jbake-location: online
:jbake-start: 2025-02-21
:jbake-end: 2025-02-21

== Clojure real-world-data meeting 25 - prep meet...

Clojure real-world-data meeting 25 - prep meeting for conference cfp +
 +
Hi! +
As @melody just announced in the Clojure Google group, on Feb. 21st, we will have the 25th meeting of the real-world-data group, which will serve as a first prep session for the upcoming  SciNoj Light  conference! +
Updates about the agenda will be shared in the Zulip chat. +
If you wish to join the group, please reach out beforehand.  +
If you wish to present anything, please reach out soon. +
About SciNoj Light: +
In recent months, the Clojure toolkit for data and science has been maturing. Thus, in 2025, Scicloj can finally shift more resources into making it accessible and well-known. SciNoj Light is one of the first steps in that direction. It is an online conference where Clojurians will share their short-term data analysis. The conference will be on May 16-17, and proposals should be submitted by March 15th. +
parens1920&times;1440 98.2 KB +
 +
Zulip: https://clojurians.zulipchat.com/#narrow/stream/262224-events/near/498442945 +

