= Clojure DSP meeting 2025-11-08
2025-11-08
:jbake-type: event
:jbake-edition: 
:jbake-link: https://clojureverse.org/t/clojure-dsp-meeting-2025-11-08/14769
:jbake-location: online
:jbake-start: 2025-11-08
:jbake-end: 2025-11-08

== Clojure DSP meeting 2025-11-08

Once in a while, a few of the Scicloj freinds will meet to learn about signal processing, implement things in Clojure. +
This will be the second meeting. It is not too late to join &ndash; please reach out beforehand, and we will help you catch up. +
Joining +
Please let us know if you are planning to join by dropping a message at #dsp &gt; meeting 2025-11-08 on the Clojurians Zulip Chat (require login). +
Then, we will add you to the calendar event. +
Text +
We follow the Think DSP book by Allen B. Downey and the Think DSP 2 draft notebooks. +
Our notes will be published at Clojure Civitas. +
Background +
Clojure knowledge will be assumed. We will adapt the style and pace given the backgrounds of participants who let us know beforehand. +
Chat +
We will use the #dsp channel at the Zulip chat. +
Length +
The official session will run for 120 minutes. Informal discussions may continue afterwards for those interested. +
Recording +
We will possibly share a recording internally in the Zulip chat. +
More info +
See the group&rsquo;s page. +
 +
Zulip: https://clojurians.zulipchat.com/#narrow/stream/262224-events/near/553976810 +

