= Data-recur meeting 7 - R4Clj 1
2025-01-31
:jbake-type: event
:jbake-edition: 
:jbake-link: https://clojureverse.org/t/data-recur-meeting-7-r4clj-1-introducing-r-and-the-tidyverse/11148
:jbake-location: online
:jbake-start: 2025-01-31
:jbake-end: 2025-01-31

== Data-recur meeting 7 - R4Clj 1: Introducing R ...

Data-recur meeting 7 - R4Clj 1: Introducing R and the Tidyverse +
 +
The data-recur group will have its next meeting on Jan 31st. +
This will be a beginning of a series of meetups, where we introduce the R languages and its ecosystem to the Clojure crowd. +
While Clojure already has an established collection of libraries for data science, it can be enlightening for Clojurians to learn about a different-but-similar language. A few of the Clojure data science libraries, such as Tablecloth and Tableplot, are explicitly inspired by R and its packages. To encourage additional inspiration of this kind, we will host a few meetings for the Clojure audience to discuss R and its relationship with Clojure. +
Agenda for this meeting +
 +
The R language +
The Tidyverse packages +
A small example +
Discussion +
 +
Joining  +
 +
Please mark your participation using the Your rsvp button at the top of this page (requires Clojureverse login). +
Please join the Clojurians Zulip chat beforehand. +
You can also use the Add to Calendar button to add the event to your calendar. +
 +
Preparing for this meeting +
Before the meeting, it is recommended to install R and the Tidyverse package in your system and play with the R REPL a little bit. +
Length +
The official part will be 90 minutes long. +
Sometimes some of us like to stay longer and chat. +
Platform +
 +
Video meeting: Launch Meeting - Zoom +
Text chat: We will use the #data-recur Zulip stream (requires Zulip login). +
 +
Recording +
Some parts of the meeting will be recorded and probably shared publicly. +
Some parts will be unrecorded. +
 +
Zulip: https://clojurians.zulipchat.com/#narrow/stream/262224-events/near/494306905 +

