= Don't fear the Storm (by Juan Monetta)
2025-01-28
:jbake-type: event
:jbake-edition: 
:jbake-link: https://www.meetup.com/london-clojurians/events/305198588/
:jbake-location: online
:jbake-start: 2025-01-28
:jbake-end: 2025-01-28

== Don't fear the Storm (by Juan Monetta)

THIS IS AN ONLINE EVENT +
[Connection details will be shared 1h before the start time] +
The London Clojurians are happy to present: +
Title: Don't fear the Storm +
Speaker: Juan Monetta +
Time: 2025-01-28 @ 18:30 (London time) +
Local time: click here for local time +
Juan Monetta (https://github.com/jpmonettas/) will be presenting: +
&quot;Don't fear the Storm&quot; +
We will dig into FlowStorm internals, from its approach to instrumentation (ClojureStorm and ClojureScriptStorm), how FlowStorm uses it for tracing, indexing to providing tools for exploring and visualizing full systems execution. We will also explore a little bit of the new FlowStorm data visualization capabilities. +
Juan has been working as a programmer since late 90s, and working professionally as a Clojure developer since 2011 over many domains. He has a passion for dev tooling and anything that makes writing software more fun. +
If you missed this event, you can watch the recording on our YouTube channel: +
https://www.youtube.com/@LondonClojurians +
(The recording will be uploaded a couple of days after the event.) +
Please, consider supporting the London Clojurians with a small donation: +
https://opencollective.com/london-clojurians/ +
Your contributions will enable the sustainability of the London Clojurians community and support our varied set of online and in-person events: +
 +
ClojureBridge London: supports under-represented groups discover Clojure +
re:Clojure: our free to attend annual community conference +
monthly meetup events with speakers from all over the world +
subscription and admin costs such as domain name &amp; StreamYard subscription +
 +
Thank you to our sponsors: +
 +
https://juxt.pro/ +
https://flexiana.com/ +
And many individual sponsors +
 +
Zulip: https://clojurians.zulipchat.com/#narrow/stream/262224-events/near/491802584 +

