= Intro to Fugato (by David Nolen)
2025-02-04
:jbake-type: event
:jbake-edition: 
:jbake-link: https://www.meetup.com/london-clojurians/events/305401951/
:jbake-location: online
:jbake-start: 2025-02-04
:jbake-end: 2025-02-04

== Intro to Fugato (by David Nolen)

THIS IS AN ONLINE EVENT +
[Connection details will be shared 1h before the start time] +
The London Clojurians are happy to present: +
Title: Intro to Fugato +
Speaker: David Nolen +
Time: 2025-02-04 @ 18:30 (London time) +
Local time: click here for local time +
David Nolen (https://github.com/swannodette) will be presenting: +
&quot;Intro to Fugato&quot; +
A quick tour of Fugato, a tiny stateful property-based testing library for Clojure(Script). Fugato focuses on modeling the problem, but it's also easy to run the results against your programs. +
Lead developer of ClojureScript since 2012. +
If you missed this event, you can watch the recording on our YouTube channel: +
https://www.youtube.com/@LondonClojurians +
(The recording will be uploaded a couple of days after the event.) +
Please, consider supporting the London Clojurians with a small donation: +
https://opencollective.com/london-clojurians/ +
Your contributions will enable the sustainability of the London Clojurians community and support our varied set of online and in-person events: +
 +
ClojureBridge London: supports under-represented groups discover Clojure +
re:Clojure: our free to attend annual community conference +
monthly meetup events with speakers from all over the world +
subscription and admin costs such as domain name &amp; StreamYard subscription +
 +
Thank you to our sponsors: +
 +
https://juxt.pro/ +
https://flexiana.com/ +
And many individual sponsors +
 +
Zulip: https://clojurians.zulipchat.com/#narrow/stream/262224-events/near/491802606 +

