= Intro to Collet. A low-code ETL
2025-02-18
:jbake-type: event
:jbake-edition: 
:jbake-link: https://www.meetup.com/london-clojurians/events/305238843/
:jbake-location: online
:jbake-start: 2025-02-18
:jbake-end: 2025-02-18

== Intro to Collet. A low-code ETL management too...

Intro to Collet. A low-code ETL management tool (by Sergei Tkachenko) +
 +
THIS IS AN ONLINE EVENT +
[Connection details will be shared 1h before the start time] +
The London Clojurians are happy to present: +
Title: Intro to Collet. A low-code ETL management tool +
Speaker: Sergei Tkachenko +
Time: 2025-02-18 @ 18:30 (London time) +
Local time: click here for local time +
Sergei Tkachenko (https://github.com/margintop15px) will be presenting: +
&quot;Intro to Collet. A low-code ETL management tool&quot; +
In this talk, we'll explore the Collet project, its features, and core concepts. We'll begin with basic building blocks like tasks and actions, and discuss best practices for combining them effectively. You'll learn about built-in and custom actions, error handling, and job monitoring. Finally, we'll cover data exploration during development and deployment options using Docker containers. +
Sergei has been actively developing with Clojure since 2018, building a diverse portfolio of projects across different scales and domains. His experience spans from working with early-stage startups building solutions to architecting and maintaining high-load, data-intensive applications that process substantial volumes of information. +
If you missed this event, you can watch the recording on our YouTube channel: +
https://www.youtube.com/@LondonClojurians +
(The recording will be uploaded a couple of days after the event.) +
Please, consider supporting the London Clojurians with a small donation: +
https://opencollective.com/london-clojurians/ +
Your contributions will enable the sustainability of the London Clojurians community and support our varied set of online and in-person events: +
 +
ClojureBridge London: supports under-represented groups discover Clojure +
re:Clojure: our free to attend annual community conference +
monthly meetup events with speakers from all over the world +
subscription and admin costs such as domain name &amp; StreamYard subscription +
 +
Thank you to our sponsors: +
 +
https://juxt.pro/ +
https://flexiana.com/ +
And many individual sponsors +
 +
Zulip: https://clojurians.zulipchat.com/#narrow/stream/262224-events/near/491802625 +

