= London Clojurians Talk
2025-11-11
:jbake-type: event
:jbake-edition: 
:jbake-link: https://clojureverse.org/t/london-clojurians-talk-the-gaiwan-stack-by-arne-brasseur/14746
:jbake-location: online
:jbake-start: 2025-11-11
:jbake-end: 2025-11-11

== London Clojurians Talk: The Gaiwan Stack (by A...

London Clojurians Talk: The Gaiwan Stack (by Arne Brasseur) +
 +
MeetupIntro1920&times;1080 271 KB +
THIS IS AN ONLINE EVENT +
[Connection details will be shared 1h before the start time] +
The London Clojurians are happy to present: +
Title: The Gaiwan Stack +
Speaker: Arne Brasseur +
Time: 2025-11-11 @ 18:30 (London time) +
Local time: click here for local time +
RSVP: The Gaiwan Stack (by Arne Brasseur), Tue, Nov 11, 2025, 6:30 PM | Meetup +
Arne Brasseur (https://arnebrasseur.net) will be presenting: +
&ldquo;The Gaiwan Stack&rdquo; +
Since 2019 Gaiwan has either built or been involved with close to two dozen Clojure applications. This gives us a unique vantage point to look at the ecosystem. Over time we&rsquo;ve largely settled on a stack of libraries, tools, and practices that we are happy with. In this talk we&rsquo;ll go over what that stack looks like, which alternatives we&rsquo;ve considered, and why we made certain choices. +
Arne has been writing software since the early nillies. He started making Clojure screencast under the Lambda Island monniker in 2016 as a way to share his love for functional programming. In 2019 he founded the Gaiwan software consultancy. He&rsquo;s known for his open source projects like Kaocha, and for community organising, such as the Heart of Clojure conference in Belgium. +
If you missed this event, you can watch the recording on our YouTube channel: +
https://www.youtube.com/@LondonClojurians +
(The recording will be uploaded a couple of days after the event.) +
Please, consider supporting the London Clojurians with a small donation: +
https://opencollective.com/london-clojurians/ +
Your contributions will enable the sustainability of the London +
Clojurians community and support our varied set of online and +
in-person events: +
 +
ClojureBridge London: supports under-represented groups discover Clojure +
re:Clojure: our annual community conference +
monthly meetup events with speakers from all over the world +
subscription and admin costs such as domain name &amp; StreamYard subscription +
 +
Thank you to our sponsors: +
 +
https://juxt.pro/ +
https://gaiwan.co/ +
And many individual sponsors +
 +
RSVP: The Gaiwan Stack (by Arne Brasseur), Tue, Nov 11, 2025, 6:30 PM | Meetup +
 +
Zulip: https://clojurians.zulipchat.com/#narrow/stream/262224-events/near/542779534 +

