= Macroexpand-2 - Connecting Clojure Data
2025-08-09
:jbake-type: event
:jbake-edition: 
:jbake-link: https://clojureverse.org/t/macroexpand-2-connecting-clojure-data-practitioners/11485
:jbake-location: online
:jbake-start: 2025-08-09
:jbake-end: 2025-08-09

== Macroexpand-2 - Connecting Clojure Data Practi...

Macroexpand-2 - Connecting Clojure Data Practitioners +
 +
Join us for our second meeting of macroexpand gatherings, a Scicloj initiative that brings together Clojurians for focused, action-oriented discussions to help Clojure grow in new domains and use cases. +
Are you using Clojure for data analysis, modeling, engineering, or visualization? Whether you&rsquo;re with a startup, consultancy, academic institution, or any organization working with data, we want to connect with you. +
 Please share this broadly. +
This meeting is co-organised by @syungb &amp; @daslu. +
Joining +
  Please mark your participation using the form before Aug. 5th. +
Event details +
 +
 Sat, Aug. 9th, 2025, 13:00 UTC. +
 Duration: 3 hours +
 We will use Zoom for video. A link will be sent by email to participants. +
 Some parts will be recorded and shared publicly. +
 +
Getting the time right +
 +
The time at the top of this page is in your time zone. +
You can also use the click Add to calendar button +
&hellip; or see the event at the Clojure Calendar Feed. +
 +
More about the event +
 What makes this event different? +
It&rsquo;s a platform to: +
 +
Share real-world experiences and challenges +
Network with fellow practitioners +
Develop concrete solutions to common problems +
Shape the future of Clojure in data science +
 +
 Agenda +
 +
 +
 +
 +
Session +
Focus On +
 +
 +
 +
 +
Opening +
Welcome &amp; introductions +
 +
 +
Lightning Rounds +
Lightning talks from community members +
 +
 +
Noj Introduction +
Clojure data analysis toolkit demonstration +
 +
 +
Open Discussion +
Practical lessons from the field +
 +
 +
Strategic Discussion +
Growing teams and hiring +
 +
 +
Community Building +
Creating lasting support networks +
 +
 +
Action Planning +
Turn ideas &amp; suggestions into commitments +
 +
 +
 +
What we want to gain +
Our goal is to transform individual challenges into collective solutions, strengthening the entire Clojure data ecosystem. +
Any questions/suggestions? +
Please Reach out to participate in this collaborative effort to advance Clojure in the data space. +
 +
Zulip: https://clojurians.zulipchat.com/#narrow/stream/262224-events/near/528670570 +

