= Scicloj AI Meetup 2: practice session
2025-03-22
:jbake-type: event
:jbake-edition: 
:jbake-link: https://clojureverse.org/t/scicloj-ai-meetup-2-practice-session-build-a-rag/11252
:jbake-location: online
:jbake-start: 2025-03-22
:jbake-end: 2025-03-22

== Scicloj AI Meetup 2: practice session - build ...

Scicloj AI Meetup 2: practice session - build a RAG +
 +
In this meeting, the second meeting of the new scicloj-ai-meetups group, will be our first practice session. +
In practice sessions, we will dive into ideas and practices and implement them together. +
This time, we will practice building a RAG in Clojure +
We&rsquo;d love to hear your comments if you have some ideas or advice for this meeting. +
Joining  +
 +
Please mark your participation using the Your rsvp button at the top of this page (requires Clojureverse login). +
Please join the Clojurians Zulip chat beforehand. +
You can also use the Add to Calendar button to add the event to your calendar. +
 +
Chat +
We will use the #scicloj-ai-meetups channel of the Clojurians Zulip Chat (requires login). Please join the Zulip chat before attending our meetings. +
Length +
The official session will run for 90 minutes. +
Informal discussions may continue afterwards for those interested. +
Platform +
 +
Video meeting: Launch Meeting - Zoom +
Text chat: We will use the #ai-meetups Zulip stream (requires Zulip login) +
 +
Recording +
Portions of the meeting will be recorded and may be shared publicly. +
Some segments will remain unrecorded. +
joy21212&times;568 98.3 KB +
 +
Zulip: https://clojurians.zulipchat.com/#narrow/stream/262224-events/near/505709126 +

