= Scicloj AI Meetup 8: Clojure-MCP
2025-06-07
:jbake-type: event
:jbake-edition: 
:jbake-link: https://clojureverse.org/t/scicloj-ai-meetup-8-clojure-mcp/11438
:jbake-location: online
:jbake-start: 2025-06-07
:jbake-end: 2025-06-07

== Scicloj AI Meetup 8: Clojure-MCP

Please rsvp  +
This will be the eighth meeting of the scicloj-ai-meetups group. +
It will be a mix of a talk and a practice session. +
Agenda +
 +
@bhauman: Clojure MCP - REPL-Driven Development with AI Assistance +
A practice session (topic TBD) +
 +
Joining  +
 +
Please mark your participation using the Your rsvp button at the top of this page (requires Clojureverse login). +
Please join the Clojurians Zulip chat beforehand. +
You can also use the Add to Calendar button to add the event to your calendar. +
 +
Chat +
We will use the #scicloj-ai-meetups channel of the Clojurians Zulip Chat (requires login). Please join the Zulip chat before attending our meetings. +
Length +
The official session will run for 90 minutes. +
Informal discussions may continue afterwards for those interested. +
Platform +
 +
Video meeting: Launch Meeting - Zoom - please do not share this link anywhere  +
Text chat: We will use the #ai-meetups Zulip stream (requires Zulip login) +
 +
Recording +
Parts of the meeting will be recorded and may or may not be shared publicly. +
Some parts will remain unrecorded. +
 +
joy21212&times;568 98.3 KB +
 +
Zulip: https://clojurians.zulipchat.com/#narrow/stream/262224-events/near/520936248 +

