= Scicloj AI Meetup 10
2025-08-16
:jbake-type: event
:jbake-edition: 
:jbake-link: https://clojureverse.org/t/scicloj-ai-meetup-10-datascript-mcp-server/14598
:jbake-location: online
:jbake-start: 2025-08-16
:jbake-end: 2025-08-16

== Scicloj AI Meetup 10: datascript-mcp-server

Please rsvp  +
This scicloj-ai-meetups group is back with its meetups. We find it important to meet more than once in the coming few weeks, so we can prepare well for the upcoming Macroexpand-Deep conference. +
On the main part of this meeting, we will have @stevechan, who will talk about datascript-mcp-server. +
Also, it will be an opportunity to discuss your ideas and proposals for the upcoming conference. +
Agenda +
 +
@stevechan - datascript-mcp-server +
practice session: using LLMs with notebooks +
brainstorming Macroexpand-Deep +
 +
Joining  +
 +
Please mark your participation using the Your rsvp button at the top of this page (requires Clojureverse login). +
Please join the Clojurians Zulip chat beforehand. +
You can also use the Add to Calendar button to add the event to your calendar. +
 +
Zoom +
 +
Video meeting: Launch Meeting - Zoom - please do not share this link anywhere  +
 +
Chat +
We will use the #scicloj-ai-meetups channel of the Clojurians Zulip Chat (requires login). Please join the Zulip chat before attending our meetings. +
Length +
The official session will run for 90 minutes. +
Informal discussions may continue afterwards for those interested. +
Recording +
Parts of the meeting will be recorded and may or may not be shared publicly. +
Some parts will remain unrecorded. +
 +
joy21212&times;568 98.3 KB +
 +
Zulip: https://clojurians.zulipchat.com/#narrow/stream/262224-events/near/533142675 +

