= Scicloj AI Meetup 11
2025-08-23
:jbake-type: event
:jbake-edition: 
:jbake-link: https://clojureverse.org/t/scicloj-ai-meetup-11-agentic-workflows-with-grain/14617
:jbake-location: online
:jbake-start: 2025-08-23
:jbake-end: 2025-08-23

== Scicloj AI Meetup 11: Agentic workflows with G...

Scicloj AI Meetup 11: Agentic workflows with Grain +
 +
Please rsvp  +
The scicloj-ai-meetups is having a few meetings during August, preparing for the upcoming Macroexpand-Deep conference in October. +
At this meeting, we will have Cameron Barre, who will talk about the Grain framework for event sourcing and agentic workflows. +
Also, it will be an opportunity to discuss your ideas and proposals for the upcoming conference. +
Agenda +
 +
Grain - a talk by Cameron +
a discussion +
preparing for the Macroexpand-Deep conference +
 +
Joining  +
 +
Please mark your participation using the Your rsvp button at the top of this page (requires Clojureverse login). +
Please join the Clojurians Zulip chat beforehand. +
You can also use the Add to Calendar button to add the event to your calendar. +
 +
Zoom +
 +
Video meeting: Launch Meeting - Zoom - please do not share this link anywhere  +
 +
Chat +
We will use the #scicloj-ai-meetups channel of the Clojurians Zulip Chat (requires login). Please join the Zulip chat before attending our meetings. +
Length +
The official session will run for 90 minutes. +
Informal discussions may continue afterwards for those interested. +
Recording +
Parts of the meeting will be recorded and may or may not be shared publicly. +
Some parts will remain unrecorded. +
 +
joy21212&times;568 98.3 KB +
 +
Zulip: https://clojurians.zulipchat.com/#narrow/stream/262224-events/near/534694378 +

