= Scicloj AI Meetup 7
2025-05-24
:jbake-type: event
:jbake-edition: 
:jbake-link: https://clojureverse.org/t/scicloj-ai-meetup-7-can-we-turn-copilot-into-an-interactive-programmer/11384
:jbake-location: online
:jbake-start: 2025-05-24
:jbake-end: 2025-05-24

== Scicloj AI Meetup 7: Can we turn CoPilot into ...

Scicloj AI Meetup 7: Can we turn CoPilot into an Interactive Programmer? +
 +
Please rsvp  +
This will be the seventh meeting of the scicloj-ai-meetups group. +
It will be a mix of a talk and a practice session. +
Agenda +
 +
 +
@pez: Can we turn CoPilot into an Interactive Programmer? +
Introducing Calva Backseat Driver, REPL Tools for AI Agents +
 +
 +
A practice session: +
We will explore the integration of an LLM in a data analysis workflow. +
 +
 +
Joining  +
 +
Please mark your participation using the Your rsvp button at the top of this page (requires Clojureverse login). +
Please join the Clojurians Zulip chat beforehand. +
You can also use the Add to Calendar button to add the event to your calendar. +
 +
Chat +
We will use the #scicloj-ai-meetups channel of the Clojurians Zulip Chat (requires login). Please join the Zulip chat before attending our meetings. +
Length +
The official session will run for 90 minutes. +
Informal discussions may continue afterwards for those interested. +
Platform +
 +
Video meeting: Launch Meeting - Zoom - please do not share this link anywhere  +
Text chat: We will use the #ai-meetups Zulip stream (requires Zulip login) +
 +
Recording +
Parts of the meeting will be recorded and may or may not be shared publicly. +
Some parts will remain unrecorded. +
 +
joy21212&times;568 98.3 KB +
 +
Zulip: https://clojurians.zulipchat.com/#narrow/stream/262224-events/near/516532528 +

