= Scicloj AI Meetup 12: Practicing Grain
2025-09-30
:jbake-type: event
:jbake-edition: 
:jbake-link: https://clojureverse.org/t/scicloj-ai-meetup-12-practicing-grain/14739
:jbake-location: online
:jbake-start: 2025-09-30
:jbake-end: 2025-09-30

== Scicloj AI Meetup 12: Practicing Grain

Please rsvp  +
The 12th meeting of the scicloj-ai-meetups series will be a practice session. +
It will be co-organised by @pbaille and @daslu. +
Joining  +
 +
Please mark your participation using the Your rsvp button at the top of this page (requires Clojureverse login). +
Please join the Clojurians Zulip chat beforehand. +
You can also use the Add to Calendar button to add the event to your calendar. +
 +
Agenda +
Following meeting 11, where Cameron Barre presented the Grain framework, we will dive into the code, and practice creating little workflows. +
We will probably wonder about the idea of behavior trees, about the way event sourcing is handled, about the ergonomics, and about the use of DSPy. +
Possibly, Cameron will be present at the meeting, but this time, a few of us, non-experts, will also be trying things out. +
Background +
The meeting will be self-contained, and only Clojure knowledge will be assumed. +
However, it is recommended to watch the video of meeting 11, read Grain&rsquo;s readme, and look into the macroexpand-2-demo (that Cameron has created for our Macroexpand-2 meeting). +
Zoom +
 +
Video meeting: Launch Meeting - Zoom - please do not share this link anywhere  +
 +
Chat +
We will use the #scicloj-ai-meetups channel of the Clojurians Zulip Chat (requires login). Please join the Zulip chat before attending our meetings. +
Length +
The official session will run for 90 minutes. +
Informal discussions may continue afterwards for those interested. +
Recording +
Parts of the meeting will be recorded and may or may not be shared publicly. +
Some parts will remain unrecorded. +
 +
joy21212&times;568 98.3 KB +
 +
Zulip: https://clojurians.zulipchat.com/#narrow/stream/262224-events/near/540856439 +

