= Visual-tools meeting 27
2025-01-03
:jbake-type: event
:jbake-edition: 
:jbake-link: https://clojureverse.org/t/visual-tools-meeting-27-workflow-demos-1/11091
:jbake-location: online
:jbake-start: 2025-01-03
:jbake-end: 2025-01-03

== Visual-tools meeting 27: Workflow Demos 1

The visual tools group will have its 27th meeting on Jan 3rd 2025. +
This meeting is part of a short Workflow Demos series. A few of our friends will demonstrate their workflows for others to learn from. +
Agenda +
 +
@adham -  Emacs with CIDER and other useful packages +
Jarret Atkinson - VSCode with Calva and a few additional ideas +
@mauricioszabo - Pulsar  +
 +
Joining +
Please write to @daslu or comment below if you wish to participate. You can also use the Add to Calendar to add the event to your calendar. +
Length +
The official part will be 90 minutes long. +
Sometimes, some of us like to stay longer and chat. +
Video Call +
Zoom link: Launch Meeting - Zoom +
Recording +
Possibly, we will share a recording of parts of the meeting. This has not been decided yet. +
 +
Zulip: https://clojurians.zulipchat.com/#narrow/stream/262224-events/near/490223137 +

