= Visual-tools meeting 30
2025-01-23
:jbake-type: event
:jbake-edition: 
:jbake-link: https://clojureverse.org/t/visual-tools-meeting-30-workflow-demos-4/11134
:jbake-location: online
:jbake-start: 2025-01-23
:jbake-end: 2025-01-23

== Visual-tools meeting 30: Workflow Demos 4

The visual tools group will have its 30th meeting on Jan 23th 2025. +
This meeting is part of a short Workflow Demos series. A few of our friends will demonstrate their workflows for others to learn from. +
Agenda +
(updating gradually) +
 +
@stoica94 - using LLMs in Emacs for Clojure #1 +
@adham - using LLMs in Emacs for Clojure #2 +
TBD +
 +
Joining +
Please write to @daslu or comment below if you wish to participate. You can also use the Add to Calendar to add the event to your calendar. +
Length +
The official part will be 90 minutes long. +
Sometimes, some of us like to stay longer and chat. +
Video Call +
Zoom link: Launch Meeting - Zoom +
Recording +
Possibly, we will share a recording of parts of the meeting. This has not been decided yet.f +
 +
Zulip: https://clojurians.zulipchat.com/#narrow/stream/262224-events/near/492836393 +

