= Visual-tools meeting 34
2025-05-18
:jbake-type: event
:jbake-edition: 
:jbake-link: https://clojureverse.org/t/visual-tools-meeting-34-clojure-in-wasm-docker-nrepl-el/11385
:jbake-location: online
:jbake-start: 2025-05-18
:jbake-end: 2025-05-18

== Visual-tools meeting 34: Clojure in WASM, dock...

Visual-tools meeting 34: Clojure in WASM, docker-nrepl.el +
 +
(edit: updated agenda, 2024-05-13) +
(note the meeting is slightly longer than usual) +
Pleae rsvp  +
The visual tools group will have its 34th meeting on May 18th, 2025. +
Agenda +
 +
Clojure in WebAssembly - a practice session and a discussion with @roman01la and @Shagun_Agrawal following their blog posts (Running Clojure in WASM, Compiling Clojure to WebAssembly) +
CheerpJ - a brief demo by @jasalt +
docker-nrepl.el - a short talk by Andrey Subbotin  about Docker, nREPL, and the new package to connect them in Emacs +
Alex Coyle - nrepl-ws-server, nrepl-ws-client, and a a browser UI for Clay for beginner-friendly visual exploration +
 +
Joining +
Please RVSP at the top of this page (requires Clojureverse login). You can also use the Add to Calendar to add the event to your calendar. +
Length +
The official part will be 120 minutes long. +
Sometimes, some of us like to stay longer and chat. +
Video Call +
Zoom link: Launch Meeting - Zoom +
Recording +
Possibly, we will share a recording of parts of the meeting +
 +
Zulip: https://clojurians.zulipchat.com/#narrow/stream/262224-events/near/517832707 +

