= Visual-tools meeting 28
2025-01-07
:jbake-type: event
:jbake-edition: 
:jbake-link: https://clojureverse.org/t/visual-tools-meeting-28-workflow-demos-2/11092
:jbake-location: online
:jbake-start: 2025-01-07
:jbake-end: 2025-01-07

== Visual-tools meeting 28: Workflow Demos 2

The visual tools group will have its 28th meeting on Jan 7th 2025. +
This meeting is part of a short Workflow Demos series. A few of our friends will demonstrate their workflows for others to learn from. +
Agenda +
 +
Mykhaylo Beliansky - a Portal / Snitch / clj-reload combo +
@onetom - a few Cursive tricks +
@practicalli - Neovim with Conjure, Portal for data inspection, and Parinfer for structural editing +
 +
Joining +
Please write to @daslu or comment below if you wish to participate. You can also use the Add to Calendar to add the event to your calendar. +
Length +
The official part will be 90 minutes long. +
Sometimes, some of us like to stay longer and chat. +
Video Call +
Zoom link: Launch Meeting - Zoom +
Recording +
Possibly, we will share a recording of parts of the meeting. This has not been decided yet. +
 +
Zulip: https://clojurians.zulipchat.com/#narrow/stream/262224-events/near/490223208 +

