= Visual-tools meeting 31
2025-03-24
:jbake-type: event
:jbake-edition: 
:jbake-link: https://clojureverse.org/t/visual-tools-meeting-31-workflow-demos-5/11248
:jbake-location: online
:jbake-start: 2025-03-24
:jbake-end: 2025-03-24

== Visual-tools meeting 31: Workflow Demos 5

The visual tools group will have its 31st meeting on Mar 24th 2025. +
This meeting is part of a short Workflow Demos series. It will focus on Clay, a tool for REPL-friendly data visualization and notebooking +
Agenda +
(updating gradually) +
 +
@daslu - Clay overview: +
 +
setup +
beginner UX +
interactive data exploration +
documentation and publishing +
generated testing +
 +
 +
 +
Joining +
Please RVSP at the top of this page (requires Clojureverse login). You can also use the Add to Calendar to add the event to your calendar. +
Length +
The official part will be 90 minutes long. +
Sometimes, some of us like to stay longer and chat. +
Video Call +
Zoom link: Launch Meeting - Zoom +
Recording +
Possibly, we will share a recording of parts of the meeting. This has not been decided yet.f +
 +
Zulip: https://clojurians.zulipchat.com/#narrow/stream/262224-events/near/505133668 +

