= Clojure SYNC 
clojureSYNC
2018-02-15
:jbake-type: event
:jbake-edition: 2018
:jbake-link: https://clojuresync.com
:jbake-location: New Orleans, Louisiana
:jbake-start: 2018-02-15
:jbake-end: 2018-02-16

It’s a synchronous event, in a syncretist city with syncopated music, about an async language. On February 15th and 16th, 2018, two hundred Clojurists from around the world, like yourselves, will come to the heart of New Orleans to enjoy talks about humanity, business, and code through the lens of Clojure and Functional Programming.

The topics are different from what we’re used to at other conferences. If Strange Loop is about the confluence of industry and academia, Clojure SYNC is about the connections between our skills, our work, and the history of technology. If you like the PurelyFunctional.tv Newsletter, you’ll love the talks at Clojure SYNC. An explicit goal of the conference is to broaden our perspectives on the history of computing and how it fits into the history of humanity.
