= Welcome to Clojure!
Alex Miller
2016-01-14
:type: guides
:toc: macro
:icons: font

ifdef::env-github,env-browser[:outfilesuffix: .adoc]

toc::[]

== What tools do I need?

=== Clojure REPL

Clojure is a https://clojure.org/about/dynamic[dynamic development environment] where you interact with your Clojure program while you write it, growing and adding to it while it's running. The primary interface to this environment is the Read-Eval-Print-Loop (REPL). The REPL is a console interface that allows you to enter and execute commands and examine their results.

A typical REPL conversation might look like this:

[source,clojure-repl]
----
user=> (str "Hello " "world!")
"Hello world!"
user=> (+ 1 1)
2
----

To get started:

* **<<install_clojure_cli#,Install the Clojure command-line tool>>** - this tool provides a basic REPL along with other functions for downloading libraries and running Clojure programs. The command-line tool will download Clojure automatically when you use it.

Explore more:

* <<deps_and_cli#,Clojure CLI guide>>
* <<repl/introduction#,REPL guide>>

=== Clojure Editor

While learning Clojure, it is strongly recommended to use an editor that supports these two key features:

* REPL integration - evaluate code directly from your file editor in the runtime context of a connected REPL
* Structural editing - Text editors allow you to edit text made of characters. Clojure code consists almost entirely of forms with arbitrary nesting and structural editing refers to manipulating the structure of that tree of forms

These features will give you the best Clojure development experience.

Start here for simple environments that provide this experience:

* **<<aquamacs#,Install Aquamacs>>** [Mac]
* **<<vscode#,Install VS Code>>** [Windows, Linux, Mac]

Explore more:

* <<xref/../../community/tools#,More Clojure editors>> - many Clojure editor options exist that add additional features
* <<xref/../../community/tools#,Other tools>> - you will eventually want tools to build, deploy, and debug your programs

== How do I learn the language?

* <<learn/syntax#,Learn Clojure guide>>
* <<xref/../../community/books#,Clojure books>>
* ??

== Where can I ask questions?

There are many places to interact with other Clojure developers:

* https://ask.clojure.org[Ask Clojure] [official] - Clojure Q&A and knowledgebase
* https://clojurians.net[Clojurians Slack channel] - Clojure chat, check out #beginners, #jobs, etc
* ...

== Other resources

* ...
