= Getting Started
Alex Miller
2016-01-14
:type: guides
:toc: macro
:icons: font

ifdef::env-github,env-browser[:outfilesuffix: .adoc]

toc::[]

Welcome to Clojure!

Check out <<learn/syntax#,Learn Clojure>>, <<xref/../../community/resources#,Resources>>, or <<xref/../../community/books#,Books>> for learning the language!

== Clojure installer and CLI tools

Clojure provides <<deps_and_cli#,command line tools>> that can be used to start a Clojure repl, use Clojure and Java libraries, and start Clojure programs.

=== Installation on Mac via `brew`

Install the command line tools with brew:

[source,shell]
----
brew install clojure
----

If you've already installed, you can upgrade to the latest release with:

[source,shell]
----
brew upgrade clojure
----

=== Installation on Linux

1. Ensure that the following dependencies are installed: `bash`, `curl`, `rlwrap`, and Java (Java JDK 11, 9 and 8 should be acceptable but you may want to [choose between different vendors](https://purelyfunctional.tv/guide/clojure-jvm/#which-jdk) ).
2. Use the `linux-install` script to download and run the install, which will by default create executables `/usr/local/bin/clj`,   `/usr/local/bin/clojure` and directory `/usr/local/lib/clojure`:

[source,shell]
----
VERSION=1.10.0.442
curl -O https://download.clojure.org/install/linux-install-${VERSION}.sh
chmod +x linux-install-${VERSION}.sh
sudo ./linux-install-${VERSION}.sh
----

If you want to put everything into a single location (for example `/opt/infrastructure/clojure`), use option `--prefix` instead:

[source,shell]
----
VERSION=1.10.0.442
curl -O https://download.clojure.org/install/linux-install-${VERSION}.sh
chmod +x linux-install-${VERSION}.sh
sudo ./linux-install-${VERSION}.sh --prefix /opt/infrastructure/clojure
----

If you select the "single location" approach you need to extend the MANPATH so that manual pages can be found.

This is often done by extending `/etc/man_db.conf` adding a line like this:

----
MANPATH_MAP /opt/infrastructure/clojure/bin /opt/infrastructure/clojure/man
----

Note that the `VERSION` string is hardcoded in the `linux-install` script, which makes the script version-dependent!

You can remove the `linux-install` script after installation.

=== Installation on Windows

An early release version of clj on Windows is available at [clj on Windows](https://github.com/clojure/tools.deps.alpha/wiki/clj-on-Windows).
Please provide feedback at https://dev.clojure.org/jira/browse/TDEPS.

== Other ways to run Clojure

*Local build*

Download and build Clojure from source (requires Git, Java, and Maven):

[source,shell]
----
git clone https://github.com/clojure/clojure.git
cd clojure
mvn -Plocal -Dmaven.test.skip=true package
----

Then start the REPL with the local jar:

[source,shell]
----
java -jar clojure.jar
----

*Try Clojure online*

https://repl.it/languages/clojure[repl.it] provides a browser-based Clojure repl for interactive exploration.

*Build tools*

Build tools provide a range of capabilities for building, running, and deploying Clojure libraries and applications. The two most popular Clojure build tools are https://leiningen.org/[Leiningen] and http://boot-clj.com/[Boot].
