= Getting Started
Rich Hickey
2016-01-14
:type: guides
:toc: macro
:icons: font

ifdef::env-github,env-browser[:outfilesuffix: .adoc]

Welcome to Clojure!

== Brew install

If you are on Mac OS X, you can install the latest stable version of Clojure with:

[source,shell]
----
brew install clojure
----

Or the latest development version with:

[source,shell]
----
brew install --devel clojure
----

Then start the interactive REPL with:

[source,shell]
----
clj
----

You can find more info on using the `clj` and `clojure` scripts in the <<deps_and_cli#,Deps and CLI Guide>>.

== JAR Install

Clojure requires only http://java.sun.com/javase/downloads/index.jsp[Java] 1.6 or greater, plus the Clojure JAR file itself.

<<xref/../../community/downloads#,Download>> and unzip Clojure. In the directory in which you expanded clojure.zip, run:
[source,clojure]
----
java -cp clojure-1.8.0.jar clojure.main
----
This will bring up a read-eval-print loop (REPL). 

* Note: This process will not work in the latest development version (1.9.0-alpha...) as Clojure has been split into several jars. More info to come when 1.9 releases.

== Try Clojure Online

These sites provide browser-based Clojure repls for interactive exploration:

* https://repl.it/languages/clojure[repl.it]
* http://tryclj.com/[TryClojure]

== Leiningen

https://leiningen.org/[Leiningen] is a build and project management tool written in Clojure and used pervasively throughout the Clojure community. Follow the instructions there to install Leiningen.

Once it's installed you can start a REPL with:

[source,shell]
----
lein repl
----

== Boot

http://boot-clj.com/[Boot] is a build-focused DSL written in Clojure. Follow the Getting Started instructions to install Boot, then start a REPL with:

[source,shell]
----
boot repl
----

Check out the <<learn/syntax#,Learn Clojure>> pages or <<xref/../../community/resources#,Resources>> page to get started with tutorials and resources on learning Clojure!
