= Getting Started
Rich Hickey
2016-01-14
:type: guides
:toc: macro
:icons: font

ifdef::env-github,env-browser[:outfilesuffix: .adoc]

Welcome to Clojure!

== Minimal Install

Clojure requires only http://www.oracle.com/technetwork/java/javase/downloads/index.html[Java] 1.6 or greater, plus the Clojure JAR file itself.

<<xref/../../community/downloads#,Download>> and unzip Clojure. In the directory in which you expanded clojure.zip, run:
[source,clojure]
----
java -cp clojure-1.8.0.jar clojure.main
----
This will bring up a read-eval-print loop (REPL). 

* Note: This process will not work in the latest development version (1.9.0-alpha...) as Clojure has been split into several jars. More info to come when 1.9 releases.

== Try Clojure Online

This site provides a browser-based Clojure repl for interactive exploration:

* https://repl.it/languages/clojure[repl.it]

== Leiningen

https://leiningen.org/[Leiningen] is a build and project management tool written in Clojure and used pervasively throughout the Clojure community. Follow the instructions there to install Leiningen.

Once it's installed you can start a REPL with:

[source,shell]
----
lein repl
----

== Boot

http://boot-clj.com/[Boot] is a build-focused DSL written in Clojure. Follow the Getting Started instructions to install Boot, then start a REPL with:

[source,shell]
----
boot repl
----

Check out the <<learn/syntax#,Learn Clojure>> pages or <<xref/../../community/resources#,Resources>> page to get started with tutorials and resources on learning Clojure!
