= Getting Started
Alex Miller
2016-01-14
:type: guides
:toc: macro
:icons: font

ifdef::env-github,env-browser[:outfilesuffix: .adoc]

toc::[]

== Strategy for Beginners

Clojure is a hosted language; you will need the host platform, a library to translate Clojure code into a form the host understands, and a way of interacting with that library. The host platform for Clojure is the Java Virtual Machine (ClojureScript, a popular Clojure variant hosted in JavaScript, is not covered here) and it is assumed that you have already installed a recent version of Java. This guide will cover the remaining steps and after completing it you will have a viable environment for running Clojure code so you can experiment with the language.

Check out <<learn/syntax#,Learn Clojure>>, <<xref/../../community/resources#,Resources>>, or <<xref/../../community/books#,Books>> for learning the syntax. You are encouraged to read up on the <<repl/introduction#,repl>> and <<deps_and_cli#,built in CLI tools>> for real-time ways of accessing the Clojure library, tools to run Clojure programs, and the official tools to handle dependency management. Clojure's built in tools are a recent development (introduced with Clojure 1.9.0), and as of the <<xref/../../news/2019/02/04/state-of-clojure-2019#,2019 State of Clojure survey>> they are still less popular than the community supported https://leiningen.org/[Leiningen] build tool for managing projects.

Welcome to Clojure!

== Clojure installer and CLI tools

=== Installation on Mac via `brew`

Install the command line tools with brew:

[source,shell]
----
brew install clojure
----

If you've already installed, you can upgrade to the latest release with:

[source,shell]
----
brew upgrade clojure
----

=== Installation on Linux

1. Ensure that the following dependencies are installed: bash, curl, rlwrap, and Java.
2. Use the linux-install script to download and run the install, which will create /usr/local/bin/clj, /usr/local/bin/clojure, and /usr/local/lib/clojure:

[source,shell]
----
curl -O https://download.clojure.org/install/linux-install-1.10.0.411.sh
chmod +x linux-install-1.10.0.411.sh
sudo ./linux-install-1.10.0.411.sh
----

Platform installers (apt-get, etc) will be available in the future.

=== Installation on Windows

Not yet available - see https://leiningen.org/[Leiningen] or http://boot-clj.com/[Boot] instead.

== Other ways to run Clojure

*Local build*

Download and build Clojure from source (requires Git, Java, and Maven):

[source,shell]
----
git clone https://github.com/clojure/clojure.git
cd clojure
mvn -Plocal -Dmaven.test.skip=true package
----

Then start the REPL with the local jar:

[source,shell]
----
java -jar clojure.jar
----

== Try Clojure online

https://repl.it/languages/clojure[repl.it] provides a browser-based Clojure repl for interactive exploration.
