= Getting Started
Alex Miller
2016-01-14
:type: guides
:toc: macro
:icons: font

ifdef::env-github,env-browser[:outfilesuffix: .adoc]

toc::[]

Welcome to Clojure!

Check out <<learn/syntax#,Learn Clojure>>, <<xref/../../community/resources#,Resources>>, or <<xref/../../community/books#,Books>> to learn the language! If you have questions, you can search or ask at the official forum https://ask.clojure.org[Ask Clojure].

== Dependencies

Clojure requires Java. Clojure officially supports Java LTS releases (currently Java 8 and Java 11), but also tries to ensure interim versions work as well. You can use any Java installation, whether it's a commercial release from Oracle or an open source version based on OpenJDK (like adoptopenjdk).

The Clojure tools require that either the `java` command is on the path or that the `JAVA_HOME` environment variable is set.

== Clojure installer and CLI tools

Clojure provides <<deps_and_cli#,command line tools>> that can be used to start a Clojure repl, use Clojure and Java libraries, and start Clojure programs. 

Follow these instructions to install the latest release of the `clj` and `clojure` tools:

=== Installation on Mac via https://brew.sh[Homebrew]

Install the command line tools with `brew` from the https://github.com/clojure/homebrew-tools[clojure/tools tap]:

[source,shell]
----
brew install clojure/tools/clojure
----

If you've already installed this way in the past, you can upgrade to the latest release with:

[source,shell]
----
brew upgrade clojure/tools/clojure
----

=== Installation on Linux

To install with the Linux script installer:

1. Ensure that the following dependencies are installed: `bash`, `curl`, `rlwrap`, and `Java`.
2. Use the `linux-install` script to download and run the install, which will create the executables `/usr/local/bin/clj`, `/usr/local/bin/clojure`, and the directory `/usr/local/lib/clojure`:

[source,shell]
----
curl -O https://download.clojure.org/install/linux-install-1.10.2.774.sh
chmod +x linux-install-1.10.2.774.sh
sudo ./linux-install-1.10.2.774.sh
----

==== Custom location

To install to a custom location (like `/opt/infrastructure/clojure`), use the option `--prefix`:

[source,shell]
----
sudo ./linux-install-1.10.2.774.sh --prefix /opt/infrastructure/clojure
----

Extend the MANPATH in `/etc/man_db.conf` to include the manual pages:

[source]
----
MANPATH_MAP /opt/infrastructure/clojure/bin /opt/infrastructure/clojure/man
----

The `linux-install` script can be removed after installation.

=== Installation on Windows

An early release version of clj on Windows is available at https://github.com/clojure/tools.deps.alpha/wiki/clj-on-Windows[clj on Windows].
Please provide feedback on https://ask.clojure.org[Ask Clojure] or Clojurians slack in #clj-on-windows.

=== Other versions

See the <<xref/../../releases/tools#,changelog>> for version history and the https://github.com/clojure/homebrew-tools[Clojure tap] for info on installing older versions or newer prereleases instead.


== Other ways to run Clojure

*Local build*

Most Clojure users use Clojure jars downloaded from the Maven central repository (by the tools above or other Clojure build tools). However, you can also build Clojure from source with necessary dependent jars into a single executable jar (requires Git, Java, and Maven):

[source,shell]
----
git clone https://github.com/clojure/clojure.git
cd clojure
mvn -Plocal -Dmaven.test.skip=true package
----

Then start the REPL with the local jar (note this will not work with the jars in Maven as they do not include dependencies):

[source,shell]
----
java -jar clojure.jar
----

*Try Clojure online*

https://repl.it/languages/clojure[repl.it] provides a browser-based Clojure repl for interactive exploration.

== Next steps

* <<xref/../../community/tools#,Install editors and build tools>>
* <<guides/learn/syntax#,Start learning the Clojure basics>>
* <<xref/../../community/books#,Learn Clojure from a book>>
* <<xref/../../community/resources#,Explore Clojure communities and resources>>
* https://ask.clojure.org[Ask questions about Clojure]

