= Install Clojure
Alex Miller
2021-01-21
:type: guides
:toc: macro
:icons: font

ifdef::env-github,env-browser[:outfilesuffix: .adoc]

toc::[]

== Mac OS instructions

Prerequisites: <<install_clojure#brew,brew>>, <<install_clojure#java,Java>>

This adds the commands `clojure` and `clj` to your system from the https://github.com/clojure/homebrew-tools[clojure/tools tap]:

[source,shell]
----
brew install clojure/tools/clojure
----

== Linux instructions

Prerequisites: <<install_clojure#java,Java>>, `bash`, `curl`, `rlwrap`

To install with Linuxbrew (requires <<install_clojure#brew,brew>>):

[source,shell]
----
brew install clojure/tools/clojure
----

To install with the Linux script installer:

1. Ensure that the following dependencies are installed: `bash`, `curl`, `rlwrap`, and `Java`.
2. Use the `linux-install` script to download and run the install, which will create the executables `/usr/local/bin/clj`, `/usr/local/bin/clojure`, and the directory `/usr/local/lib/clojure`:

[source,shell]
----
curl -O https://download.clojure.org/install/linux-install-1.11.1.1208.sh
chmod +x linux-install-1.11.1.1208.sh
sudo ./linux-install-1.11.1.1208.sh
----

To install to a custom location (like `/opt/infrastructure/clojure`), use the option `--prefix`:

[source,shell]
----
sudo ./linux-install-1.11.1.1208.sh --prefix /opt/infrastructure/clojure
----

You may also want to extend the MANPATH in `/etc/man_db.conf` to include the manual pages:

[source]
----
MANPATH_MAP /opt/infrastructure/clojure/bin /opt/infrastructure/clojure/man
----

The `linux-install` script can be removed after installation.

== Posix instructions

A POSIX version of the linux installer is now available as well. This installer should work on Linux, BSD, and even Mac (but will conflict with brew!)

To install with the POSIX script installer:

1. Ensure that the following dependencies are installed: `bash`, `curl`, `rlwrap`, and `Java`.
2. Use the `posix-install` script to download and run the install, which will create the executables `/usr/local/bin/clj`, `/usr/local/bin/clojure`, and the directory `/usr/local/lib/clojure`:

[source,shell]
----
curl -O https://download.clojure.org/install/posix-install-1.11.1.1208.sh
chmod +x posix-install-1.11.1.1208.sh
sudo ./posix-install-1.11.1.1208.sh
----

To install to a custom location (like `/opt/infrastructure/clojure`), use the option `--prefix`:

[source,shell]
----
sudo ./posix-install-1.11.1.1208.sh --prefix /opt/infrastructure/clojure
----

You may also want to extend the MANPATH in `/etc/man_db.conf` to include the manual pages:

[source]
----
MANPATH_MAP /opt/infrastructure/clojure/bin /opt/infrastructure/clojure/man
----

The `posix-install` script can be removed after installation.

== Windows instructions

Prerequisites: <<install_clojure#java,Java>>

An early release version of clj on Windows is available at https://github.com/clojure/tools.deps.alpha/wiki/clj-on-Windows[clj on Windows].
Please provide feedback on https://ask.clojure.org[Ask Clojure] or Clojurians slack in #clj-on-windows.

== Prerequisite installation details

[[brew]]
=== brew (Mac or Linux)

`brew` is a package manager for Mac OS X or Linux. To install `brew`:

* Go to https://brew.sh/ and follow the installation instructions for your OS

[[java]]
=== Java

Clojure requires Java. Clojure officially supports Java LTS releases (currently Java 8, 11, and 17), but also tries to ensure interim versions work as well. You can use any Java distribution, whether it’s a commercial release from Oracle or an open source version based on OpenJDK (like Temurin). The Clojure tools require only that the `java` command is on the `PATH` or that the `JAVA_HOME` environment variable is set.

If you don't already hava Java installed, we recommend installing Adoptium Temurin 17.

To use the Adoptium Temurin installers:

* Go to https://adoptium.net/
* Download and run the installer appropriate to your platform
* Ensure `java` is on the system PATH

On Mac, you can also install Temurin using brew:

* `brew tap homebrew/cask-versions` - add the cask-versions tap to Homebrew
* `brew install --cask temurin17` - install Temurin 17 (formerly AdoptOpenJDK)

Check your Java version by running `java --version`. If that's not Temurin 17, then you may then need to add `java` to your `PATH`:

[source,shell]
----
echo 'export PATH="/Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home/bin:$PATH"' >> ~/.zshrc
----

== More information

For other versions of the Clojure command-line tools, see the <<xref/../../releases/tools#,changelog>> for version history and the https://github.com/clojure/homebrew-tools[Clojure tap] for info on installing older versions or newer prereleases instead.
