= Getting Started
Alex Miller
2021-01-21
:type: guides
:toc: macro
:icons: font

ifdef::env-github,env-browser[:outfilesuffix: .adoc]

toc::[]

== Mac OS instructions

=== Install brew

`brew` is a package manager for Mac OS X. To install `brew`:

* Go to https://brew.sh/ and follow the installation instructions

=== Install Java

Clojure requires Java. Clojure officially supports Java LTS releases (currently Java 8 and Java 11), but also tries to ensure interim versions work as well. If you don't already hava Java installed, we recommend installing adoptopenjdk 11.

* `brew tap adoptopenjdk/openjdk` - add the adoptopenjdk tap to brew
* `brew install adoptopenjdk11` - install adoptopenjdk 11 (you may need to enter your user password)

You then need to add `java` to your PATH:

[source,shell]
----
echo 'export PATH="/Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home/bin:$PATH"' >> ~/.zshrc
----

=== Install Clojure <<deps_and_cli#,command line tools>>

This adds the commands `clojure` and `clj` to your system from the https://github.com/clojure/homebrew-tools[clojure/tools tap]:

* `brew install clojure/tools/clojure`

== Linux instructions

=== Install Java

* Go to https://adoptopenjdk.net/ and follow the instructions
* OR use your package manager to install OpenJDK 11
* Ensure that `java` is in your path

=== Install Clojure <<deps_and_cli#,command line tools>>

To install with the Linux script installer:

1. Ensure that the following dependencies are installed: `bash`, `curl`, `rlwrap`, and `Java`.
2. Use the `linux-install` script to download and run the install, which will create the executables `/usr/local/bin/clj`, `/usr/local/bin/clojure`, and the directory `/usr/local/lib/clojure`:

[source,shell]
----
curl -O https://download.clojure.org/install/linux-install-1.10.1.763.sh
chmod +x linux-install-1.10.1.763.sh
sudo ./linux-install-1.10.1.763.sh
----

==== Custom location

To install to a custom location (like `/opt/infrastructure/clojure`), use the option `--prefix`:

[source,shell]
----
sudo ./linux-install-1.10.1.763.sh --prefix /opt/infrastructure/clojure
----

Extend the MANPATH in `/etc/man_dev.conf` to include the manual pages:

[source]
----
MANPATH_MAP /opt/infrastructure/clojure/bin /opt/infrastructure/clojure/man
----

The `linux-install` script can be removed after installation.

== Windows instructions

=== Install Java

* Go to https://adoptopenjdk.net
* Download and run the Windows installer
* Ensure `java` is on the system PATH (see this option on the Custom Setup page)

=== Install Clojure <<deps_and_cli#,command line tools>>

An early release version of clj on Windows is available at https://github.com/clojure/tools.deps.alpha/wiki/clj-on-Windows[clj on Windows].
Please provide feedback on https://ask.clojure.org[Ask Clojure] or Clojurians slack in #clj-on-windows.

== More information

For other versions of the Clojure command-line tools, see the <<xref/../../releases/tools#,changelog>> for version history and the https://github.com/clojure/homebrew-tools[Clojure tap] for info on installing older versions or newer prereleases instead.