= Install Clojure
Alex Miller
2021-01-21
:type: guides
:toc: macro
:icons: font

ifdef::env-github,env-browser[:outfilesuffix: .adoc]

toc::[]

== Mac OS instructions

Prerequisites: <<install_clojure#brew,brew>>, <<install_clojure#java,Java>>

This adds the commands `clojure` and `clj` to your system from the https://github.com/clojure/homebrew-tools[clojure/tools tap]:

[source,shell]
----
brew install clojure/tools/clojure
----

== Linux instructions

Prerequisites: <<install_clojure#java,Java>>, `bash`, `curl`, `rlwrap`

To install with Linuxbrew (requires <<install_clojure#brew,brew>>):

[source,shell]
----
brew install clojure/tools/clojure
----

To install with the Linux script installer:

1. Ensure that the following dependencies are installed: `bash`, `curl`, `rlwrap`, and `Java`.
2. Use the `linux-install` script to download and run the install, which will create the executables `/usr/local/bin/clj`, `/usr/local/bin/clojure`, and the directory `/usr/local/lib/clojure`:

[source,shell]
----
curl -O https://download.clojure.org/install/linux-install-1.10.1.763.sh
chmod +x linux-install-1.10.1.763.sh
sudo ./linux-install-1.10.1.763.sh
----

To install to a custom location (like `/opt/infrastructure/clojure`), use the option `--prefix`:

[source,shell]
----
sudo ./linux-install-1.10.1.763.sh --prefix /opt/infrastructure/clojure
----

You may also want to extend the MANPATH in `/etc/man_db.conf` to include the manual pages:

[source]
----
MANPATH_MAP /opt/infrastructure/clojure/bin /opt/infrastructure/clojure/man
----

The `linux-install` script can be removed after installation.

== Windows instructions

Prerequisistes: <<install_clojure#java,Java>>

An early release version of clj on Windows is available at https://github.com/clojure/tools.deps.alpha/wiki/clj-on-Windows[clj on Windows].
Please provide feedback on https://ask.clojure.org[Ask Clojure] or Clojurians slack in #clj-on-windows.

== Prerequisite installation details

[[brew]]
=== brew (Mac or Linux)

`brew` is a package manager for Mac OS X. To install `brew`:

* Go to https://brew.sh/ and follow the installation instructions

[[java]]
=== Java

Clojure requires Java. Clojure officially supports Java LTS releases (currently Java 8 and Java 11), but also tries to ensure interim versions work as well. If you don't already hava Java installed, we recommend installing adoptopenjdk 11.

To use the adoptopenjdk installers:

* Go to https://adoptopenjdk.net
* Download and run the installer appropriate to your platform
* Ensure `java` is on the system PATH (see this option on the Custom Setup page)

On Mac, it is also possible to install using brew:

* `brew tap adoptopenjdk/openjdk` - add the adoptopenjdk tap to brew
* `brew install adoptopenjdk11` - install adoptopenjdk 11 (you may need to enter your user password)

You then need to add `java` to your PATH:

[source,shell]
----
echo 'export PATH="/Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home/bin:$PATH"' >> ~/.zshrc
----

== More information

For other versions of the Clojure command-line tools, see the <<xref/../../releases/tools#,changelog>> for version history and the https://github.com/clojure/homebrew-tools[Clojure tap] for info on installing older versions or newer prereleases instead.
