= Dutch Clojure Days free conference
2026-05-09
:jbake-type: event
:jbake-edition: 
:jbake-link: https://clojuredays.org
:jbake-location: Herengracht 23, 1382 AG Weesp
:jbake-start: 2026-05-09
:jbake-end: 2026-05-09

== Dutch Clojure Days free conference

Dutch Clojure Days conference 2026 +
 +
The Dutch Clojure Days conference returns in May 2026 +
After a four years hiatus, the ClojureDays Foundation is happy to announce the 2026 edition of the Dutch Clojure Days free conference! +
You can expect the usual DCD vibe: a full day filled with inspirational talks alongside an informal and welcoming atmosphere, all while surrounded by wonderful, like minded people. +
Oh and did I mention that it's still a FREE event? ( ????) !! +
This time around we're coming to the picturesque Amsterdam city district of Weesp, where we'll sit in the local theater City of Wesopa. +
A few useful pointers and important dates: +
- ? the conference itself: Saturday, May 9th 2026 https://clojuredays.org +
- ? we are now looking for sponsors: hosting a free conference means we need all the support we can get from you and your companies. Get in touch if you want to contribute to DCD26! https://clojuredays.org/#packages +
- ? the call for papers is not yet open: you will be able to submit your proposal between November 1st 2025 and January 15th 2026. Better start brewing some good content! https://clojuredays.org/#cfp +
- ?? get your ticket: yes, the event is completely free of charge BUT you still need to reserve your seat. Beware: space is limited, you have been warned https://clojuredays.org/#tickets +
Looking forward to meeting you all again next year in May +
 +
 +
Zulip: https://clojurians.zulipchat.com/#narrow/stream/262224-events/near/541677994 +

