= Scicloj AI Meetup: Agent-o-rama
2026-01-17
:jbake-type: event
:jbake-edition: 
:jbake-link: https://clojureverse.org/t/scicloj-ai-meetup-agent-o-rama/14782
:jbake-location: online
:jbake-start: 2026-01-17
:jbake-end: 2026-01-17

== Scicloj AI Meetup: Agent-o-rama

Please rsvp  +
This meeting of the scicloj-ai-meetups series will host Nathan Marz, focusing on the Agent-o-rama LLM agent platform. +
Joining  +
 +
Please mark your participation using the Your rsvp button at the top of this page (requires Clojureverse login). +
Please join the Clojurians Zulip chat beforehand. +
You can also use the Add to Calendar button to add the event to your calendar. +
 +
Agenda +
 +
talk +
discussion +
 +
Zoom +
 +
Video meeting: Launch Meeting - Zoom - please do not share this link anywhere  +
 +
Chat +
We will use the #scicloj-ai-meetups channel of the Clojurians Zulip Chat (requires login). Please join the Zulip chat before attending our meetings. +
Length +
The official session will run for 90 minutes. +
Informal discussions may continue afterwards for those interested. +
Recording +
Parts of the meeting will be recorded and may or may not be shared publicly. +
Some parts will remain unrecorded. +
 +
Zulip: https://clojurians.zulipchat.com/#narrow/stream/262224-events/near/558924141 +

